### ISSUE TITLE
RFTools and EnderTanks Crash on 1.10.2

### ISSUE THREAD

**Issue by calebh514** [ShetiPhian/Localizations-and-Issues#10]
I'll post this issue here, but mention @McJty , hopefully he'll see it and can provide input. 

---

Crash Log: http://pastebin.com/hbseuFdL

---

Whenever using an RFTools Builder to pump liquid into an EnderTank the game crashes. Simple as that. 

I first experienced this in the FTB Infinity Lite 1.10 modpack, but I tested it with the latest versions of just Forge, RFTools, EnderTanks, and the required libraries as the crash log will show.

**Comment by McJty** [comment]
That looks like a bug in endertanks as I'm just accessing the capability as it should. Note that I'm using 'facing' == null which seems to be the problem. And yes, facing == null is legal for capabilities. That is supposed to access the tank (or items for item handler) internally without using a side.

So not a bug in rftools

**Comment by McJty** [comment]
BTW for reference: this is the documentation that goes with ICapabilityProvider:

    /**
     * Determines if this object has support for the capability in question on the specific side.
     * The return value of this MIGHT change during runtime if this object gains or looses support
     * for a capability.
     *
     * Example:
     *   A Pipe getting a cover placed on one side causing it loose the Inventory attachment function for that side.
     *
     * This is a light weight version of getCapability, intended for metadata uses.
     *
     * @param capability The capability to check
     * @param facing The Side to check from:
     *   CAN BE NULL. Null is defined to represent 'internal' or 'self'
     * @return True if this object supports the capability.
     */
    boolean hasCapability(Capability<?> capability, @Nullable EnumFacing facing);

And there you see the 'CAN BE NULL' comment

**Comment by calebh514** [comment]
So to remedy the issue for now would be to pump into something like an ExtraUtils2 Drum and then into the EnderTank. 

Thanks for the help :)

**Comment by ShetiPhian** [comment]
I'll add a null check to stop issues like this from happening again.


May I ask why your passing null?
As the documentation points out null is for internal or self, neither of which other mods would be.
You could be passing the opposite of the direction offset you used to get the tile entity, providing the capability, as the facing variable.

**Comment by McJty** [comment]
This is exactly meant for other mods. The idea with passing null is that other mods that don't access from a given side can access the internal contents anyway. There are plenty of mods that allow direct access or remote access which doesn't involve any side. You are supposed to give access to all fluid (or item) slots when passing null

**Comment by ShetiPhian** [comment]
If that is indeed the intended function then the documentation needs to be changed to indicate null is 'full/all access' as internal and self do not imply the function you describe.

But regardless if the documentation is wrong or not;
I've uploaded new build for 1.10 that accepts unknown sides. 

Still see no reason for you passing null; you have the side, your specifically defining it, but proceed to toss it and pass null.
Did you run into a mod that didn't work when providing a side? My tanks can pump in/out of other fluid inventories, I'll have the same incompatibility.

**Comment by McJty** [comment]
I have a few use cases for this:

a) I have a tank that can only change access by right clicking the specific side with a wrench. It has no GUI. Since the builder is already at the side that you want to give access this is annoying as then you would have first to get rid of the builder to be able to change the mode. So this is why the builder accesses the tank without side. I *could* possibly change that with multiple detection but even then there is:

b) The RFTools liquid monitor can monitor tanks without being directly adjacent to it. It works in a 3x3x3 area around the monitor. So it doesn't have a side.

c) The One Probe shows complete tank information when looking at a tank regardless of side. Because it would be annoying to have to watch the given side (especially when that is not accessible with a builder below it or something else) to be able to see what liquid is in it.

**Comment by ShetiPhian** [comment]
Makes sense, without using null you'd need to check all six sides individually. Get a a few liquid monitors watching several tanks and that could become costly quickly.
