### ISSUE TITLE
Coremod does not load under 1.12.1

### ISSUE THREAD

**Issue by krwminer** [ShetiPhian/Localizations-and-Issues#100]
Not sure it is possible to work on both 1.12 and 1.12.1, but would be nice.

**Comment by ShetiPhian** [comment]
The MC version check doesn't accept ranges.
I'll just disable the check again.

**Comment by ShetiPhian** [comment]
Fixed in 3.5.1
https://minecraft.curseforge.com/projects/shetiphiancore/files/2470543
