### ISSUE TITLE
Suggestion: Config for Bones drops

### ISSUE THREAD

**Issue by davqvist** [ShetiPhian/Localizations-and-Issues#101]
I wonder if it would be possible to add a similar config like for the Small Stones for Bones to define what they can drop. This would be very helpful for the pack I'm working on.

Terraqueous 1.4.0.3
MC 1.12.1
Forge 2456

**Comment by ShetiPhian** [comment]
In the next build all doodads have their own whitelist and blacklist.

**Comment by davqvist** [comment]
Very cool, thanks very much.

**Comment by ShetiPhian** [comment]
Added in 1.4.1
https://minecraft.curseforge.com/projects/terraqueous/files/2470605
