### ISSUE TITLE
Suggestion: Null for small stones and tiny dust for copper etc.

### ISSUE THREAD

**Issue by Blatts12** [ShetiPhian/Localizations-and-Issues#102]
Add null to small stone whitelist = chance to no drop

Add more tiny dusts(copper, tin, silver, nickel, lead)

I recolored yours iron tiny dust
http://imgur.com/a/Aqcz8

Thank you in advanced

**Comment by ShetiPhian** [comment]
Tiny dusts are currently being considered for removal. They don't add anything to the gameplay, and without four they are useless, just wasting inventory space.

In the next build all doodads will support a whitelist and have a drop chance config setting.

**Comment by ShetiPhian** [comment]
Added in 1.4.1
https://minecraft.curseforge.com/projects/terraqueous/files/2470605
