### ISSUE TITLE
[1.12][MultiStorage] No recipe for vault blocks

### ISSUE THREAD

**Issue by angelnc1989** [ShetiPhian/Localizations-and-Issues#105]
No matter to what I change the config line for vault blocks there is no recipe to craft them.

>            # Adds Vault Block crafting recipes
>            # 0 = Only doors and concrete are craftable, everything else must be poured in world
>            B:enableVaultWallRecipes=false

I tried true, false, numbers... nothing works.

**Comment by ShetiPhian** [comment]
The '0 =' is a typo (left over from the old description)
enableVaultWallRecipes is a Boolean now, only true or false works.
(game needs to be restarted for the recipes to be created)

The recipes could be broken though.
I set the system up while Forge was in beta, the format may have changed.

**Comment by angelnc1989** [comment]
I guess they are broken then. I definitly tried "true".

**Comment by ShetiPhian** [comment]
Yep broken, and by me when I converted the configs, wasn't loading the lists before the recipes needed them.

**Comment by ShetiPhian** [comment]
Fixed in 1.4.1
https://minecraft.curseforge.com/projects/multistorage/files/2470532
