### ISSUE TITLE
Fruit trees do not drop saplings Terraqueous 1.12.0-1.4.2

### ISSUE THREAD

**Issue by CplPibald** [ShetiPhian/Localizations-and-Issues#108]
MC 1.12.2
forge-1.12.1-14.22.0.2463

I upgraded Terraqueous from 1.4.0.3 to 1.4.2, and fruit trees no longer drop saplings.  

Players noticed that chopping trees don't give saplings.  Confirmed by spawning 10,000 leaf blocks (plum, lemon, apple, mango) using worldedit.  I'm using default configs.

**Comment by CplPibald** [comment]
It also appears that fruit saplings aren't growing, even when spawned in with /give, or planted from saplings collected in the previous version.

**Comment by ShetiPhian** [comment]
All tree events where not working anymore after changing from hard coded values to user settable.

Shouldn't be long before Curse makes the new build available:
https://minecraft.curseforge.com/projects/terraqueous/files/2475266
