### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Chupp4-Jo3** [ShetiPhian/Localizations-and-Issues#11]
Game crashed while reloading world after using the Minecraft Comes Alive crystal ball and specifying preferences.

http://pastebin.com/09bUt1EG

I assume there was something that didn't like the whole Redo the World thing

Need any more info please ask :)

**Comment by ShetiPhian** [comment]
Crash happens while reading the names retrieved by OreDictionary.getOreNames()
Somehow the redo has put the OreDictionary into a broken state, don't know how broken, but there is now nulls in a list that shouldn't have any.

I added a null check, new version is up.
