### ISSUE TITLE
[Terraqueous] Rampant plant growth

### ISSUE THREAD

**Issue by ouroborus** [ShetiPhian/Localizations-and-Issues#112]
I like the idea of spreading plants, but the spread rate seems excessive. If a player settles down somewhere (or just chunkloads an area for about a real day) the plant life quickly gets out of hand, turning the area into a thicket of double tall grass and dense flower and bush growth.

Some thoughts I had on mitigating this:
 * Placed plants don't spread. If a plant is generated as part of worldgen, it spreads normally. If a plant is placed by other means, it doesn't spread. This would help a lot in situations where you're trying to use the plants for decoration.
   * Another possibility is having a tool that a player can use to turn growth or spreading on/off of individual plants and to examine these states.
 * The more of a particular plant in an area, the less it spreads and/or the slower it grows.
   * In the interest of preventing server lag for such a thing, it may be useful to implement this such that each plant has a NBT item or similar that tracks local count. When a plant is added or removed by any means, the counts of surrounding plants of the same type are updated accordingly. At the same time, this scan is used to determine the newly placed plant's own value. Growth/spread chance could easily take this into account without having to constantly re-scan.

**Comment by ShetiPhian** [comment]
These will need to wait for 1.13 as the metadata limitation is finally getting removed.
Currently I'd either have to use tile entities, or extra block id's. Tile entity's should be used sparingly and not on abundant blocks, and using extra id's would be a waste of the limited available, especially when the meta limit is gone in the next Minecraft version.

I could scan the area on each spread attempt, but as you also noted it would cause server lag.
As an interim work around, there are config options to control the growth.
If you don't want to disable it all together you can lower the chance, or even restrict it to only while its raining.

Plants also do not spread to/from the planters I added.

**Comment by VallenFrostweaver** [comment]
Is there currently a way to turn off plant spread/grass growth? Doubletall grass is not something I like everywhere I frequent.

**Comment by ShetiPhian** [comment]
@VallenFrostweaver 
config > tweaks > plants

# '1 in x' chance the grass will become double tall on the next block update
grass_Grow_normal
grass_Grow_rain

# '1 in x' chance the grass will spread on the next block update
grass_Spread_normal
grass_Spread_rain

setting those to zero disables it

**Comment by VallenFrostweaver** [comment]
Oof. I completely overlooked that. XD
