### ISSUE TITLE
ServerSide Crash - MultiStorage 1.12.1

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [ShetiPhian/Localizations-and-Issues#114]
Details:
	Minecraft Version: 1.12.1
	Operating System: Windows Server 2012 R2 (amd64) version 6.3
	Java Version: 1.8.0_144, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 871088472 bytes (830 MB) / 2073300992 bytes (1977 MB) up to 8520204288 bytes (8125 MB)
	JVM Flags: 8 total; -Xms1g -Xmx8g -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:MaxGCPauseMillis=40 -XX:CMSInitiatingOccupancyFraction=70 -XX:+CMSScavengeBeforeRemark -XX:+AggressiveOpts
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
FML: MCP 9.41 Powered by Forge 14.22.1.2481 122 mods loaded, 122 mods active

multistorage | 1.4.2 | multistorage-1.12.0-1.4.2.jar

https://gist.github.com/P3rf3ctXZer0/5a84e794678cbb4e7f308ec6c56d1729

**Comment by ShetiPhian** [comment]
Sorry about that, normally getSubItems is not called server side (it was marked as client side only) so the issue never came up. Craft Tweaker however is using it, bring to light a dumb decision by Mojang I didn't notice earlier. (Despite the data existing on both client and server, Mojang marked the read method client only.)

I used my access transformer to give direct access to the variable, and updated the five locations it was used.
This test build should fix your issue:
http://www.mediafire.com/file/zcsxl8n1dxl9212/multistorage-1.12.0-1.4.3-TEST-1.jar

**Comment by P3rf3ctXZer0** [comment]
Fixed
