### ISSUE TITLE
NULL folder at .\minecraft 

### ISSUE THREAD

**Issue by PWaksman** [ShetiPhian/Localizations-and-Issues#116]
There is a NULL folder in the minecraft root folder %appdata%\.minecraft

I'm not sure if it is this mod that create it, but looks like it is. Probably miss some variable initialization that is getting null

with this structure.

- %appdata%\.minecraft
- - null
- - - endertanks
- - - - [-Public-].dat

[.minecraft\null\endertanks]

**Comment by ShetiPhian** [comment]
I'm rather sure of the exact code producing this error, and have a good idea why and a possible solution.

Doesn't look like I'll get the time to fix it this weekend as I originally though though.

**Comment by ShetiPhian** [comment]
Fixed in:
endertanks-1.12.0-1.6.1
https://minecraft.curseforge.com/projects/endertanks/files/2490815

multistorage-1.12.0-1.4.4
https://minecraft.curseforge.com/projects/multistorage/files/2490814
