### ISSUE TITLE
snow

### ISSUE THREAD

**Issue by bob0bob** [ShetiPhian/Localizations-and-Issues#118]
When it snows. your platforms do not show the snow correctly.  The snows shows on the block above the platform.  So if it is a slab platform.  the snows shows up the block above.  but there is is air in between.  I included the screen shot.
![2017-10-08_03 15 47](https://user-images.githubusercontent.com/30982580/31315117-21f3e660-abd7-11e7-8cee-6c67d0ab1177.png)

**Comment by ShetiPhian** [comment]
With the removal of BlockState limitations in Minecraft 1.13 I should be able to create a proper snowy state.

Anyhow back to the issue.
The blocks are passing the snows can place check, I'll need either make that fail or remove the snow when it triggers a neighbor update.

Unfortunately I don't know when I'd get the chance to do that, thinking at least a few weeks out.

**Comment by ShetiPhian** [comment]
Fixed in 1.12.0-1.4.1
https://minecraft.curseforge.com/projects/platforms/files/2490802
