### ISSUE TITLE
Entertanks data location

### ISSUE THREAD

**Issue by utoc** [ShetiPhian/Localizations-and-Issues#12]
Greetings

I've noticed in the current release of EnderTanks, 1.4.7, that data is stored literally in "world\endertanks" rather than a subdirectory of world called endertanks.

Here is a screenshot because this is quite a unique issue: http://i.imgur.com/Wqjs7Wp.jpg

**Comment by ShetiPhian** [comment]
I forgot Unix systems don't use '\' as a separator, before the save rework I had '/' and thought it was a typo I made so I changed it to the Windows standard.
Ive switched to  'File.separator' as I should have done in the first place.

Curse has the the new versions of EnderTanks and MultiStorage

**Comment by utoc** [comment]
Thanks!
