### ISSUE TITLE
[Terraqueous, 1.12.2] Wool recipe doesn’t work

### ISSUE THREAD

**Issue by PapiDimmi** [ShetiPhian/Localizations-and-Issues#122]
![recipe](https://user-images.githubusercontent.com/25916106/32685768-0fc548a4-c698-11e7-9a65-1d4da650f1f2.png)
![crafting](https://user-images.githubusercontent.com/25916106/32685767-0fa84916-c698-11e7-8c97-5670b46edcac.png)

Terraqueous version: 1.12.0-1.4.4
Minecraft version: 1.12.2

**Comment by ShetiPhian** [comment]
Is this option set to true? Config > Crafting > enableWoolToString
Is this a modpack? it may have used Craft Tweaker, or similar mod, to disable it.

If its not the above the issue is a mod conflict.
I'll need the mod list so I can find, and possibally solve it

**Comment by PapiDimmi** [comment]
I tested this in a new game with only Terraqueous and ShetiPhianCore, and the recipe still didn’t work, so it’s definitely not a mod conflict or a CraftTweaker script. I used the default Terraqueous config, in which the wool recipe is enabled.

###Versions:
Minecraft: 1.12.2
Forge: 14.23.0.2537
Terraqueous: 1.12.0-1.4.5
ShetiPhianCore: 1.12.0-3.5.4

**Comment by PapiDimmi** [comment]
I tested this in a new game with only Terraqueous and ShetiPhianCore, and the recipe still didn’t work, so it’s definitely not a mod conflict or a CraftTweaker script. I used the default Terraqueous config, in which the wool recipe is enabled.

**Versions**:
Minecraft: 1.12.2
Forge: 14.23.0.2537
Terraqueous: 1.12.0-1.4.5
ShetiPhianCore: 1.12.0-3.5.4

**Comment by ShetiPhian** [comment]
Okay looks like Forge broke something -_-
Now to find out what version after 2509 it happens in and then figure out what they changed and why it is breaking this simple recipe.

**Comment by ShetiPhian** [comment]
Looks like 2532 broke using wildcards for meta on hard coded recipes.
Its not worth reporting though as Forges stance is all recipes should be json files now and those are unaffected.

I coded the recipes before _factories.json was a thing, and haven't gone back to convert the few that I couldn't originally.
Until I get the time to do that, wool to string and coal to dust will not work on Forge builds past 2531

**Comment by PapiDimmi** [comment]
All right. Thanks.

Do you think I should go back to using Forge 2531 when playing the modpack I’m playing so that the recipes work, or would that break some mods?

Anyway, I hope that this is fixed soon. This isn’t the only mod that has a problem like this; [I found a similar problem with Vazkii’s Quark mod](Vazkii/Quark/issues/676), which was probably also caused by Forge 2532.

**Comment by PapiDimmi** [comment]
All right. Thanks.

Do you think I should go back to using Forge 2531 when playing the modpack I’m playing so that the recipes work, or would that break some mods?

Anyway, I hope that this is fixed soon. This isn’t the only mod that has a problem like this; I found a similar problem with Vazkii’s Quark mod, which was probably also caused by Forge 2532 (Vazkii/Quark/issues/676).

**Comment by ShetiPhian** [comment]
Shouldn't have any issues going back a few Forge versions, and I doubt any mods have already made it an requirement.

Probably is the same issue,
Wool is the most likely block this issue will appear for, as it doesn't have an Ore Dictionary entry so most recipes will just use the wild card.

**Comment by PapiDimmi** [comment]
This was fixed in Forge version 14.23.0.2542.
