### ISSUE TITLE
[FTB Horizons: III Minecraft 1.12.2] Render Crash

### ISSUE THREAD

**Issue by Jacques0726** [ShetiPhian/Localizations-and-Issues#124]
I am randomly crashing from placing a Private EnderLink Chest and the crash log is almost always mentioning the EnderLink chest. Its annoying due to that its the only thing similar to Ender Storage in the pack.
If you need any more information, just ask since this is the first Issue I've ever reported...

**Comment by ShetiPhian** [comment]
I'll need your crash report.
Paste it into either a 'gist.github.com' or 'pastebin.com' and post the url here.

**Comment by Jacques0726** [comment]
Here you go: [https://gist.github.com/Jacques0726/3b513f00a6ca395061c6a9a3c5a80de8](url)
I can only see it saying its a rendering issue, but its so random, only really happens to private ones, works fine when placing public Enderlink chests then changing them to private though...

**Comment by ShetiPhian** [comment]
I can't seem to reproduce the bug.
But based on the line having the error it appears to be a bad tile entity packet was received.
While the packet send and receive system is not part of my code, the processing is so I'll add crash prevention there.

Just running a test build now,

**Comment by ShetiPhian** [comment]
Here is the test builds
http://www.mediafire.com/?6dbe5477eb7el

You'll need to update ShetiPhianCore as those builds also fix not being able to break a tank/chest after making a team one.

**Comment by Jacques0726** [comment]
Thanks for the responses, but I wouldn't be able to test if it fixes the issue since it happens on a sponge server I play on (do not own) maybe it will not happen after the server updates to the latest version of the pack, not sure. You could mark this as closed.

**Comment by ShetiPhian** [comment]
Files have been uploaded to Curse.
