### ISSUE TITLE
[Minecraft 1.11.2 - Terraqueous-1.11.0-1.3.17] Fruit trees won't drop their saplings

### ISSUE THREAD

**Issue by YswMusician** [ShetiPhian/Localizations-and-Issues#129]
*Sorry for multiple posts. I don't know the reason.

Tested with just ShetiPhianCore and the Newest version of Terraqueous for 1.11.
After mod installation or after config deletion, fruit trees drop their saplings as usual.
But just after restarting Minecraft, trees won't drop their saplings.

(I also tested with Minecraft 1.12.2 and it works without problem)

Interestingly, copying config file from 1.12.2 to 1.11.2 fixes this problem! Maybe there are problem with config, I guess?

**Comment by ShetiPhian** [comment]
The config format changed in 1.12, using it in 1.11 would cause the defaults to be added to the file (similar to deleting the file, but now 1.12 and 1.11 settings exist)

Looks like I was missing a load trigger, give this build a try.
https://www.mediafire.com/file/d21akkgx6u4nb9n/terraqueous-1.11.0-1.3.18.jar

**Comment by YswMusician** [comment]
Yes, 1.12 config copyied to 1.11 didn't fix problem completely. No saplings after restarting game.

And, hooray, new build works. I re-started game after I have checked that there's config generated and it works.

**Comment by ShetiPhian** [comment]
I've removed the test build as Curse now has the release with the fix
