### ISSUE TITLE
Its not possible to color ender tanks

### ISSUE THREAD

**Issue by Darkere** [ShetiPhian/Localizations-and-Issues#13]
I tried coloring with lapis and red dye nothing happens when I click on the white stripes.
Version 1.11 -1.5.0.1

**Comment by ShetiPhian** [comment]
There was a bug in the OreDictionary, but I'm sure that was fixed after another breaking change so 1.5.0.1 won't run on it.

I stopped doing builds after they where becoming incompatible within 12hrs, but as of a few hours ago Forge has a release build now. Its unlikely any more breaking changes will be done.

**Comment by ShetiPhian** [comment]
1.11.0-1.5.1 works with the release build of Forge and is available on Curse now.
