### ISSUE TITLE
3.4.8 crashes dedicated server Forge 1.11.2 build 2530 with nosuchmethod error

### ISSUE THREAD

**Issue by kreezxil** [ShetiPhian/Localizations-and-Issues#130]
crash report:
https://gist.github.com/cd04ada6135eb6d9e7512c29e5abbaa0

fml server latest:
https://gist.github.com/387ba7aa7ae00489679c52adc55ea0f2

possibly related to #123 

In my case I have no blacklist mod and I also tried his advice and wiped my configs to no success. This was not an issue with the immediately prior version.

**Comment by ShetiPhian** [comment]
I have that call in a try/catch but I guess that isn't always working.

I made a quick change to the code path, should solve the bug.
https://www.mediafire.com/file/8j74bclubcuthuz/shetiphiancore-1.11.0-3.4.9.jar
