### ISSUE TITLE
[suggestion] (Terraqueous) separate enabling and disabling each fruit individually.

### ISSUE THREAD

**Issue by majijn** [ShetiPhian/Localizations-and-Issues#132]
I would like to keep coconuts disabled, but not the other fruits from the mod.

because when i walk next to/on top of the coconut entities things act weird.

is that something that could be done?

**Comment by ShetiPhian** [comment]
config > tweaks > trees > fruit_grow > coconut = 0
That will stop coconuts from growing by causing it to fail its should grow check.
Ones currently in world, including ones that are currently growing, will not be removed. You'll need to break them either by punching or using a liquid.


_"walk next to/on top of the coconut entities things act weird"_
Is this referring to your movement when colliding with a coconut?

**Comment by majijn** [comment]
yep, it's almost like the game doesn't know if I should walk on top of the coconut or just push it.

also thanks !

**Comment by ShetiPhian** [comment]
Starting in the newest build, coconuts no longer push players.
