### ISSUE TITLE
no dimension blacklist for plants

### ISSUE THREAD

**Issue by Hypsellis** [ShetiPhian/Localizations-and-Issues#134]
There is no way to prevent Terraqueous plants to spawn in other dimensions where they shouldn't.

**Comment by ShetiPhian** [comment]
I expanded the cloud blacklist code into the rest of my generators.
Config > Generator > Dim_Blacklist

http://www.mediafire.com/file/89t934xffy559sz/terraqueous-1.12.0-1.4.6-TESTER.jar

**Comment by ShetiPhian** [comment]
Feature available in the newest build
