### ISSUE TITLE
Fast Leaf Rendering Support.

### ISSUE THREAD

**Issue by KaneHart** [ShetiPhian/Localizations-and-Issues#135]
**Versions:**
terraqueous-1.12.0-1.4.5.jar
forge-1.12.2-14.23.1.2566-universal.jar

Fast leaf rendering important for performance and even looks. Sadly the mod does not seem to be supporting it right now. 

![yw5nfgh](https://user-images.githubusercontent.com/425853/34084135-847bc9d4-e349-11e7-8a97-15a79e1d41a0.png)

**Comment by ShetiPhian** [comment]
The default Fast/Fancy toggle is supported.
Your leaves are in fast but the clouds are fancy, I take it OptiFine was used to change only the leaves.

Due to some previous code changes, I think I can support this with a few simple changes.

**Comment by ShetiPhian** [comment]
After looking at the code I couldn't do it the way I originally thought.

Here is a test build with a different workaround:
http://www.mediafire.com/file/89t934xffy559sz/terraqueous-1.12.0-1.4.6-TESTER.jar

**Comment by ShetiPhian** [comment]
Should be fixed in the newest build
