### ISSUE TITLE
[1.4.5] crashes client when used with forge 1.12.2 b2577

### ISSUE THREAD

**Issue by kreezxil** [ShetiPhian/Localizations-and-Issues#136]
https://pastebin.com/S9u2D3xr

as you can see the only mods in this report are yours. :)

**Comment by ShetiPhian** [comment]
Drop back to Forge build 2575,

I'll need to see what they changed in 2576 that causes their model loader to fail when loading my models.

**Comment by ShetiPhian** [comment]
Found the problem,
Forge is now sensitive to a very old code error I made back when the model system was first introduced in a method that appeared to be unused and was undocumented.

**Comment by ShetiPhian** [comment]
Fixed in the newest build,
Issue existed in both Terraqueous and platforms
