### ISSUE TITLE
Terraqeuous 1.12.2 Cloud Amulet can not be equiped as bauble

### ISSUE THREAD

**Issue by NotAVerb** [ShetiPhian/Localizations-and-Issues#137]
Baubles is installed, yet the cloud amulet refuses to enter any of the bauble slots.

**Comment by ShetiPhian** [comment]
I was still using Baubles old mod id, causing the support code not to see it and thus not load.
New build has been upload to Curse: https://minecraft.curseforge.com/projects/terraqueous/files/2517841
