### ISSUE TITLE
Terraqueous 1.12.2 Flora in the Aether and Twilight Forest

### ISSUE THREAD

**Issue by NotAVerb** [ShetiPhian/Localizations-and-Issues#138]
Flowers can spawn in both dimensions.
Fruit trees can spawn in the Twilight Forest, but I'm uncertain about the Aether. 

Configuration options to further fine tune generation would be much appreciated.

**Comment by ShetiPhian** [comment]
You'll need to get the name of the DimensionType (may need to ask the mod author)
Then add the name to the blacklist for the generator you with to disable
Blacklists can be found here: Config > generator > dim_blacklist

**Comment by NotAVerb** [comment]
Wow, I don't know how I missed that option.
Using AetherI worked liked a charm.

**Comment by ShetiPhian** [comment]
Option is quite new, has only existed since Dec 18, prior to that it was limited  to the cloud generator.
