### ISSUE TITLE
drying grass blocks replace any block above them if placed on top of an existing drying grass block

### ISSUE THREAD

**Issue by majijn** [ShetiPhian/Localizations-and-Issues#139]
I had noticed that my tall grass sometimes disappeared when I was placing them on top of eachother, I placed a stone brick block on top of a drying grass, and sure enough, it was destroyed by the loose hay/drying grass that replaced it.

it can probably replace otherwise unbreakable blocks.

![2017-12-29_08 17 47](https://user-images.githubusercontent.com/18368034/34640767-7a4abadc-f2f9-11e7-8c2f-384d037ac51f.png)
![2017-12-29_08 17 51](https://user-images.githubusercontent.com/18368034/34640768-7cba8108-f2f9-11e7-8206-acf590271b2b.png)

**Comment by ShetiPhian** [comment]
Fixed, just need to look into the baubles bug that was reported then I'll push an update to Curse.
