### ISSUE TITLE
Sideways tanks?

### ISSUE THREAD

**Issue by Darkere** [ShetiPhian/Localizations-and-Issues#14]
Are you supposed to be able to place the tanks sideways like on the picture on curse? If so its most likely not working.
Version 1.11 -1.5.0.1

**Comment by ShetiPhian** [comment]
It is currently a wrench only  feature.

**Comment by Darkere** [comment]
ok got it to work with a refined storage wrench

**Comment by ShetiPhian** [comment]
In the new builds tanks now place rotated based on the face clicked, and wrenches can still rotate them.
