### ISSUE TITLE
[1.12.2] [Platforms 1.4.3] Ingot oredictionary entries 

### ISSUE THREAD

**Issue by wamc2017** [ShetiPhian/Localizations-and-Issues#140]
Hi,

I updated platforms from version 1.4.2 to version 1.4.3 today and had some issues with ingots from several mods and from vanilla minecraft. The oredictionary entries from the ingots are removed after the update. 
Before the update:
![oredict2](https://user-images.githubusercontent.com/33242447/35190440-2bcee63e-fe62-11e7-85cd-c017004b11c8.png)

After the update:
![oredict](https://user-images.githubusercontent.com/33242447/35190442-31f6d42c-fe62-11e7-98d9-1c123701d066.png)

Mods used to test:
ActuallyAdditions-1.12.2-r128.jar (only for the additional information thingie... ;))
jei_1.12.2-4.8.5.146.jar
platforms-1.12.0-1.4.3.jar
shetiphiancore-1.12.0-3.5.6.jar

Mods which are affected:
Immersive Engineering
Nuclear Craft
(and maybe much more which adds ingots with Oredict entries... :smile:)

Thanks for the mod, was hard to track this problem down... :smile:

Best regards
wamc

**Comment by whitestarx0312** [comment]
Ah so that's what was causing the recipe issues! I can confirm this is removing certain recipes from vanilla including iron buckets, hoppers, and really anything that those Oredict entries pertain to.

**Comment by ShetiPhian** [comment]
The changes to my paring code resulted in writes to the list returned from the OreDictionary; In the past doing that would throw an error as the list was unmodifiable, but as that is no longer the case I'm causing all ingots with a block to be wiped from the OreDictionary.

Fixed builds have been upload to Curse
1.12.0-1.4.3b -- https://minecraft.curseforge.com/projects/platforms/files/2522977
1.11.0-1.3.5b -- https://minecraft.curseforge.com/projects/platforms/files/2522976

**Comment by wamc2017** [comment]
Thanks for the update, everything works fine now. :+1:
