### ISSUE TITLE
Jan 20th Update removes several recipes from being craftable

### ISSUE THREAD

**Issue by Undeadbanana** [ShetiPhian/Localizations-and-Issues#141]
After realizing it wasn't a change by the FTB team, I spent several hours trying to pinpoint which mod removed the ability to make a vanilla flint and several other random recipes. Finally found the culprit, your mod. Not sure why but updating to the Jan 20th version removes the ability to craft Flint and steel. After narrowing it down, I updated every other mod and reloaded the FTB Revelations pack; 100% confirmed its this mod.

**Comment by Undeadbanana** [comment]
Also, it removes the ability to craft several other recipes from other mods; Iron casin from actually additions was one of the recipes I remembered/confirmed.

**Comment by wamc2017** [comment]
Hi, that should be the oredict problem, already mentioned here: https://github.com/ShetiPhian/Localizations-and-Issues/issues/140 :smile:

It breaks nearly all recipes which are using recipes with oredicted ingots...

**Comment by calloatti** [comment]
Came here to report this.

Vanilla recipes get removed, for example:

gold ingot to gold nuggets

**Comment by ShetiPhian** [comment]
The changes to my paring code resulted in writes to the list returned from the OreDictionary; In the past doing that would throw an error as the list was unmodifiable, but as that is no longer the case I'm causing all ingots with a block to be wiped from the OreDictionary.

Fixed builds have been upload to Curse
1.12.0-1.4.3b -- https://minecraft.curseforge.com/projects/platforms/files/2522977
1.11.0-1.3.5b -- https://minecraft.curseforge.com/projects/platforms/files/2522976

**Comment by Undeadbanana** [comment]
Issue fixed, thanks! I wasn't even mad after the hours I spent reloading FTB Revelations slowly going through each mod. I had just restarted a new world and it wasn't letting me build an iron pickaxe but since Tinkers is in the map, I thought the FTB team had made the pack harder... So glad they didn't 👍 Thanks again, @ShetiPhian 🥇

**Comment by abdullamu** [comment]
yes this was problem for me too but with applied energistics 2 recipes are removed i narrowed it down to this mod being the problems platforms.
