### ISSUE TITLE
Platforms Issues Here was some things I figured out

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [ShetiPhian/Localizations-and-Issues#142]
https://github.com/P3rf3ctXZer0/MC-1.12.2-TGGRS/issues/10

Removing platforms was all I had to do.

**Comment by ShetiPhian** [comment]
Update to 1.12.0-1.4.3**b**

The 1.4.3 build released Friday had a bug, discovered Sunday,
Monday morning it was archived on Curse, stops new downloads without breaking existing modpacks, and 1.4.3**b** was released.

My post in the previous reports: https://github.com/ShetiPhian/Localizations-and-Issues/issues/140, https://github.com/ShetiPhian/Localizations-and-Issues/issues/141

> The changes to my paring code accidentally resulted in writes to the list returned from the OreDictionary; In the past doing that would throw an error as the list was unmodifiable, but as that is no longer the case I'm causing all ingots with a block to be wiped from the OreDictionary.
> 
> Fixed builds have been upload to Curse
> 1.12.0-1.4.3b -- https://minecraft.curseforge.com/projects/platforms/files/2522977
> 1.11.0-1.3.5b -- https://minecraft.curseforge.com/projects/platforms/files/2522976
