### ISSUE TITLE
Compatibility with Craft Matter

### ISSUE THREAD

**Issue by IrresoluteArkia** [ShetiPhian/Localizations-and-Issues#147]
There was a crash reported with my mod, Craft Matter, and yours, Terraqueous. The log is here: https://pastebin.com/hwfasYCb

Since I can't see your code on github, I'm not entirely sure if it's something I need to fix or something you do. You can see my code here: https://github.com/IrresoluteArkia/craftmatter

**Comment by ShetiPhian** [comment]
Looks to be me,
I've missed the zero/null fluid handling, when it happens during crafting.

I'll post a test build once I'm done with the other reports.

**Comment by ShetiPhian** [comment]
Build uploaded to Curse
https://minecraft.curseforge.com/projects/terraqueous/files/2533248
