### ISSUE TITLE
[Request] Dimension whitelist/blacklist for worldgen features.

### ISSUE THREAD

**Issue by orbwoi** [ShetiPhian/Localizations-and-Issues#148]
I'm requesting a dimension whitelist for world gen features in Terraqueous.

... because clouds look really silly on the moon and fruit trees shouldn't be on alien planets. :)
(Using advanced rocketry worlds)

![2018-02-17_20 02 38](https://user-images.githubusercontent.com/4501752/36348130-c5c15616-141d-11e8-8cfc-2d5a0cd17703.png)

**Comment by ShetiPhian** [comment]
If this is 1.12, a blacklist was added a few versions ago.

"Generators will not generate in the dimensions on this list", "eg: overworld, the_nether, the_end", "regex supported"
Config > Generator > Dim_Blacklist > --generator--

Just add the name of the DimensionType to the list of the generator you want to disable.

**Comment by ShetiPhian** [comment]
In the newest build;

https://minecraft.curseforge.com/projects/terraqueous/files/2637253
- Added global dimension blacklist, adding a dimension to it will block it from all of my generators
- Added support for using dimension IDs in blacklists
- Improved details of the the dim_blacklist config menu, better explaining how to use it
