### ISSUE TITLE
GenPlants.gnerate passes wrong blockastate to soil resulting in crashes

### ISSUE THREAD

**Issue by mcenderdragon** [ShetiPhian/Localizations-and-Issues#149]
GenPlnats#generate line 48,` soil.canSustainPlant(Blocks.CACTUS.getDefaultState()...` but you have to pass the state of the soil.

**Comment by ShetiPhian** [comment]
Same bug found in a few other places.

This should fix the crash:
http://www.mediafire.com/file/qe6n3frugqr8orv/terraqueous-1.12.0-1.4.9-TESTER2.jar

**Comment by ShetiPhian** [comment]
Build uploaded to Curse
https://minecraft.curseforge.com/projects/terraqueous/files/2533248

If the issue still exists let me know.
