### ISSUE TITLE
Crash when placing Dried Grass

### ISSUE THREAD

**Issue by instinxx** [ShetiPhian/Localizations-and-Issues#150]
When rt clicking on the ground with grass in hand to create drying grass, the client crashes with this error-

The game crashed whilst unexpected error
The game crashed whilst unexpected error
Error: java.lang.IllegalArgumentException: Cannot add types to unregistered biome net.minecraft.world.biome.BiomePlains@9499643

Full Log - https://pastebin.com/Mh07gC62

**Comment by ShetiPhian** [comment]
Your pack is seriously broken.

But to focus on a single issue, something is causing null and missing biomes, this is causing the crash you have.

**Comment by instinxx** [comment]
Are you familiar with OTG? - https://minecraft.curseforge.com/projects/open-terrain-generator ?

That is the current world generator. Does your mod expect vanilla biomes?

I suspect that it may be a conflict between the two and / or possibly between Forge .2607 and .2618. Note that this issue did not occur with .2607.

**Comment by ShetiPhian** [comment]
I'm using the Biome Dictionary provided by Forge, the crash happens when Forge tries to generate the defaults and errors due to missing/null biomes.

Until OTG updates for the latest Forge changes you'll need to stick with 2607
