### ISSUE TITLE
[Incompatibility/Enhancement] [Terraqueous] Mod glass blocks, and vanilla panes, drop no shards

### ISSUE THREAD

**Issue by NotAVerb** [ShetiPhian/Localizations-and-Issues#151]
Glass blocks from Chisel, plain and stained, do not drop glass shards upon being broken.
The glass door and trapdoor from Inspirations do not drop shards either.

Also, vanilla glass panes don't seem to drop shards, but that may be intentional. Otherwise maybe they should drop 0-1 shards?

Terraqueous V1.4.9

**Comment by ShetiPhian** [comment]
Rather then directly checking for glass blocks and panes, this build checks the OreDictionary.
As long as a mod item is registered as "blockGlass" or "paneGlass" it should drop glass shards (shards still only drop if nothing would have dropped before)

http://www.mediafire.com/file/1k84wj8gjef408v/terraqueous-1.12.0-1.4.10-TESTER.jar

**Comment by NotAVerb** [comment]
The Chisel glasses drops shards as expected.
The inspirations blocks still drop nothing, but that's because they're not glass blocks.

There is some possibly undesirable behavior from the shards dropping from non sand derived glasses like Aether quicksoil glass, and NetherEX soul glass, and Betweenlands silt glass. The Natura nether glasses drop nothing.

**Comment by ShetiPhian** [comment]
It should be fine to leave as is.

With those registered to the dictionary as glass you can use them in as glass in recipes, also a unifier mod will'll be able to change them into normal glass and vice-versa.

**Comment by ShetiPhian** [comment]
New version uploaded to Curse
https://minecraft.curseforge.com/projects/terraqueous/files/2537386
