### ISSUE TITLE
[1.12.2] [Terraqueous] Possible issue with the doodads

### ISSUE THREAD

**Issue by NotAVerb** [ShetiPhian/Localizations-and-Issues#152]
It seems that whenever I load a world, the first doodad I break drops nothing. The second doodad broken gives items as normal.

V1.4.9

**Comment by ShetiPhian** [comment]
So it does...
The first one broken generates the drop lists, turns out I only built the list and never passed it to the drop code.

Fix will be in the next release.

**Comment by ShetiPhian** [comment]
New version uploaded to Curse
https://minecraft.curseforge.com/projects/terraqueous/files/2537386
