### ISSUE TITLE
[Terraquaeous] Shooting an arrow at an end crystal crashes the game

### ISSUE THREAD

**Issue by NotAVerb** [ShetiPhian/Localizations-and-Issues#155]
Hitting the crystals with a melee attack does not crash the game.

https://gist.github.com/NotAVerb/01b42e9df6aed149d7cbe830da116013

This might be related to the 1.4.10 test build. I'm off to test without it.

**Comment by NotAVerb** [comment]
A test with just Terraquaeous 1.4.9 didn't cause a crash

I also just tested 1.4.10 by itself. Yeah, its broken.

**Comment by ShetiPhian** [comment]
Fixed, just added a check for empty item stacks.

**Comment by NotAVerb** [comment]
The crystals seem fine now.
The error log is clean too.
