### ISSUE TITLE
[Request] [Terraqueous] Crafttweaker support for the Ender Table

### ISSUE THREAD

**Issue by NotAVerb** [ShetiPhian/Localizations-and-Issues#156]
What it says on the tin.
Seems like it could be a cool crafting station.

**Comment by ShetiPhian** [comment]
I've looked things over, it appears doable.
I'll add the StormForge at the same time.

**Comment by NotAVerb** [comment]
Fantastic.
Also it would be nice if the ender table received an icon for its JEI crafting tab. At the moment it's just EN, and looks out of place compared to everything else.

**Comment by ShetiPhian** [comment]
Still haven't gotten the chance to fully code and test CraftTweaker support, but that JEI fix is in.

**Comment by ShetiPhian** [comment]
Still have testing to do, but here is the current test build:
http://www.mediafire.com/file/fzdsqv9w3afvadx/terraqueous-1.12.0-1.4.11-TESTER.jar

---
**EnderTable**
`mods.terraqueous.EnderTable`

Single choice recipe methods:
```javascript
void addRecipe(IItemStack result, IIngredient inputItem, int experienceCost, float enchantPower, String tooltip, @Optional IIngredient inputMaterial)

void addRecipe(IItemStack result, IIngredient inputItem, int experienceCost, float enchantPower, String tooltip, boolean obfuscateTooltip, @Optional IIngredient inputMaterial)

/* Example
mods.terraqueous.EnderTable.addRecipe(<minecraft:book>, <minecraft:paper>, 2, 1, "paper to book");
*/
```


1-3 choice recipe methods:
```javascript
EnderTableButtonOption buttonOption(IItemStack result, int experienceCost, float enchantPower, String tooltip, @Optional IIngredient inputMaterial)

EnderTableButtonOption buttonOption(IItemStack result, int experienceCost, float enchantPower, String tooltip, boolean obfuscateTooltip, @Optional IIngredient inputMaterial)

void addRecipe(IIngredient inputItem, EnderTableButtonOption first, @Optional EnderTableButtonOption second, @Optional EnderTableButtonOption third)

/* Example:
var first = mods.terraqueous.EnderTable.buttonOption(<minecraft:emerald>, 2, 1, "stick to emerald");
var second = mods.terraqueous.EnderTable.buttonOption(<minecraft:dirt>, 2, 1, "stick to dirt");
var third = mods.terraqueous.EnderTable.buttonOption(<minecraft:coal>, 2, 1, "stick to coal");
mods.terraqueous.EnderTable.addRecipe(<minecraft:stick>, first, second, third);
*/
```

---
**StormForge**
`mods.terraqueous.StormForge`

```javascript
void addConversion(IItemStack result, IIngredient input, int ticksToComplete, boolean lightningStrikeOnComplete)

// If provided altResult will be used if the StormForge is struck by lightning while processing this item
void addConversion(IItemStack result, IIngredient input, int ticksToComplete, @Optional IItemStack altResult)

/* Example
mods.terraqueous.StormForge.addConversion(<minecraft:diamond>, <minecraft:coal_block>, 200, true);
*/
```

**Comment by NotAVerb** [comment]
I copied your examples into a script file.
The recipes for the Ender Table show up in JEI, but neither are functional.
The stormforge turns coal into diamonds perfectly. Nice ring of fire by the way.

**Comment by ShetiPhian** [comment]
I forgot to look in JEI
The recipes require at least one bookshelf before they show up.
Forge declares a bookshelf as giving 1 EnchantPower, but mod items can be different. (eg. BiblioCraft bookcases change in value depending on how may books are in it.)

I should add the EnchantPower requirement to JEI, and while I'm at it make it easier to understand.

**Comment by ShetiPhian** [comment]
New build uploaded to Curse
https://minecraft.curseforge.com/projects/terraqueous/files/2540004
