### ISSUE TITLE
Terraqueous conflicts with Wizardry

### ISSUE THREAD

**Issue by faeldray** [ShetiPhian/Localizations-and-Issues#157]
I had a game crash while exploring a jungle, here's the report: https://pastebin.com/bf4nnKcD

I initially reported it to the Wizardry folks (https://github.com/TeamWizardry/Wizardry/issues/111) but they directed me here.

**Comment by pau101** [comment]
To resolve this, @ShetiPhian, I suggest changing the current code using a `null` as the `RayTraceResult` parameter to
```java
new RayTraceResult(RayTraceResult.Type.BLOCK, new Vec3d(event.getPos()), EnumFacing.DOWN, event.getPos())
```

**Comment by ShetiPhian** [comment]
@faeldray 
Temporary fix is to disable glass shard drops (configs under tweaks)

@pau101 
In the past I thought the same thing, but had to add null checks to getPickBlock after to getting crash reports.
At the time I figured the other mod made an error but the other day I noticed IntelliJ marks it Nullable
![getPickBlock](https://lh3.googleusercontent.com/YZqDb1G27_mcT9IT-rzSmdfYr97vEFaCP8sFHGv7anvfMD7bnYPabIyPn8Y0Sa2kPoNHl--NKQMBe7lQAa1MPDVf_IVaYLpygm2cq_Sek81djgCUip9Ki_GFBBBzKHRjL2cUL9GQse8lyCTUecfGAk-J6QVrFnRrV9VR2KTtFAjcpeKssto3aP8d9mjlj41UKbxv_p9301eyw8d5FFC5cl3OhcH715cfnbWgpV0VEoKg3wWurHCrL9STMiF9ldLDGx1ebyIfXamVEDpnpAH2W8AorPb6abEp2W-3hM1F1jxeGbuPeeFECZMMM1ldHc5ER9iM51gE8wLyypE34DY7uJloQ95TVg2O4OycGBxbojUcVblL_wUVevqyiBVXU2Ji5XR_j2KhlQbXQsHNW4o2AACEmphtz9fARpSRlKACcu4OWJ0NK-GMgtjP_WxsetQeB_x2_LR2OGMvU9uJnVNnJuZUVbCeY3PewtEzCYB-aZQo_Y9p7WohFxnDZFOuvzorL8lwICJMrraiJZwIb2epENX2BLjFMJwUkyrQu0ExqCjXfZ232y5r-Sr2auJfE294LRmc8z5tSTRywgxwSYp2b5j91e3FuwNLHBO_YVo=w822-h96-no)

I'll change the code so I'm not part of the confusion/problem, but I'd highly suggest you add a null check as there are other mods out there passing null.

**Comment by pau101** [comment]
Inferred annotations are not reliable. I can only guess IntelliJ sees the base Block implementation of that method not referencing target or player. However, the minecraft packages are marked `@ParametersAreNonnullByDefault` from MCP. But mainly this is a Forge added method, so if it is not marked nullable it surely isn't nullable.

The code already has a null check, that is what threw the exception. The class Wizardy was using here is one from LibrarianLib which is written in Kotlin, whose compiler adds nullity preconditions.

**Comment by faeldray** [comment]
@ShetiPhian Thanks, changing that config has allowed me to load my save without it crashing now.

**Comment by ShetiPhian** [comment]
So any variable that isn't marked NonNull your forcing a crash if its null, regardless if your using it or not?
Your asking for a lot of incompatibilities, Forge using annotations is rather new, not everything is marked.
A great example here is getPickBlock's player variable. That thing has been Nullable since Forge added the method. Everyone just checks it before trying to use it, and has a fall back if its null.

**Comment by ShetiPhian** [comment]
*sigh* this conversation is going nowhere

I couldn't care less if player is officially flagged one way or another, at most it just mean I could remove my null checks.

If you don't want a heads up on possible quirks/issues from the pre-annotation time, so be it.
I'm done wasting time here.

**Comment by ShetiPhian** [comment]
@faeldray 
New build uploaded to Curse
https://minecraft.curseforge.com/projects/terraqueous/files/2540004
