### ISSUE TITLE
[Question] [Terraqueous] Are the wood variants using NBT data for their coloring?

### ISSUE THREAD

**Issue by NotAVerb** [ShetiPhian/Localizations-and-Issues#159]
There's an issue with Terraqueous wood Inspirations-bookshelves being colored wrong.
https://github.com/KnightMiner/Inspirations/issues/28

**Comment by KnightMiner** [comment]
Hmm, odd that its not working if you do not use NBT or tinting for textures. The way I get the textures uses both the item method `getMetadata()` and the block method `getStateFromMeta()`, I assume you properly implement both in your wood slabs?

**Comment by ShetiPhian** [comment]
I thought the question was with my planks.

Using the slabs would be a pain, as they are in a highly condensed block that uses a tile entity. (this mess was done to save as many block ids as possible, and has caused many headaches)

The easiest way to use them would probably be;
Take the slab ItemStack meta, subtract 50, then get the texture from the planks with the result.
[0-9=door, 10-19=trapdoor, 20-29= gate, 30-39=fence, 40-49=stairs, 50-59=slab]

Might want to leave it though, as in 1.13 I'll be following Mojang and will be flattening everything into its own block/item.

I'm rather excited for 1.13, sure I basically have to re-code but finally no more block id limits.
allows for much cleaner code, far more compatible/mod friendly, and I'm free form the corners I coded myself into (eg. I couldn't add another tree if I wanted to, without creating a larger mess)

**Comment by KnightMiner** [comment]
Yeah, I was hoping to avoid needing to special case any mods there. Might just have to leave those woods as unsupported until 1.13.

**Comment by ShetiPhian** [comment]
I'll close this for now and revisit in 1.13
