### ISSUE TITLE
[Terraqueous] Crashing with Twilight Forest and Extra Utils 2 quarry

### ISSUE THREAD

**Issue by Aphyxia** [ShetiPhian/Localizations-and-Issues#161]
Using Twilight Forest mod and mining Extra Utils 2 quarry after latest Terraqueous update has sent my server to a long or infinite series of crashes. At least that's what I gather from the crash log.
This didn't happen before the latest update of Terraqueous and the other two mods haven't been updated recently so I'm inclined to believe it is the fault of Terraqueous.
Tell me if it is not so and I will post the crash to the githubs of the other mods.

Pastebin with crash log: https://pastebin.com/pUSXvpdy

**Comment by ShetiPhian** [comment]
Short term fix: disable glass shard drops (config tweaks)
This is fixed internally, just finishing up some other stuff before updating the version on Curse.

**Comment by ShetiPhian** [comment]
New build uploaded to Curse
https://minecraft.curseforge.com/projects/terraqueous/files/2540004
