### ISSUE TITLE
[Terraqueous] Graphical xray glitch involving the big thing

### ISSUE THREAD

**Issue by NotAVerb** [ShetiPhian/Localizations-and-Issues#162]
This occurs when the top corner slopes are placed up against another solid block.
![2018-03-09_15 09 29](https://user-images.githubusercontent.com/30223331/37227744-397ab0ee-23d6-11e8-9de3-25504e140c0f.png)
The other slopes all seem to be fine.

V 1.4.11 T1

**Comment by ShetiPhian** [comment]
Fixed; next build will have the correction.
