### ISSUE TITLE
crashing problem after like 2-5 minutes

### ISSUE THREAD

**Issue by lwadam** [ShetiPhian/Localizations-and-Issues#163]
yo!

i have a problem with minecraft and it seems it might be with this core. 
i am new to this thing but i would copy the message error here in hopes of someone enlightening me.
thanks and cheers!

adam

"---- Minecraft Crash Report ----

WARNING: coremods are present:
  ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.6.jar)
Contact their authors BEFORE contacting forge

// Everything's going to plan. No, really, that was supposed to happen.

Time: 3/10/18 7:12 AM
Description: Tesselating block model

java.lang.OutOfMemoryError: Tesselating block model
	at sun.misc.Unsafe.allocateMemory(Native Method)
	at java.nio.DirectByteBuffer.<init>(Unknown Source)
	at java.nio.ByteBuffer.allocateDirect(Unknown Source)
	at net.minecraft.client.renderer.GLAllocation.func_74524_c(SourceFile:41)
	at net.minecraft.client.renderer.BufferBuilder.func_181670_b(BufferBuilder.java:55)
	at net.minecraft.client.renderer.BufferBuilder.func_178981_a(BufferBuilder.java:420)
	at net.minecraftforge.client.model.pipeline.VertexBufferConsumer.put(VertexBufferConsumer.java:67)
	at net.minecraftforge.client.model.pipeline.VertexLighterFlat.processQuad(VertexLighterFlat.java:213)
	at net.minecraftforge.client.model.pipeline.QuadGatheringTransformer.put(QuadGatheringTransformer.java:63)
	at net.minecraftforge.client.model.pipeline.LightUtil.putBakedQuad(LightUtil.java:113)
	at net.minecraft.client.renderer.block.model.BakedQuad.pipe(BakedQuad.java:66)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.render(ForgeBlockModelRenderer.java:120)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187497_c(ForgeBlockModelRenderer.java:64)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:47)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:38)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:80)
	at codechicken.lib.render.block.CCBlockRendererDispatcher.func_175018_a(CCBlockRendererDispatcher.java:64)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:200)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:100)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:43)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at sun.misc.Unsafe.allocateMemory(Native Method)
	at java.nio.DirectByteBuffer.<init>(Unknown Source)
	at java.nio.ByteBuffer.allocateDirect(Unknown Source)
	at net.minecraft.client.renderer.GLAllocation.func_74524_c(SourceFile:41)
	at net.minecraft.client.renderer.BufferBuilder.func_181670_b(BufferBuilder.java:55)
	at net.minecraft.client.renderer.BufferBuilder.func_178981_a(BufferBuilder.java:420)
	at net.minecraftforge.client.model.pipeline.VertexBufferConsumer.put(VertexBufferConsumer.java:67)
	at net.minecraftforge.client.model.pipeline.VertexLighterFlat.processQuad(VertexLighterFlat.java:213)
	at net.minecraftforge.client.model.pipeline.QuadGatheringTransformer.put(QuadGatheringTransformer.java:63)
	at net.minecraftforge.client.model.pipeline.LightUtil.putBakedQuad(LightUtil.java:113)
	at net.minecraft.client.renderer.block.model.BakedQuad.pipe(BakedQuad.java:66)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.render(ForgeBlockModelRenderer.java:120)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187497_c(ForgeBlockModelRenderer.java:64)

-- Block model being tesselated --
Details:
	Block: terraqueous:pergola[variant=top_none]
	Block location: World: (751,82,91), Chunk: (at 15,5,11 in 46,5; contains blocks 736,0,80 to 751,255,95), Region: (1,0; contains chunks 32,0 to 63,31, blocks 512,0,0 to 1023,255,511)
	Using AO: false
Stacktrace:
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:47)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:38)

-- Block being tesselated --
Details:
	Block type: ID #267 (tile.terraqueous.pergola // shetiphian.terraqueous.common.block.BlockPergola)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (751,82,91), Chunk: (at 15,5,11 in 46,5; contains blocks 736,0,80 to 751,255,95), Region: (1,0; contains chunks 32,0 to 63,31, blocks 512,0,0 to 1023,255,511)
Stacktrace:
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:80)
	at codechicken.lib.render.block.CCBlockRendererDispatcher.func_175018_a(CCBlockRendererDispatcher.java:64)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Adamka'/1651, l='MpServer', x=721.70, y=70.00, z=112.70]]
	Chunk stats: MultiplayerChunkCache: 255, 255
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-32,64,244), Chunk: (at 0,4,4 in -2,15; contains blocks -32,0,240 to -17,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 270737 game time, 270737 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 106 total; [EntityItem['item.item.terraqueous.multifood.coconut'/1280, l='MpServer', x=-42.14, y=63.00, z=263.18], MoCEntityBass['Bass'/2816, l='MpServer', x=665.64, y=59.42, z=160.53], MoCEntityBass['Bass'/2817, l='MpServer', x=664.15, y=60.94, z=173.94], MoCEntityBass['Bass'/2819, l='MpServer', x=672.11, y=59.07, z=168.88], EntityCreeper['Creeper'/3333, l='MpServer', x=659.50, y=20.00, z=171.81], EntityZombie['Zombie'/4103, l='MpServer', x=689.79, y=32.00, z=175.50], EntitySkeleton['Skeleton'/4364, l='MpServer', x=692.50, y=28.00, z=173.50], EntityItem['item.item.string'/4365, l='MpServer', x=686.72, y=29.00, z=155.38], EntityZombieVillager['Zombie Villager'/3854, l='MpServer', x=666.50, y=33.00, z=97.50], MoCEntityCricket['Cricket'/4886, l='MpServer', x=666.03, y=69.00, z=53.88], MoCEntityCricket['Cricket'/4887, l='MpServer', x=667.50, y=69.00, z=53.50], MoCEntityCricket['Cricket'/4888, l='MpServer', x=664.50, y=69.00, z=50.50], EntitySkeleton['Skeleton'/2847, l='MpServer', x=700.50, y=49.00, z=96.91], MoCEntityBoar['Boar'/2848, l='MpServer', x=692.62, y=66.00, z=105.09], MoCEntityBoar['Boar'/2849, l='MpServer', x=697.88, y=68.00, z=83.64], EntityItem['item.item.string'/2850, l='MpServer', x=697.71, y=32.00, z=109.60], MoCEntityBoar['Boar'/2851, l='MpServer', x=687.36, y=65.00, z=96.40], MoCEntityBoar['Boar'/2852, l='MpServer', x=700.27, y=68.00, z=101.62], MoCEntityAngelFish['AngelFish'/2854, l='MpServer', x=673.88, y=61.02, z=177.12], EntityItem['item.item.string'/2860, l='MpServer', x=674.35, y=63.00, z=149.13], EntitySpider['Spider'/4396, l='MpServer', x=645.30, y=61.10, z=87.99], MoCEntityAngelFish['AngelFish'/2861, l='MpServer', x=682.47, y=60.99, z=167.23], MoCEntityAngelFish['AngelFish'/2862, l='MpServer', x=672.50, y=61.33, z=170.50], EntityZombie['Zombie'/3121, l='MpServer', x=651.70, y=55.00, z=86.33], EntityCreeper['Creeper'/4672, l='MpServer', x=701.50, y=32.00, z=108.50], EntityCreeper['Creeper'/4161, l='MpServer', x=650.50, y=24.00, z=75.50], EntityCreeper['Creeper'/4162, l='MpServer', x=649.48, y=24.00, z=72.82], EntityWitch['Witch'/4678, l='MpServer', x=661.50, y=49.00, z=91.50], EntitySkeleton['Skeleton'/2892, l='MpServer', x=699.30, y=45.03, z=81.70], EntitySkeleton['Skeleton'/2893, l='MpServer', x=704.21, y=50.00, z=96.49], EntitySpider['Spider'/2894, l='MpServer', x=704.94, y=65.00, z=43.20], EntityCow['Cow'/2899, l='MpServer', x=707.45, y=79.00, z=149.97], EntityCow['Cow'/2900, l='MpServer', x=708.50, y=80.00, z=147.50], EntityCow['Cow'/2901, l='MpServer', x=709.50, y=80.00, z=147.50], EntityCow['Cow'/2902, l='MpServer', x=708.55, y=78.00, z=150.57], MoCEntityJellyFish['JellyFish'/2906, l='MpServer', x=714.70, y=61.96, z=107.49], EntitySkeleton['Skeleton'/4442, l='MpServer', x=653.50, y=33.00, z=92.50], MoCEntityJellyFish['JellyFish'/2907, l='MpServer', x=714.56, y=62.00, z=116.21], EntitySkeleton['Skeleton'/4443, l='MpServer', x=652.50, y=33.00, z=93.50], EntityZombie['Zombie'/4444, l='MpServer', x=655.50, y=33.00, z=93.50], EntityZombieVillager['Zombie Villager'/4703, l='MpServer', x=771.27, y=68.00, z=45.47], EntityCreeper['Creeper'/3693, l='MpServer', x=739.50, y=28.00, z=33.50], MoCEntityBird['Bird'/4209, l='MpServer', x=792.21, y=71.86, z=31.51], EntityCreeper['Creeper'/3187, l='MpServer', x=652.18, y=58.00, z=68.54], EntitySkeleton['Skeleton'/4733, l='MpServer', x=696.50, y=31.00, z=171.50], EntityVillager['Villager'/3978, l='MpServer', x=788.65, y=69.00, z=55.51], EntityVillager['Villager'/3980, l='MpServer', x=788.50, y=76.00, z=65.44], EntitySheep['Sheep'/3982, l='MpServer', x=790.45, y=69.00, z=43.20], EntitySheep['Sheep'/3983, l='MpServer', x=788.50, y=74.00, z=39.50], EntitySheep['Sheep'/3984, l='MpServer', x=790.52, y=69.00, z=42.13], MoCEntityRaccoon['Raccoon'/3218, l='MpServer', x=738.50, y=95.00, z=187.50], MoCEntityBird['Bird'/3221, l='MpServer', x=741.80, y=73.00, z=54.80], EntityVillager['Villager'/3224, l='MpServer', x=739.50, y=79.00, z=98.50], EntityVillager['Villager'/3225, l='MpServer', x=747.50, y=90.00, z=98.50], EntityVillager['Villager'/3226, l='MpServer', x=747.00, y=89.00, z=112.58], EntityVillager['Villager'/3227, l='MpServer', x=740.52, y=91.00, z=87.34], EntityVillager['Villager'/3228, l='MpServer', x=738.18, y=90.00, z=87.54], EntityItem['item.item.clay'/4514, l='MpServer', x=711.13, y=61.00, z=95.88], EntityCow['Cow'/3492, l='MpServer', x=770.67, y=79.00, z=80.26], EntityCow['Cow'/3493, l='MpServer', x=774.50, y=74.00, z=75.03], EntityCow['Cow'/3494, l='MpServer', x=774.50, y=75.00, z=76.55], EntityCow['Cow'/3495, l='MpServer', x=772.69, y=79.00, z=79.47], EntityVillager['Villager'/3496, l='MpServer', x=764.45, y=80.94, z=92.51], MoCEntitySnake['Snake'/3497, l='MpServer', x=767.04, y=80.00, z=166.01], EntityPlayerSP['Adamka'/1651, l='MpServer', x=721.70, y=70.00, z=112.70], MoCEntitySnake['Snake'/3498, l='MpServer', x=775.00, y=80.00, z=158.08], EntityVillager['Villager'/3246, l='MpServer', x=761.50, y=81.00, z=112.50], EntityVillager['Villager'/3247, l='MpServer', x=767.50, y=82.00, z=119.50], EntityVillager['Villager'/3249, l='MpServer', x=752.70, y=84.00, z=119.59], EntityVillager['Villager'/3250, l='MpServer', x=746.49, y=85.00, z=122.43], MoCEntityAnt['Ant'/3765, l='MpServer', x=716.31, y=80.00, z=141.01], MoCEntityAnt['Ant'/3766, l='MpServer', x=713.50, y=80.00, z=150.50], MoCEntityAnt['Ant'/3767, l='MpServer', x=708.92, y=80.00, z=145.51], EntitySkeleton['Skeleton'/3514, l='MpServer', x=688.50, y=32.00, z=175.50], EntitySkeleton['Skeleton'/4285, l='MpServer', x=656.50, y=39.00, z=58.50], EntityCreeper['Creeper'/3007, l='MpServer', x=658.50, y=41.00, z=35.50], EntitySkeleton['Skeleton'/4287, l='MpServer', x=713.53, y=47.00, z=91.70], EntityCreeper['Creeper'/3008, l='MpServer', x=660.50, y=41.00, z=34.50], MoCEntityButterfly['ButterFly'/4292, l='MpServer', x=791.47, y=67.00, z=45.09], MoCEntityButterfly['ButterFly'/4293, l='MpServer', x=755.27, y=83.00, z=43.07], MoCEntityAnt['Ant'/4294, l='MpServer', x=779.49, y=80.00, z=51.51], MoCEntityGreenOgre['GreenOgre'/4045, l='MpServer', x=658.19, y=34.00, z=90.99], EntityZombie['Zombie'/4813, l='MpServer', x=695.50, y=32.00, z=98.50], EntityChicken['Chicken'/4047, l='MpServer', x=796.50, y=68.00, z=83.06], EntityChicken['Chicken'/4049, l='MpServer', x=792.48, y=65.94, z=77.53], EntityChicken['Chicken'/4050, l='MpServer', x=796.50, y=68.00, z=84.18], EntityVillager['Villager'/3539, l='MpServer', x=776.50, y=77.00, z=103.50], EntityChicken['Chicken'/4051, l='MpServer', x=796.50, y=68.00, z=83.76], EntitySheep['Sheep'/2774, l='MpServer', x=670.28, y=68.00, z=50.46], EntitySheep['Sheep'/2775, l='MpServer', x=653.83, y=68.00, z=52.80], EntitySheep['Sheep'/2776, l='MpServer', x=661.28, y=69.00, z=54.57], EntitySheep['Sheep'/2777, l='MpServer', x=674.76, y=65.00, z=53.27], MoCEntityElephant['Elephant'/2779, l='MpServer', x=661.93, y=66.00, z=85.98], MoCEntityBass['Bass'/2785, l='MpServer', x=645.50, y=61.13, z=169.50], EntitySheep['Sheep'/2786, l='MpServer', x=677.19, y=65.00, z=80.85], EntityHorse['Horse'/2787, l='MpServer', x=651.65, y=68.00, z=104.13], EntityHorse['Horse'/2788, l='MpServer', x=652.86, y=68.00, z=104.13], EntityEnderman['Enderman'/3556, l='MpServer', x=733.50, y=70.00, z=62.50], EntityHorse['Horse'/2789, l='MpServer', x=651.62, y=68.00, z=105.30], EntitySheep['Sheep'/2790, l='MpServer', x=661.85, y=66.00, z=96.51], EntitySheep['Sheep'/2791, l='MpServer', x=655.66, y=66.00, z=95.45], EntitySheep['Sheep'/2792, l='MpServer', x=675.19, y=66.00, z=93.84], MoCEntityAnt['Ant'/4587, l='MpServer', x=645.50, y=66.00, z=62.50], MoCEntityBass['Bass'/2812, l='MpServer', x=667.70, y=60.00, z=148.30], MoCEntityFox['Fox'/2813, l='MpServer', x=671.49, y=64.00, z=82.72], MoCEntityMantaRay['MantaRay'/2815, l='MpServer', x=661.51, y=59.64, z=164.36]]
	Retry entities: 81 total; [EntityItem['item.item.terraqueous.multifood.coconut'/1280, l='MpServer', x=-42.14, y=63.00, z=263.18], EntityCoconut['entity.coconut.name'/1282, l='MpServer', x=-37.85, y=63.00, z=262.39], EntityHorse['Horse'/1283, l='MpServer', x=-34.14, y=68.00, z=296.44], EntityCow['Cow'/1284, l='MpServer', x=-37.41, y=65.00, z=303.15], EntityItem['item.item.string'/2317, l='MpServer', x=5.06, y=17.00, z=252.73], MoCEntityBass['Bass'/1421, l='MpServer', x=49.81, y=59.07, z=276.22], EntityZombie['Zombie'/1939, l='MpServer', x=-10.50, y=35.00, z=288.50], MoCEntityCrab['Crab'/1302, l='MpServer', x=-19.50, y=63.00, z=183.55], MoCEntityMaggot['Maggot'/1303, l='MpServer', x=-18.09, y=65.00, z=194.22], EntityHorse['Horse'/1304, l='MpServer', x=-29.90, y=65.00, z=205.05], EntitySkeleton['Skeleton'/1305, l='MpServer', x=-27.50, y=45.00, z=219.53], EntityCreeper['Creeper'/2074, l='MpServer', x=-76.50, y=20.00, z=233.50], EntitySpider['Spider'/1306, l='MpServer', x=-33.30, y=47.10, z=217.70], EntityZombie['Zombie'/1690, l='MpServer', x=-18.50, y=31.00, z=256.50], EntitySkeleton['Skeleton'/2202, l='MpServer', x=-14.49, y=40.00, z=280.68], MoCEntitySnail['Snail'/1307, l='MpServer', x=-20.88, y=65.00, z=212.60], MoCEntitySnail['Snail'/1308, l='MpServer', x=-29.12, y=65.00, z=210.11], EntityHorse['Horse'/1309, l='MpServer', x=-25.90, y=66.00, z=224.02], MoCEntityFireOgre['FireOgre'/1310, l='MpServer', x=-21.50, y=19.00, z=287.50], EntityHorse['Horse'/1311, l='MpServer', x=-22.18, y=68.00, z=297.37], EntityCreeper['Creeper'/2207, l='MpServer', x=3.50, y=16.00, z=179.50], MoCEntityAnt['Ant'/1312, l='MpServer', x=-29.24, y=67.00, z=302.96], EntityCreeper['Creeper'/2210, l='MpServer', x=38.50, y=40.00, z=302.50], EntityItem['item.item.terraqueous.multifood.coconut'/2212, l='MpServer', x=-35.13, y=63.00, z=265.93], EntityCreeper['Creeper'/2085, l='MpServer', x=-51.50, y=33.00, z=205.50], EntityItem['item.item.string'/1970, l='MpServer', x=-33.27, y=35.00, z=245.88], EntityCreeper['Creeper'/2228, l='MpServer', x=-37.21, y=30.00, z=244.48], EntityZombie['Zombie'/2238, l='MpServer', x=-24.50, y=25.00, z=250.50], MoCEntityRat['Rat'/2241, l='MpServer', x=-1.98, y=26.00, z=222.25], EntityItem['item.item.string'/1988, l='MpServer', x=-16.88, y=11.00, z=291.72], EntityItem['item.item.arrow'/1990, l='MpServer', x=-9.80, y=68.00, z=267.13], EntityItem['item.item.bone'/1991, l='MpServer', x=-8.93, y=68.00, z=268.04], EntityHorse['Horse'/1352, l='MpServer', x=-11.00, y=65.00, z=209.02], EntityItem['item.item.string'/1354, l='MpServer', x=-5.13, y=14.00, z=276.88], MoCEntityMouse['Mouse'/1355, l='MpServer', x=-13.50, y=65.00, z=284.76], EntityHorse['Horse'/1356, l='MpServer', x=-10.02, y=67.00, z=277.13], MoCEntityMouse['Mouse'/1357, l='MpServer', x=-7.55, y=64.00, z=279.60], MoCEntityAnt['Ant'/1358, l='MpServer', x=-4.46, y=64.00, z=305.02], EntitySkeleton['Skeleton'/1232, l='MpServer', x=-99.51, y=29.00, z=270.67], MoCEntitySalmon['Salmon'/1234, l='MpServer', x=-100.60, y=60.99, z=299.53], EntityCreeper['Creeper'/2263, l='MpServer', x=-5.50, y=18.00, z=254.50], MoCEntityClownFish['ClownFish'/1240, l='MpServer', x=-80.06, y=61.18, z=161.93], MoCEntityBlackBear['BlackBear'/1368, l='MpServer', x=12.14, y=63.00, z=221.96], MoCEntityBass['Bass'/1241, l='MpServer', x=-91.66, y=60.90, z=167.08], MoCEntityGrizzlyBear['GrizzlyBear'/1369, l='MpServer', x=15.42, y=68.00, z=214.71], MoCEntityHippoTang['HippoTang'/1242, l='MpServer', x=-90.06, y=61.51, z=242.19], MoCEntityHorseMob['HorseMob'/2010, l='MpServer', x=2.28, y=28.35, z=224.33], EntitySheep['Sheep'/1370, l='MpServer', x=6.55, y=63.27, z=235.59], MoCEntityHippoTang['HippoTang'/1243, l='MpServer', x=-103.37, y=61.95, z=286.38], EntityCoconut['entity.coconut.name'/2268, l='MpServer', x=-37.70, y=75.88, z=265.60], EntityCreeper['Creeper'/2012, l='MpServer', x=-17.50, y=27.00, z=302.50], EntityZombie['Zombie'/1373, l='MpServer', x=9.50, y=28.00, z=305.50], EntitySpider['Spider'/2142, l='MpServer', x=-7.03, y=26.00, z=231.99], MoCEntityClownFish['ClownFish'/1250, l='MpServer', x=-65.42, y=62.45, z=175.60], MoCEntityMantaRay['MantaRay'/1251, l='MpServer', x=-66.92, y=59.01, z=203.72], EntityCow['Cow'/1379, l='MpServer', x=22.62, y=64.00, z=188.82], MoCEntityHippoTang['HippoTang'/1252, l='MpServer', x=-68.84, y=61.68, z=238.71], MoCEntityGrizzlyBear['GrizzlyBear'/1380, l='MpServer', x=25.09, y=65.00, z=203.79], MoCEntityKitty['Kitty'/1253, l='MpServer', x=-65.71, y=62.91, z=294.63], EntityCow['Cow'/1382, l='MpServer', x=18.52, y=69.00, z=219.80], MoCEntityBlackBear['BlackBear'/1383, l='MpServer', x=26.99, y=65.00, z=211.15], MoCEntityGrizzlyBear['GrizzlyBear'/1384, l='MpServer', x=26.51, y=67.00, z=214.38], MoCEntityMantaRay['MantaRay'/1258, l='MpServer', x=-53.96, y=59.75, z=162.33], MoCEntityMantaRay['MantaRay'/1259, l='MpServer', x=-57.94, y=58.80, z=168.68], MoCEntityKitty['Kitty'/1260, l='MpServer', x=-61.47, y=62.90, z=304.10], EntityCoconut['entity.coconut.name'/1388, l='MpServer', x=27.85, y=63.00, z=328.60], EntityCow['Cow'/1261, l='MpServer', x=-50.49, y=64.00, z=292.78], EntityCoconut['entity.coconut.name'/1389, l='MpServer', x=27.50, y=72.63, z=330.30], MoCEntityMaggot['Maggot'/1262, l='MpServer', x=-55.00, y=63.00, z=296.85], MoCEntityKitty['Kitty'/1263, l='MpServer', x=-55.51, y=63.00, z=296.74], EntityItem['item.item.terraqueous.multifood.coconut'/2033, l='MpServer', x=-38.36, y=77.00, z=265.06], EntityCoconut['entity.coconut.name'/1267, l='MpServer', x=-61.60, y=63.00, z=338.54], EntityItem['item.item.string'/2167, l='MpServer', x=-10.29, y=12.00, z=277.53], MoCEntityBass['Bass'/1400, l='MpServer', x=32.30, y=62.00, z=184.30], MoCEntityAnchovy['Anchovy'/1401, l='MpServer', x=45.28, y=61.73, z=191.10], EntityZombie['Zombie'/2042, l='MpServer', x=-22.51, y=23.00, z=224.81], MoCEntityBass['Bass'/1402, l='MpServer', x=44.23, y=61.99, z=192.59], MoCEntityFishy['Fishy'/1275, l='MpServer', x=-43.77, y=60.99, z=152.41], MoCEntityDeer['Deer'/1277, l='MpServer', x=-30.96, y=65.00, z=209.57], EntityZombie['Zombie'/1917, l='MpServer', x=-3.50, y=39.00, z=274.50], EntityCreeper['Creeper'/2303, l='MpServer', x=-70.50, y=15.00, z=198.50]]
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2748)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:49)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (x86) version 10.0
	Java Version: 1.8.0_161, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 234090872 bytes (223 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.2.2624 22 mods loaded, 22 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                | Version          | Source                                        | Signature                                |
	|:--------- |:----------------- |:---------------- |:--------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft         | 1.12.2           | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | mcp               | 9.42             | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | FML               | 8.0.99.99        | forge-1.12.2-14.23.2.2624.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge             | 14.23.2.2624     | forge-1.12.2-14.23.2.2624.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | mercurius_updater | 1.0              | MercuriusUpdater-1.12.2.jar                   | None                                     |
	| UCHIJAAAA | infinitylib       | 1.12.2-1.12.0    | InfinityLib-1.12.2.jar                        | None                                     |
	| UCHIJAAAA | agricraft         | 2.12.0-1.12.0-a0 | Agricraft-1.12.2.jar                          | None                                     |
	| UCHIJAAAA | baubles           | 1.5.2            | Baubles-1.12-1.5.2.jar                        | None                                     |
	| UCHIJAAAA | biomesoplenty     | 7.0.1.2325       | BiomesOPlenty-1.12.2-7.0.1.2325-universal.jar | None                                     |
	| UCHIJAAAA | botania           | r1.10-353        | Botania r1.10-353.jar                         | None                                     |
	| UCHIJAAAA | codechickenlib    | 3.1.5.331        | CodeChickenLib-1.12.2-3.1.5.331-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | customspawner     | 3.11.3           | Custom-Mob-Spawner-Mod-1.12.2.jar             | None                                     |
	| UCHIJAAAA | jei               | 4.8.3.126        | jei_1.12.2-4.8.3.126.jar                      | None                                     |
	| UCHIJAAAA | journeymap        | 1.12.2-5.5.2     | journeymap-1.12.2-5.5.2.jar                   | None                                     |
	| UCHIJAAAA | minecolonies      | 1.12.2-0.8.4191  | minecolonies-universal-1.12.2-0.8.4191.jar    | None                                     |
	| UCHIJAAAA | mocreatures       | 12.0.3           | Mo-Creatures-Mod-1.12.2.jar                   | None                                     |
	| UCHIJAAAA | movillages        | 1.5.4            | Mo-Villages-Mod-1.12.2.jar                    | None                                     |
	| UCHIJAAAA | nei               | 2.4.1            | NotEnoughItems-1.12.2-2.4.1.233-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | harvestcraft      | 1.12.2q          | Pam's+HarvestCraft+1.12.2q.jar                | None                                     |
	| UCHIJAAAA | pamscookables     | 1.1              | pamscookables-1.1.jar                         | None                                     |
	| UCHIJAAAA | shetiphiancore    | 3.5.6            | shetiphiancore-1.12.0-3.5.6.jar               | None                                     |
	| UCHIJAAAA | terraqueous       | 1.4.10           | terraqueous-1.12.0-1.4.10.jar                 | None                                     |

	Loaded coremods (and transformers): 
ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.6.jar)
  shetiphian.asm.ClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Launched Version: 1.12.2-forge1.12.2-14.23.2.2624
	LWJGL: 2.9.4
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz"

**Comment by ShetiPhian** [comment]
At first I thought it may be a conflict with codechickenlib as you appear to be the first/only one with this issue and their render dispatcher has been injected into the normal pipeline. But I remember seeing other packs using it without problems.

I think this OutOfMemoryError is just that, it appears as if you only gave it 1011MB to work with.
1.8+ uses much more memory then previous versions, due to it storing all models in ram vs. building them on the fly. (trading off ram usage for smoother gameplay)

Most packs want 4GB, but you don't have many mods so 2GB probably would work.
Let me know if that solves it.

**Comment by lwadam** [comment]
thanks for your fast reply,man.
i tried what you suggested - i remember i tried it earlier as well - ,but i got this little gift:

"Error occurred during initialization of VM
Could not reserve enough space for 2097152KB object heap
Java HotSpot(TM) Client VM warning: Using incremental CMS is deprecated and will likely be removed in a future release"
strange,i have 8 gbs of ram in my pc.

**Comment by ShetiPhian** [comment]
Might be a launcher issue; even if its only 32bit, 2GB is under the limit

If your able to use MultiMC, memory allocation can be found here: Edit Instance > Settings
Otherwise you'll need to ask Titan support how to get more ram to work.

**Comment by lwadam** [comment]
the maximum ram i can allocate with MultiMC is 1280 mb.
it is really strange.  i have zero idea what to do now.
i thought maybe java version is the problem which is 1.8.0_161 and i run win10 x64.

**Comment by ShetiPhian** [comment]
It might be an issue with your java install.
161 isn't old, but its possible its corrupt or a previous install locked some setting

Start by uninstalling all java versions.
Reinstall with a fresh download of java (using the offline installer avoids possible issues)

Oracle doesn't let you direct link to the download, so all I can do is provide the download page:
http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html

Use this version:
Windows x64 Offline -- jre-8u162-windows-x64.exe

**Comment by lwadam** [comment]
bro,this solved it all.
tanks so much!
