### ISSUE TITLE
[Terraqueous 1.4.11] Error registering event handler

### ISSUE THREAD

**Issue by NotAVerb** [ShetiPhian/Localizations-and-Issues#164]
This is appearing in my startup logs.
https://gist.github.com/NotAVerb/421c9da881b21c4fbaea036dbd43171d
`Caused by: java.lang.ClassNotFoundException: com.buuz135.industrial.api.plant.PlantRecollectable`

**Comment by ShetiPhian** [comment]
Well it looks like someone forgot to check the logs after changes.... oh wait that was me :)
Like the rest of my mod support I have the code wrapped on a crash handler and side load the classes.

On the plus side it is just a bit of log spam, it can be ignored or with a config change removed
(configs > integration > enableIndustrialForegoing > false)

Besides with the intense log spam so many modpacks have, whats a few more lines ;)

I've fixed this internally, I'll likely push and update on the weekend, giving time for more bugfixes and features.

**Comment by ShetiPhian** [comment]
New build uploaded to Curse
https://minecraft.curseforge.com/projects/terraqueous/files/2554193
