### ISSUE TITLE
destroying bedrock

### ISSUE THREAD

**Issue by Yomamasnuggets** [ShetiPhian/Localizations-and-Issues#166]
When i use the multi tool in pick form on smooth stone that is placed on bedrock the pick seems to try and mine a 3x3 area which removes the bedrock from the world.  Is this supposed to happen?

**Comment by ShetiPhian** [comment]
When I cleaned up the code, a while back, I must have removed the block hardness check.

**Comment by ShetiPhian** [comment]
This should fix it
http://www.mediafire.com/file/0jhfqqfaw8k9pkv/terraqueous-1.12.0-1.4.12-TESTER2.jar

**Comment by ShetiPhian** [comment]
New build uploaded to Curse
https://minecraft.curseforge.com/projects/terraqueous/files/2554193
