### ISSUE TITLE
[Suggestion] [Terraqueous] Have mobs immune to fire damage resist damage from burnium

### ISSUE THREAD

**Issue by NotAVerb** [ShetiPhian/Localizations-and-Issues#167]
It's pretty strange seeing zombie pigmen and blazing juggernauts pass through flames but keel over from standing on burnium.

**Comment by ShetiPhian** [comment]
sigh
A few Minecraft versions ago (1.8?) I changed the way I applied the damage to fix this, but a separate check is now required.

**Comment by ShetiPhian** [comment]
New build uploaded to Curse
https://minecraft.curseforge.com/projects/terraqueous/files/2554193
