### ISSUE TITLE
[Terraqueous] [1.4.11] Non-standard tools with empty button options in the Ender Table

### ISSUE THREAD

**Issue by NotAVerb** [ShetiPhian/Localizations-and-Issues#168]
![2018-03-17_22 01 07](https://user-images.githubusercontent.com/30223331/37562046-f3b249ce-2a55-11e8-9106-60af9cf9ee04.png)
Some unusual tool items have these blank options appear. These options accept any secondary item and give nothing when selected. I'm guessing this is related to the new CraftTweaker integration.

Upon further testing it is possible to use these tools in recipes, but if a value below the required secondary item is supplied first the empty recipes take over.
![2018-03-17_22 53 33](https://user-images.githubusercontent.com/30223331/37562120-b4572e6e-2a57-11e8-8207-5be33fb4b901.png)
![2018-03-17_22 54 50](https://user-images.githubusercontent.com/30223331/37562122-be853610-2a57-11e8-91aa-1e68314e76d5.png)

**Comment by ShetiPhian** [comment]
Could I get the script, I'm likely missing something thus causing the code to process wrong.

**Comment by NotAVerb** [comment]
The null recipes can be encountered with only terraqueous installed. Placing a colorizer in the table works as an example.

I added this line after encountering the issue to test if added recipes would override the null recipes.
`mods.terraqueous.EnderTable.addRecipe(<cyclicmagic:tool_launcher>, <cyclicmagic:tool_rotate>, 2, 1, "A Propulsive Staff", true, <minecraft:slime_ball> * 16);`
It of course requires cyclic.

**Comment by ShetiPhian** [comment]
Gotcha, I thought the error was only appearing with a CraftTweaker script.

**Comment by ShetiPhian** [comment]
Turns out there is issue with the available choices*, when an enchantable item also has a special recipe
[*]they're not refreshing unless you completely empty a slot.


Also not sure whats up with the CraftTweaker optional.
This works:
`mods.terraqueous.EnderTable.addRecipe(<minecraft:dirt>, <minecraft:book>, 2, 1, "make dirt", true, <minecraft:slime_ball> * 16);`

But this doesn't:
`mods.terraqueous.EnderTable.addRecipe(<minecraft:dirt>, <minecraft:book>, 2, 1, "make dirt", <minecraft:slime_ball> * 16);`

Both have supporting methods
```javascript
@ZenMethod
public static void addRecipe(IItemStack result, IIngredient inputItem, int experienceCost, float enchantPower, String tooltip, @Optional IIngredient inputMaterial)
{
	addRecipe(result, inputItem, experienceCost, enchantPower, tooltip, true, inputMaterial);
}

@ZenMethod
public static void addRecipe(IItemStack result, IIngredient inputItem, int experienceCost, float enchantPower, String tooltip, boolean obfuscateTooltip, @Optional IIngredient inputMaterial)
{
	... snip...
```

**Comment by NotAVerb** [comment]
There's also a bit of weirdness with plain books.
This recipe works if you insert the book after inserting the nether star.
`val mending = <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 70 as short}]});`
`mods.terraqueous.EnderTable.addRecipe(mending, <minecraft:book>, 5, 15, "Enchant with Mending", true, <minecraft:nether_star>);`
Placing the star second gives this.
![2018-03-18_21 09 14](https://user-images.githubusercontent.com/30223331/37573654-2a417a52-2b12-11e8-9059-1d2674751f71.png)

**Comment by ShetiPhian** [comment]
If interested, here is a compile of my test build.
http://www.mediafire.com/file/8l4ckhhmy6c63o9/terraqueous-1.12.0-1.4.12.jar

I ran out of free time, squeezed in the Burnium fix, testing is lacking.
should fix:
- logged error at startup when craft tweaker is missing
- multitool being able to mine bedrock 
- the invalid recipes (limited testing)
- available choices not updating (barely tested)
- Burnium burning entities that are immune to fire (untested)

not fixed:
- addRecipe requiring the boolean when including the optional material (I think this might be a CraftTweaker bug, the method exists but it can't find it when the optional field is populated)

**Comment by NotAVerb** [comment]
The staff script seems to be working fine now. Shears, the Flint and Steel, and Cyclic's staves no longer have empty recipes.
Burnium no longer burns pigmen. Blazes seem fine too. The crystals still deal damage but I think that's intentional.
Choices seem to update. I intend on testing to see if it's possible to have more than three button options tied to an ingredient combo later.

By the way, the third button option often has text wrap off of the gui.
![thirdoptiontextwrapping](https://user-images.githubusercontent.com/30223331/37582286-2a649668-2b44-11e8-802d-8554c770f002.png)

**Comment by ShetiPhian** [comment]
New build uploaded to Curse
https://minecraft.curseforge.com/projects/terraqueous/files/2554193
