### ISSUE TITLE
Can't place beds, pressure plates ... on mod-slabs

### ISSUE THREAD

**Issue by Gunvaldfar** [ShetiPhian/Localizations-and-Issues#17]
It's impossible to place anything on mod-slabs (works on mod-planks)

thx
Gunvaldfar

**Comment by ShetiPhian** [comment]
I thought when Forge added isSideSolid they removed all calls to isFullyOpaque, apparently not.

With beds and pressure plates checking isFullyOpaque I'm limited it what I can do.
Either these items can not be placed on slabs, or they can be place on any slabs.
But placing a bed is important so I'd rather have floating beds if placed on a lower slab then being unable to place them at all.
