### ISSUE TITLE
[Multi-Storage] Feature request- disable kill defense mod in the config.

### ISSUE THREAD

**Issue by ProsperCraft** [ShetiPhian/Localizations-and-Issues#170]
We run a PvE server and killing is harsh when someone teleports to you and you are inside, would love to be able to disable that in the server config.

**Comment by ShetiPhian** [comment]
I can add that.
Currently its disabled per vault.

I felt it would be to harsh to kill immediately, so the first time it kicks and warns, following intrusions it kills. If a player hasn't tried entering for a while (think it was 10 minutes) next intrusion is a kick and warning again.

**Comment by ShetiPhian** [comment]
Bad weather has even me a little break.
So I got that config option in.

http://www.mediafire.com/file/oeujydebd7ne1m1/multistorage-1.12.0-1.4.10-TESTER2.jar

**Comment by ShetiPhian** [comment]
New build uploaded to Curse
https://minecraft.curseforge.com/projects/multistorage/files/2556834

**Comment by ProsperCraft** [comment]
Thank you.
