### ISSUE TITLE
flowerpot connects to fence

### ISSUE THREAD

**Issue by neclimdul** [ShetiPhian/Localizations-and-Issues#172]
Looks pretty weird.
1) Make a fence(vanilla).
2) Place a flowerpot next to it.
3) See the fence reach out and connect to the pot.

**Comment by ShetiPhian** [comment]
This should fix it:
http://www.mediafire.com/file/0jhfqqfaw8k9pkv/terraqueous-1.12.0-1.4.12-TESTER2.jar

**Comment by ShetiPhian** [comment]
New build uploaded to Curse
https://minecraft.curseforge.com/projects/terraqueous/files/2554193

**Comment by neclimdul** [comment]
Sorry I didn't get around to testing it but thanks for the fix!
