### ISSUE TITLE
Crashing in Twilight Forest when breaking leaves 

### ISSUE THREAD

**Issue by xun468** [ShetiPhian/Localizations-and-Issues#174]
We are getting server crashes with Terraqueous ver1.4.11 and Twilight Forest ver3.6.345 in Minecraft 1.12.2. The forge version is 14.23.2.2630. This appears to happen when a player breaks a leaf while in the Twilight Forest but it does not happen every time. The only changes to the configs I have made is set several spread chances to 0. 

https://pastebin.com/RMqnyfKY

Also crossposted with Twilight Forest

**Comment by williewillus** [comment]
this has been fixed on our side, but calling getpickblock in a HarvestBlockEvent handler is a bit strange...

**Comment by williewillus** [comment]
perhaps you could use the Block BreakEvent to capture that, it's fired very close to where Harvest Drops is, and it has the advantage where the block is actually still in the world at that point.

**Comment by ShetiPhian** [comment]
Thank you, I knew there was a better way via another event, just way too exhausted to hunt it down.

The break event looks perfect also; pick block shouldn't have issues as the block is there, and the drop event is fired rather shortly after.

Bad weather has given me a slight break, enough time to cleanup the code mess I made last night.
http://www.mediafire.com/file/g2hiynf2vykej40/terraqueous-1.12.0-1.4.12-TESTER3.jar

**Comment by ShetiPhian** [comment]
New build uploaded to Curse
https://minecraft.curseforge.com/projects/terraqueous/files/2554193
