### ISSUE TITLE
Talisman Base crafting doesn't consume items

### ISSUE THREAD

**Issue by kjmaster1** [ShetiPhian/Localizations-and-Issues#175]
You can create infinite Talisman Base's from the Terraqueous mod as the crafting items aren't consumed. The code specifies clay balls to be removed from the crafting table but the json file specifies clay blocks to be used in the recipe.

**Comment by ShetiPhian** [comment]
The recipe is wrong, it should be asking for clay balls.
Only using the clay is intended, as you need the other items after baking the base.

**Comment by ShetiPhian** [comment]
New build uploaded to Curse
https://minecraft.curseforge.com/projects/terraqueous/files/2554193
