### ISSUE TITLE
[1.12.2] Client Crash - Client crash when clicking on a endertank from Multi-storage with an empty cell from techreborn.

### ISSUE THREAD

**Issue by ProsperCraft** [ShetiPhian/Localizations-and-Issues#176]
https://github.com/TechReborn/TechReborn/issues/1502

**Comment by modmuss50** [comment]
You are calling fill with a null fluid stack. IMO I dont see a reason for this to be a thing. I can easily add a check for a null FluidStack, it just doesn't seem like something that I should be handling.

Thanks in advance.

**Comment by ShetiPhian** [comment]
Yep I'm missing a null check, didn't see it sooner as buckets and the mod items I tested with handled it.

**Comment by ShetiPhian** [comment]
Download is live on Curse now.
https://minecraft.curseforge.com/projects/endertanks/files/2556962
