### ISSUE TITLE
ENH: Ability to use 'mod:modid' in white and black config lists

### ISSUE THREAD

**Issue by Wabbit0101** [ShetiPhian/Localizations-and-Issues#177]
Currently we can specify items & blocks as well as oredict keys. Can we also have a whole mod category? The category would allow exclusion or inclusion of all items & blocks from a mod without having to enumerate each thing. With the great flattening soon upon us, this could be very helpful for migration but is generally useful.

Is this possible now with the '(asterisk)' I see the use of `'*'` in the default configs, but there's no mention of wildcarding in comment headers. So `'mymod:*'` instead of a new category?

**Comment by ShetiPhian** [comment]
Wildcards currently only work in dictionary keys.

Should be rather simple to get them to work in the blacklist.
Not sure how to do the whitelist, I'd need to efficiently gather all items the mod registered. Scanning the item registry wouldn't be ideal.

**Comment by Wabbit0101** [comment]
I was only thinking of the black-listed items. The white-list would be tricky (and odd imho).

**Comment by ShetiPhian** [comment]
Doodad blacklist now supports blacklisting entire mods via 'mod:<modId>'

https://minecraft.curseforge.com/projects/terraqueous/files/2616060
