### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by captcookie** [ShetiPhian/Localizations-and-Issues#179]
http://food-plus.wikia.com/wiki/Juicer <--- Example

Good morning! I love the mod and wanted to request a juicer in your future 1.13 update. I think it would be a nice fit for your mod. <3 Thanks.

**Comment by captcookie** [comment]
2nd request: could thaumcraft aspects be added?

**Comment by ShetiPhian** [comment]
Its been a while, so I'll close this.
Trees already add a bunch of food, and I think a juicer is better left for a food mod, that way it can add a bunch of things and use different fruits form any mod
