### ISSUE TITLE
Overabundance of TileEntityDoodads found while profiling

### ISSUE THREAD

**Issue by Sunconure11** [ShetiPhian/Localizations-and-Issues#180]
https://pastebin.com/77NLTdem

Would it be possible to add options to reduce their spawn rates as opposed to just flat out removing them from a world?

**Comment by ShetiPhian** [comment]
Option added.

Side note:
These tile entities are very basic, used only to store the IModelState used for rendering, and have little to no impact on the game. (nothing saved thus no increase to file size, nothing synced thus no increase in network traffic, they don't even tick thus no don't slow the game)

**Comment by ShetiPhian** [comment]
New build is on Curse
https://minecraft.curseforge.com/projects/terraqueous/files/2616060
