### ISSUE TITLE
1.12.2 Breaking Dense Stone Junkboxes

### ISSUE THREAD

**Issue by Keridos** [ShetiPhian/Localizations-and-Issues#181]
When you place 2 dense Stone junkboxes on top of each other and then mine them with a pickaxe you get one normal and only one dense stone junkbox back. Using multistorage-1.12.0-1.4.9

**Comment by ShetiPhian** [comment]
The drops are correct,
There is only one dense upgrade used per block space, when you stack the dense boxes the extra upgrade item is returned to your inventory.

The four ways to get a double dense junkbox:
stack a dense on a normal
stack a normal on a dense
apply an upgrade to a double normal
stack a dense on a dense (note: this returns an upgrade)

**Comment by Keridos** [comment]
Ah ok, seems pretty unintuitive...
