### ISSUE TITLE
Attempting to place cloud workbench in invalid locations still replaces snow/long grass

### ISSUE THREAD

**Issue by TheDeviantCrafter** [ShetiPhian/Localizations-and-Issues#183]
If you hold a cloud workbench and then attempt to place it in a block space containing a snow cover or long grass, the grass or snow will disappear. This would happen if you placed a block in this location, but since cloud blocks can only be placed next to other clouds, no block is actually placed.

**Comment by ShetiPhian** [comment]
The earth and cloud machines share a block, I must have missed a check.

**Comment by ShetiPhian** [comment]
New build is now on Curse
https://minecraft.curseforge.com/projects/terraqueous/files/2616060
