### ISSUE TITLE
[Issue] Excessive feather drop

### ISSUE THREAD

**Issue by accessdenied0** [ShetiPhian/Localizations-and-Issues#185]
MC: 1.12.2
MCF: 14.23.4.2705
Terraqueous: 1.12.0-1.4.12
Shetiphiancore: 1.12.0-3.5.7.jar
Quark: r1.4-125.jar

Chicken dropping feathers every second. I think it could be an issue with Quark, but I'm not sure. I disabled it in Quark, didn't helped. Only disabeling it in Terraqueous' config,[ it stopped the excessive drop.](http://puu.sh/AMZUD/d5ac0f02ca.png)

**Comment by ShetiPhian** [comment]
Mod conflict.
Either its a child chicken who is not aging correctly, or an adult chicken with its egg drop timer altered.

With the timers unreliable, I might be better off making it an AI task.

**Comment by primetoxinz** [comment]
Yes, this is in fact Better With Mods HCChickens, which makes the vanilla timer int max value so we can implement our own timing system on vanilla chickens. It would be best to move away from that method.

**Comment by ShetiPhian** [comment]
I converted it into an AI task, shouldn't get any mod conflicts now.

New build is now on Curse
https://minecraft.curseforge.com/projects/terraqueous/files/2616060
