### ISSUE TITLE
Underside of fence "bars" invisible.

### ISSUE THREAD

**Issue by CorvusUrro** [ShetiPhian/Localizations-and-Issues#186]
The model you use for fences has the bottom of the horizontal portion of the fence cull when they shouldn't

**Comment by CorvusUrro** [comment]
Solution seems to be removing both instances of 

> , "cullface": "down"

 from "\assets\terraqueous\models\block\bases\fence_part.json"

**Comment by ShetiPhian** [comment]
Not sure if that was cause by me copying the wall model or just me being an airhead.
This will be fixed in the next release build.

**Comment by ShetiPhian** [comment]
New build is now on Curse
https://minecraft.curseforge.com/projects/terraqueous/files/2616060
