### ISSUE TITLE
Leaf blocks seem to be air with tileentitydata?

### ISSUE THREAD

**Issue by Shovinus** [ShetiPhian/Localizations-and-Issues#189]
I am trying to make [CDU](https://minecraft.curseforge.com/projects/chop-down-updated) compatible with your mod, however on investigating it seems the leaf blocks are actually air blocks jsut with tile entitydata associated? This means I canno make your trees fall over, if it possible to change this to work more like Forestry does?

**Comment by ShetiPhian** [comment]
My leaves extend BlockLeaves and have no TileEntity

BlockState Flags: fastmode[true, false], treevariant[see id's], variant[normal, flower, fruit]
Treevariant per id:
foliage1[apple, cherry]
foliage2[orange, pear]
foliage3[peach, mango]
foliage4[lemon, plum]
foliage5[coconut, banana]

foliage5 uses a different variant[normal, flower, fruit, stalk_bare, stalk_grow]
the leaves are always normal, the others are for the banana stalk

**Comment by Shovinus** [comment]
ok this is really wierd then, I have a function bound to inspect the block and tell the the name and id, when I click your block it comes back with air, I will double check, possibly it is removing the block before my script inspects it.

**Comment by Shovinus** [comment]
ok tested in gamemode 0 now :S https://youtu.be/8l0kz9xmHec

**Comment by Shovinus** [comment]
Ahhh think I found the issue, should use getPickBlock instead of getItem on the block in 1.12

**Comment by Shovinus** [comment]
Yes that has sorted it :) sorry to waste your time.
