### ISSUE TITLE
EnderLink Bag/Chest Voids Items When Inventory Full

### ISSUE THREAD

**Issue by Kumomo** [ShetiPhian/Localizations-and-Issues#19]
The enderlink bag/chest voids items if your inventory is full and you attempt to shift click more items into your inventory from the enderlink bag or chest.

Was running MultiStorage 1.10.0-1.2.10 and shetiphiancore 1.10.0-3.3.5 when it first occurred. Tested with newest versions MultiStorage 1.10.0-1.2.11 and shetiphiancore 1.10.0-3.3.6 and the issue persists.

**Comment by ShetiPhian** [comment]
Fixed in multistorage-1.10.0-1.2.12 & multistorage-1.11.0-1.3.1

ShetiPhianCore could also use some changes, its why there was loss rather then inaccessible items, but MultiStorage stops it form happening.

**Comment by Kumomo** [comment]
Thank you for the fast fix!
