### ISSUE TITLE
Request: Option to disable custom appearance in GUIs

### ISSUE THREAD

**Issue by Crowfooted** [ShetiPhian/Localizations-and-Issues#190]
Just a pet peeve of mine - I prefer all the GUIs ingame to match the vanilla Minecraft feel, so it would be really nice to be able to disable the custom appearance/texture of the GUIs you get when interacting with storage blocks (specifically the one I've seen is the one from the enderlink chest).

**Comment by ShetiPhian** [comment]
I have done a few in the vanilla style, indented on finishing them all then releasing a texture pack but having it built in with a config option would be far more convenient for players.

**Comment by ShetiPhian** [comment]
New builds are on Curse
https://minecraft.curseforge.com/projects/multistorage/files/2616063
https://minecraft.curseforge.com/projects/platforms/files/2616061
https://minecraft.curseforge.com/projects/terraqueous/files/2616060
