### ISSUE TITLE
Platforms Monkey Wrench - Add Tooltip about offhand usage

### ISSUE THREAD

**Issue by Shadlock0133** [ShetiPhian/Localizations-and-Issues#191]
Adding tooltip to monkey wrench saying something like "Place in offhand to show placement outline" would definitely make it easier to discover.

**Comment by ShetiPhian** [comment]
Added to the next build

**Comment by Shadlock0133** [comment]
Thanks.

**Comment by ShetiPhian** [comment]
New build is on Curse
https://minecraft.curseforge.com/projects/platforms/files/2616061
