### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by DatrixTHLK** [ShetiPhian/Localizations-and-Issues#192]
Hi ShetiPhian,

This might be an error from a different mod, but I wanted to check with you first in order to ensure the error is not on your side.

Terraqueous crashed me to the title screen of the game since VanillaFix is within my mods folder. Crash report noted an error. Does nullpointerexception mean that something in the mod itself is not defined or is it something the user themselves defined incorrectly within the config?

Crash Report: https://paste.dimdev.org/egulexixes.mccrash

Minecraft 1.12.2
Forge: 14.23.4.2759
ShetiphianCore: 3.5.8
Terraqueous: 1.4.13

**Comment by ShetiPhian** [comment]
A null has made it into the list of ore names.
Something is registering an item using null as the id

Forge doesn't check for this, but it does have an event that is fired on every registration, so I coded a mod that watches for an invalid id and logs it.

http://www.mediafire.com/file/0s08ji10kyzb5rb/tool_dictionary_check-1.12.0-1.0.0.jar/file
Place it in you mods folder and launch the game.
The error will appear in the console and be saved into 'fml-client-latest.log'

**Comment by DatrixTHLK** [comment]
Will do. Thanks for the response. I appreciate it.
