### ISSUE TITLE
Question about cloud spawns underground?

### ISSUE THREAD

**Issue by Milesman34** [ShetiPhian/Localizations-and-Issues#193]
If I was to, in theory, make the world surface level around y=220, would clouds still spawn underground, or would they not spawn anywhere, or spawn aboveground?

**Comment by ShetiPhian** [comment]
For the most part they wouldn't spawn, but you'd find a few in large open areas, because they can't spawn touching other blocks.

By default spawn around 3/4 the world height, but the configs has a 'cloudHeightOverride' option you can use to set the generation height.
