### ISSUE TITLE
crash report doodads

### ISSUE THREAD

**Issue by boosterdev** [ShetiPhian/Localizations-and-Issues#194]
not sure if you can help or fix this.
version info in crash report
`Exception while updating neighbours`

[crash-2018-09-25_14.30.29-server.txt](https://github.com/ShetiPhian/Localizations-and-Issues/files/2415186/crash-2018-09-25_14.30.29-server.txt)

restarting the server solves problem (temporary I guess untill it happends again)

**Comment by ShetiPhian** [comment]
You've got a invalid entry in the Ore Dictionary.

I can add a null check, but that just hides the issue can will just cause a crash somewhere else when another mod tries to read the dictionary entry.

Its better to get the mod with the broken entry to fix it then to hide the problem.

Here is a dictionary checker mod I wrote to to detect this problem when the item is registered.

http://www.mediafire.com/file/0s08ji10kyzb5rb/tool_dictionary_check-1.12.0-1.0.0.jar/file
Place it in you mods folder and launch the game.
The error will appear in the console and be saved into 'fml-client-latest.log'
