### ISSUE TITLE
ShetiPhianCore-1.11.0-3.4.4 Infected?

### ISSUE THREAD

**Issue by Ahoogas** [ShetiPhian/Localizations-and-Issues#195]
So, I haven't checked my antivirus in a while, so I decided to do it and what do I find? 
I find that this mod tried to install a Trojan Virus on my pc!
Here's a Screenshot: https://gyazo.com/c8f2649883cc82acac30b3264a04aec8

**Comment by Ahoogas** [comment]
Nothing here is infected, my anti-virus detected a hidden Trojan Virus in your addon, downloaded via twitch launcher.

**Comment by ShetiPhian** [comment]
If you go to the curse download page (https://minecraft.curseforge.com/projects/shetiphiancore/files/2404427) you can see the MD5 value for the file I uploaded (f81c43be77a6b8e7d580526fd2ea36cc)

Curse generates the MD5 at the time of upload.

If your file has a different MD5 its been tampered with, this is out of my control, try downloading again. (and if that fails try a newer 1.11 build, just make sure the MD5's match)
If you have the same MD5 your antivirus is giving a false positive. Send them the file, and wait or try 3.4.9 it doesn't have shadekillers code which caused the false positive for Ikarus last year.
