### ISSUE TITLE
I have an issue with rails

### ISSUE THREAD

**Issue by BOSSthomas** [ShetiPhian/Localizations-and-Issues#198]
I have downloaded the mod and make platforms .
Then i want to place a rail on it but nothing happends ? what could this be ? .
What i have to do.

i have thiis version platforms-1.12.0-1.4.6

**Comment by ShetiPhian** [comment]
Only the Frame and Floor variants fulfill the placement requirements of rails.

https://minecraft.curseforge.com/projects/platforms/images
In the "Example 1" photo, the rails of the wooden coaster are placed on Frames with the Flats and Ramps  beside them on Frames of their own.
The mine shaft photo, "Example 2", makes this a bit easier to see.

Frames also support torches, which in turn can be modified with glowstone dust.
Torch = Basic Light
Torch + Dust = Glowstone Light
Redstone Torch = Redstone Mode
Redstone Torch + Dust = Redstone Lamp

Redstone Mode:
Lamp is on by default, while on it emits a signal strength of 15 up, 1 to the sides, and nothing down.
A comparator/repeater can be used to read/boost the signal from the sides.
Providing power to the bottom (any strength) or sides (>1) will turn the torch off.

**Comment by ShetiPhian** [comment]
I was just about to close this when it dawned on me I only assumed you meant mine cart rails (a question I've had before) where you may have been talking about the hand rails I added.

While Rises can be placed anywhere, Rails must be attached to another platform.
Rails and Rises will only attach to 'Flat', 'Ramp' and 'Floor' style platforms.

In addition will only be visible on variants 1-10 (1 & 2 for Ramps)
(shift click with the wrench to see/change the variant)
