### ISSUE TITLE
Just a suggestion / request.

### ISSUE THREAD

**Issue by scottwilson0308** [ShetiPhian/Localizations-and-Issues#199]
Hey,

Love the mod. Just wondering if it'd be possible to split a config option into two.
B:addCraftables split into B:addCloudCraftables & B:addEarthCraftables

I'm trying to reduce the load on RAM, and don't need the different colored wood items, but I just can't part with the beautiful clouds!

**Comment by ShetiPhian** [comment]
New build has the change.
https://minecraft.curseforge.com/projects/terraqueous/files/2641239
