### ISSUE TITLE
Crash with Ic2

### ISSUE THREAD

**Issue by TacticalUniverse** [ShetiPhian/Localizations-and-Issues#202]
https://gist.github.com/TacticalUniverse/a613e0ea762dbd43da6b6f6376700e10

**Comment by ShetiPhian** [comment]
This is likely due to the same bug that was causing https://github.com/ShetiPhian/Localizations-and-Issues/issues/201

Let me know if this build also fixes the bug for you.
http://www.mediafire.com/file/hoj5dchhwgecejj/endertanks-1.12.0-1.6.8.jar/file

**Comment by TacticalUniverse** [comment]
Will test it right now

**Comment by ShetiPhian** [comment]
https://minecraft.curseforge.com/projects/endertanks/files/2664673
