### ISSUE TITLE
Crash on content changed

### ISSUE THREAD

**Issue by Balint66** [ShetiPhian/Localizations-and-Issues#205]
Hello there!

First of all: I love your mods. When I create a modpack for myself and/or for my friends I include some of them.

Now, I have an issue with the Endertanks mod. Here is the link for the crash on [hastebin](https://paste.dimdev.org/mekiletava.mccrash)

I recently installed [randomPatches](https://minecraft.curseforge.com/projects/randompatches) and [randomTweaks](https://minecraft.curseforge.com/projects/randomtweaks) and after that every time I try to load one of my saves it crashes with the same error.

I hope it's not that bad and can be easily fixed. :)

**Comment by ShetiPhian** [comment]
Upgrading to 1.6.8 will likely fix it.
https://minecraft.curseforge.com/projects/endertanks/files/2664673

I added comparator support in 1.6.7 but overlooked a case where it would run on the wrong thread, and caused issues.

**Comment by Balint66** [comment]
Sorry, I did not see the update. 😅

It fixed the error

Thank you very much! Have a nice day!

**Comment by ShetiPhian** [comment]
No problems, works out well as I didn't need to leave the 1.13 updating I was doing.

Side Note on 1.13:
Forge likely will not leave beta as it will not have all the rewrites done. They plan on jumping into 1.14 ASAP.

**Comment by Balint66** [comment]
Thanks for the side note. I'm a programmer too and I know how hard it is to implement features and stay up-to-date with the API. I hope that they will implement the liquid system again in the 1.14. version and that I will be able to make a mod someday.

Have a nice day and thank you for helping me!
