### ISSUE TITLE
Client crash on a multiplayer server - java.lang.NullPointerException at net.minecraft.network.play.client.CPacketClickWindow

### ISSUE THREAD

**Issue by ProsperCraft** [ShetiPhian/Localizations-and-Issues#206]
When opening an ender pouch, player can not reproduce.

https://gist.github.com/ProsperCraft/ed234fbd7bff42dfb935dfb97fef4576

Modpack - https://minecraft.curseforge.com/projects/drtardis-2-new-adventures

**Comment by ShetiPhian** [comment]
Not sure how the player managed to trigger the bug, but it reveled an error in my container.

Somehow between handleMouseClick and windowClick the item changed to an open bag, as handleMouseClick aborts the click if the item is an open bag.

New build pushed to Curse
https://minecraft.curseforge.com/projects/multistorage/files/2694955
