### ISSUE TITLE
Possibility to remove a Personal or Team Lock on Ender-Link Chest or Tanks

### ISSUE THREAD

**Issue by Fireztonez** [ShetiPhian/Localizations-and-Issues#207]
Hello,
I really want a possibility to remove the lock on a Personal or Team Link Chest and the same for the tank. With EnderStorage I know you can unlock with a Shift-Right click on the lock, but this is not possible for what I know with ModularStorage... If doing in world is too complicated, a simple crafting table to unlock and give back the lock item will be good.

If you do not have plan to add that functionality, let me know, I will have to create a recipe for that with Crafttweaker...

Thank you very much for your mod, I really really enjoy how it work, the Team Lock is an awesome functionality, continue your great work!

Fireztonez

**Comment by ShetiPhian** [comment]
I don't remember if I added it, but if I did.
Just breaking the block will keep all upgrades, but breaking while sneaking should drop the upgrades separately (minus capacity upgrades as those are tied to the storage pocket and not the block)

**Comment by Fireztonez** [comment]
Ok, thank's for the information. This is really good to know, I will add information in tooltips for Sneaking when mining the Chest!
