### ISSUE TITLE
Crashing while nearing a village

### ISSUE THREAD

**Issue by gianniluca01** [ShetiPhian/Localizations-and-Issues#209]
The Game crashes as I near a village.
[crash-2019-04-15_14.26.48-client.txt](https://github.com/ShetiPhian/Localizations-and-Issues/files/3080106/crash-2019-04-15_14.26.48-client.txt)

**Comment by ShetiPhian** [comment]
> Description: Rendering entity in world
> 
> java.lang.ClassCastException: java.lang.Float cannot be cast to java.lang.Boolean
> 	at mca.actions.AbstractToggleAction.getIsActive(AbstractToggleAction.java:41)
> 	at mca.entity.VillagerBehaviors.isToggleActionActive(VillagerBehaviors.java:139)
> 	at mca.client.render.RenderVillagerMCA.doRenderEffects(RenderVillagerMCA.java:172)
> 	at mca.client.render.RenderVillagerMCA.doRender(RenderVillagerMCA.java:367)
> 	at mca.client.render.RenderVillagerMCA.func_76986_a(RenderVillagerMCA.java:34)
> 	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:384)

The crash is in the MCA code, while rendering their villagers.
