### ISSUE TITLE
EnderLink Chests open a Ghost GUI to unallowed player in claim chunks

### ISSUE THREAD

**Issue by Fireztonez** [ShetiPhian/Localizations-and-Issues#210]
Hello,
I have tests some things with a friend on my server, and I found a Bug with EnderLink Chests on Claimed Chunks with FTBUtilities. When he right-click on the chest, an "Ghost GUI" where it can place items. This caused a inventory desync Server/Client, like you can see in the video:
https://streamable.com/ydv4j 

Version:
Forge: 14.23.5.2824
Multi-Storage: 1.4.13
FTB Library: 5.4.1.93
FTB Utilities: 5.4.0.90

**Comment by ShetiPhian** [comment]
I have an idea to fix this, few more days out before I can do so though.
I'll post here when the new build is available.

**Comment by ShetiPhian** [comment]
This one was opening the chest on both the client and server, when it should have been opening it on the server which in turn tells the client to open the GUI

I haven't gotten around to testing this but if the other chests work correctly this build should fix the bug:
http://www.mediafire.com/file/6a5149fr19249cw/multistorage-1.12.0-1.4.14.jar/file

Not posting to Curse yet as its untested and still working on the Queue Chest issue submitted.

**Comment by ShetiPhian** [comment]
Build on Curse
https://minecraft.curseforge.com/projects/multistorage/files/2710024
