### ISSUE TITLE
Can't place ladders on vault blocks

### ISSUE THREAD

**Issue by BrisingrAerowing** [ShetiPhian/Localizations-and-Issues#211]
I'm building a 15x15x16 vault that has multiple internal levels (for a bank build I'm doing), and I can't place ladders on the vault wall blocks, which is kind of annoying.

**Comment by ShetiPhian** [comment]
I'll add ladder support in the next build.
Have some bugs to fix also, but it will be a few days before I can work on them.

**Comment by ShetiPhian** [comment]
Still working on other bugs but here is a build with working ladders.

http://www.mediafire.com/file/6a5149fr19249cw/multistorage-1.12.0-1.4.14.jar/file

**Comment by ShetiPhian** [comment]
Build on Curse
https://minecraft.curseforge.com/projects/multistorage/files/2710024
