### ISSUE TITLE
Suggestion: Limit max banana stalk length

### ISSUE THREAD

**Issue by inkdear** [ShetiPhian/Localizations-and-Issues#217]
It's just very... infinite under the right conditions
https://i.imgur.com/V41lzle.png

I would like to suggest limiting it to something like 4 blocks (kind of like sugar cane)

I grew these with bonemeal to test, my apologies if it actually does have a growth limit normally.

**Comment by ShetiPhian** [comment]
It didn't have one before,

In 1.14 I changed it to be limited by the trees height.
I didn't limit it to 4 blocks as real stalks can grow until the flower is crushed.
