### ISSUE TITLE
[1.10.2] Terraqueous interferes with YUNoMakeGoodMap (or the other way)

### ISSUE THREAD

**Issue by DeadSix27** [ShetiPhian/Localizations-and-Issues#22]
Version: terraqueous-1.10.0-1.2.14.jar

I reported this on his mod issue tracker as well.

(See here: https://github.com/LexManos/YUNoMakeGoodMap/issues/30 )

One of those mods does not like to be with the other one.
As I have no errors our warnings displayed I can only give you that much information (unfortunately). (See the other issue for at least a little bit more information, below the edit)

When the server starts, it simply hangs on preparing world.

If you need a mod list see this gist:
https://gist.github.com/DeadSix27/df6ed6b085cd14497e13fcb362883020

**Comment by ShetiPhian** [comment]
Looks be be my tree generator.

YUNo doesn't cancel the TerrainGen.decorate events opting for setting the y value to -1. Most likely done to work around mods that don't support the TerrainGen events.

This in turn reveals a fault in my tree generator that causes it to get stuck in an endless loop.

**Comment by DeadSix27** [comment]
Nice! (the fact you identified the cause)

Are you going to work around it or fix it still within 1.10.2?  (I would appreciate that very much :P)

**Comment by ShetiPhian** [comment]
Fixed applied to both 1.10 and 1.11
Just compiled and uploaded it now.

**Comment by DeadSix27** [comment]
Awesome! I'll test it later and close the issue if it works! thanks @ShetiPhian
