### ISSUE TITLE
[Suggestion] Better "doodads" drop configurations.

### ISSUE THREAD

**Issue by UnlimatedStone9** [ShetiPhian/Localizations-and-Issues#220]
To put it simply, the configuration options for what "doodads" drop is tedious, you remove any specific outputs rather than being able to just disable all current outputs and add your own, and then you install another mod, that mods items dropping again, not to mention occasionally "doodads" like rocks drop invalid missing texture items, or items with broken names etc.
If there was an option to disable all default output mechanics, and then be able to configure what they drop thereafter, that would be perfect!

Thanks again, the mod is very useful!

**Comment by ShetiPhian** [comment]
The doodads are completely controlled by their whitelist and blacklist,
A blank whitelist disables all drops.
The entry "ore:dust*#1" is the one causing it to scan the Ore Dictionary and add any dusts found.

**Comment by UnlimatedStone9** [comment]
Seems to work fine, thanks ShetiPhian!
