### ISSUE TITLE
[1.12.2] Client crash on multiplayer server.

### ISSUE THREAD

**Issue by ProsperCraft** [ShetiPhian/Localizations-and-Issues#222]
The player says he was flying around the server and his client crashed-
https://gist.github.com/ProsperCraft/68240964ac1b49b4e3fb2459d68d80e9

Modpack- https://www.curseforge.com/minecraft/modpacks/towncraft

**Comment by ShetiPhian** [comment]
Looks like a bed split by a chunk boundary tried to render while its other half is in an unloaded chunk.
When I can I'll need to add an error handler for this.
On the plus side it should be quite rare. a bed would need to be placed spanning a chunk border, using a banner as a spread, and be visible from the air. Then a player needs to be moving through unloaded chunks fast enough the game isn't keeping up, and in the direction that requires the bed to check its other half.

**Comment by ProsperCraft** [comment]
Yes, it was quite rare, it didn't show up in our daily 6 months of testing the pack before release, or the over a year of being played.

**Comment by P3rf3ctXZer0** [comment]
I already reported this like 9 months ago @ShetiPhian you never fixed it? It is not as rare as you think and extremely easy to trigger (unfortunately)

**Comment by ShetiPhian** [comment]
I thought I had already pushed the fixed build. (it is in my current code base)

There is an upcoming build, just waiting on some textures.

**Comment by ShetiPhian** [comment]
https://www.curseforge.com/minecraft/mc-mods/multibeds/files/3048623
