### ISSUE TITLE
[1.14.4] MultiBeds Crash

### ISSUE THREAD

**Issue by NillerMedDild** [ShetiPhian/Localizations-and-Issues#224]
I used the Bed-kit to make a bed, and the game crashed. 
The logs point towards Xaero's minimap as well, so I'm opening an issue with that mod as well :)
Edit, that issue is here: https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap/issues/114

https://gist.github.com/NillerMedDild/59b12f76ac345b7e7342cd626d652769

**Comment by ShetiPhian** [comment]
My fault.
I set a default color for the block to cover the chance the tile entity was unavailable, but forgot to set a default for then the tile exists but the is no blanket.

I'll push out a fixed version in the morning.

**Comment by ShetiPhian** [comment]
New build was submitted:
https://www.curseforge.com/minecraft/mc-mods/multibeds/files/2849895

**Comment by NillerMedDild** [comment]
Thank you :)
