### ISSUE TITLE
[1.14.4] Allow Blocks to be Waterlogged

### ISSUE THREAD

**Issue by WenXin20** [ShetiPhian/Localizations-and-Issues#225]
Allowing the waterlogging of MultiBeds and Platforms could be a nice way to add more customization. It would be good for underwater decorations.

**Comment by ShetiPhian** [comment]
Added.
https://www.curseforge.com/minecraft/mc-mods/multibeds/files/2849895
https://www.curseforge.com/minecraft/mc-mods/platforms/files/2849892
