### ISSUE TITLE
Platforms GUI Tooltips Render Below JEI Items

### ISSUE THREAD

**Issue by WenXin20** [ShetiPhian/Localizations-and-Issues#226]
`Minecraft v1.14.4`
`Forge v28.1.109`
`Platforms v1.5.1`

Item tooltips in the PlatFormer GUI render below JEI items.
The GUI background also doesn't get darker.

![2020-01-12_01 09 56](https://user-images.githubusercontent.com/12000593/72215529-35992d00-34d9-11ea-8282-fa36355b4a6a.png)

**Comment by ShetiPhian** [comment]
I'm calling renderHoveredToolTip at the end of render just like the Minecraft gui's.
If they work correctly then it must be the lack of the renderBackground call.

And in that case my guess is JEI would normally render during the BackgroundDrawnEvent, (which is called from renderBackground, and happens before renderHoveredToolTip) and when it can't it must render after the gui's render method (thus after the tooltips, and appears on top)

**Comment by WenXin20** [comment]
That sounds correct, based on a similar issue I also reported a while back at CreativeMD/LittleTiles#217

**Comment by ShetiPhian** [comment]
Fixed in the new build of ShetiPhianCore
https://www.curseforge.com/minecraft/mc-mods/shetiphiancore/files/2887757
