### ISSUE TITLE
Requesting same mod but for items

### ISSUE THREAD

**Issue by carlucci9660** [ShetiPhian/Localizations-and-Issues#229]
This is an amazing mod. Makes the game so much more enjoyable, when used to its full potential. Now i was hoping you might want to make another mod for items, using this as a base. 

Yes, there is mod out there for ender chest and bag (items side) but the author is not going to port this over to 1.14.4......so that leaves people like me in the dark trying to find something that will work like this for items. I loved it for 1.7 and 1.12....now we are ready to use something for future versions. 

Thank you for your hard work !

Rich
Starbound Modder

**Comment by ShetiPhian** [comment]
I updated my response on Curse but I'll post here to increase the likely hood it will be seen.

I've decided to split EnderChests off of MultiStorage, as it has been requested semi-frequently and it will allow the chests to be 1.14 ready sooner.
The project isn't live yet as nothing has been uploaded, but here is the url: https://www.curseforge.com/minecraft/mc-mods/enderchests

**Comment by ShetiPhian** [comment]
EnderChests has been uploaded, currently 'Under Review' but shouldn't be long

https://www.curseforge.com/minecraft/mc-mods/enderchests/files/2887778
