### ISSUE TITLE
Crashes client when looking at chameleon multistorage block

### ISSUE THREAD

**Issue by shortybsd** [ShetiPhian/Localizations-and-Issues#23]
Forge 2199
MC v1.11
shetiphiancore-1.11.0-3.4.1
multistorage-1.11.0-1.3.0
Hwyla-1.8.5-B19_1.11

When looking at a chameleon multi-storage Hwyla/Waila crashes the client. Disable Hwyla and everything is fine. Here is the error:
http://pastebin.com/KbQDZ3Xr

I reported this issue to Hwyla and TehNut confirmed that the problem is relating to following:

Caused by Multistorage returning null in BlockStorageType#getPickBlock(...). Please report this to them.

Here is a link https://github.com/TehNut/HWYLA/issues/34

**Comment by ShetiPhian** [comment]
I knew when 1.11 made null stacks invalid a few would be overlooked. -_-

Also I like the way TehNut displays that error, funny for the user and the console politely informs what and where the problem is.

**Comment by ShetiPhian** [comment]
The new build is now on Curse
