### ISSUE TITLE
can't walk on platforms or ramps?

### ISSUE THREAD

**Issue by HentaiHamster** [ShetiPhian/Localizations-and-Issues#230]
Minecraft 1.14.4
platforms release latest
forge -28.2.0

platforms cant be walked on? I can;t walk on them at all...and when i jump onto them i get stuck
the ramps and floor parts both do it.

**Comment by ShetiPhian** [comment]
Is the selection box correct? (collision and selection are looked up the same way)
If not some json file failed to load (can be any mods file) and Minecraft has aborted loading resources.

Logs may have the source of the problem.

**Comment by RangeCreed** [comment]
I'm having a similar issue, I can't step on any platform on my server, it just makes me float and get stuck, Works perfectly fine in survival though.

**Comment by ShetiPhian** [comment]
While I haven't been able to recreate the issue, I had and idea about it.

If this test build works I'll know I'm on the right track and can finish the code changes.
https://www.mediafire.com/file/6191pzwd6mecqy7/platforms-1.14-1.5.2-TESTER-1.jar/file
