### ISSUE TITLE
[1.14] Platforms: Crash when climbing platforms

### ISSUE THREAD

**Issue by coolnickname** [ShetiPhian/Localizations-and-Issues#234]
Crash report: https://pastebin.com/kCPNCY1a

Single player world, I took the items from the creative menu. I place some platforms in a 1x1 pillar and a wooden raise against the bottom one. The game crashed when I tried to jump on the raise. Now the world crashes when I load it.

Please let me know if I can help. Also, really cool mod :).

**Comment by ShetiPhian** [comment]
Couldn't trigger the crash, but the report allowed me to see where it happened.
Not sure what caused code execution to get where it was but here is a test build which should fix the crash.

http://www.mediafire.com/file/v2gwzkglfx19nna/platforms-1.14-1.5.2-TESTER-2.jar/file

**Comment by coolnickname** [comment]
I haven't been able to reproduce it since either. Might have been a one-off thing.

**Comment by Sandriell** [comment]
Came here to report this as well and wanted to add that the pre-release (I grabbed TESTER-3 from the other issue) fixed it.

**Comment by ShetiPhian** [comment]
Closing as the test code was integrated into the release builds.
