### ISSUE TITLE
[1.14] Platforms: Crash when placing any platform block above a water/lava block

### ISSUE THREAD

**Issue by necros0** [ShetiPhian/Localizations-and-Issues#235]
https://pastebin.com/xA11YTPt

Not much to this one, placing any kind of platform block above a water or lava block crashes the client.
If you replace the water with dirt, then destroy the dirt after the platform is placed, it crashes in the same way, but the log comes from the server instead of the client.

**Comment by ShetiPhian** [comment]
Mojang!!! *shakes fist*
That method should at lest return a null so a code warning is displayed, you don't even preform a condition check in most places its used. -_-

I'll get that patched up.

**Comment by ShetiPhian** [comment]
http://www.mediafire.com/file/lcr5zmu84rmewlb/platforms-1.14-1.5.2-TESTER-3.jar/file
