### ISSUE TITLE
[1.8.9] Client crash when I break some blocks (SERVER)

### ISSUE THREAD

**Issue by Likrya** [ShetiPhian/Localizations-and-Issues#236]
Hello, I've some problems with Terraqueous on a server.
I'm on a private server with some friends, but when i try to break some wood-related blocks from the mod (Fence, planks...), my client crash instantly. It also crash when someone is breaking one of these blocks when he's near of me. I tryed to uninstall-reinstall the mod but it didnt works. I can break blocs in solo-mode with no problems. Here is the crash report.
[crash-2020-04-10_16.49.19-client.txt](https://github.com/ShetiPhian/Localizations-and-Issues/files/4462081/crash-2020-04-10_16.49.19-client.txt)

**Comment by ShetiPhian** [comment]
Sorry but 1.8.9 is too old.
I no longer have a development environment for it, and its before I started using version control to backup the source code.

The crash is in ShetiPhianCore though and your one build behind, maybe its was fixed but undocumented. https://www.curseforge.com/minecraft/mc-mods/shetiphiancore/files/2307032
