### ISSUE TITLE
[Multistorage 1.4.14] CapacityMax=54 does not allow more than 27

### ISSUE THREAD

**Issue by perellonieto** [ShetiPhian/Localizations-and-Issues#237]
I set the CapacityMax parameter to 54 for the EnderLink upgrade settings, but as I use enderpearl or ender_eye and the message indicates that the capacity has been increased to 54, when it is opened it only shows 3 rows and 9 columns.

Maybe I am doing something wrong?

This configuration is set in the server side.

**Comment by ShetiPhian** [comment]
Currently can't test it, but I'm sure it needs to be set server side and client side.
The server uses the variable to control the functionality, while the client uses it for rendering.

**Comment by perellonieto** [comment]
Thanks, I have tested and it actually works as you have indicated here.
