### ISSUE TITLE
[1.15.2] Crash on server start

### ISSUE THREAD

**Issue by IchigoGames** [ShetiPhian/Localizations-and-Issues#238]
Crashed as soon as a launched it on server

Minecraft 1.15.2
Forge 31.1.77
shetiphiancore-1.15-3.7.0

crash report https://pastebin.com/DvdFxtaJ

**Comment by deadspidervenom** [comment]
can confirm i am getting it as well

https://pastebin.com/0cx1F6pk

**Comment by ShetiPhian** [comment]
Fixed

https://www.curseforge.com/minecraft/mc-mods/shetiphiancore/files/2954686
