### ISSUE TITLE
[1.15.2 Bug] Ender Chest

### ISSUE THREAD

**Issue by BedrockLegends** [ShetiPhian/Localizations-and-Issues#239]
![2020-05-11_12 55 45](https://user-images.githubusercontent.com/48525410/81594611-d106b580-9386-11ea-8816-63ba205cd8f0.png)

As you can see the sort buttons are overlapping the chest and idk if this is a bug with your mod or another

**Comment by BedrockLegends** [comment]
Might be a quark bug but not sure

**Comment by ArMoReDfUrY** [comment]
does it still appear that way once you have expanded the chest to full size? you can use ender pears to upgrade it by 3 slots or ender eye to add 9 slots, max size is 27( normal chest size).
it will probably fix at max size.
it is the quark sorting system but it's not a bug, a compatibility patch is needed.

**Comment by ShetiPhian** [comment]
Looks like the buttons align above slot 9 by default.
(Didn't they render on the left side of the gui before?)

Just looked into the Quark GitHub, the API's don't have anything for button location, only disabling. I'll take a peak at the code to see if there is a reference so something I can set.

**Comment by ShetiPhian** [comment]
Yep its based on the 9th slot (index 8)

Without a getRowSize or getTopRightSlot method, the only thing I could do is disable Quark's buttons from appearing.

**Comment by ArMoReDfUrY** [comment]
disabling the buttons until max capacity would be totally fine for me as i won't be doing much sorting of the ender chest. i prefer to have an ender pouch with me on trips to other dimensions or while mining large quantities of ore, and setup a hopper under the chest and pull items into a sorting system or temporary chest stack.
your chests do work with hoppers still i hope :)

**Comment by BedrockLegends** [comment]
@ShetiPhian I am also noticing when I click on a Ender chest with an Emerald, it tells me I am not on a team. I have FTB Teams installed and have a team through that

**Comment by ShetiPhian** [comment]
Only the scoreboard team system is currently supported, I haven't yet re-implemented mod integrations.
