### ISSUE TITLE
Mod not working properly

### ISSUE THREAD

**Issue by CynicalDrew** [ShetiPhian/Localizations-and-Issues#24]
I have just installed the mod and it allows me to put the items in my inventory, however, it will not let me place anything it instantly disappears. Any ideas as what the issue is?

**Comment by ShetiPhian** [comment]
If your on a server or lan world, its most likely spawn protection.

If this is not the case I need to know what mod version your using, what item(s) is/are causing the trouble and if anything appears in the console/log.

**Comment by CynicalDrew** [comment]
I'm pretty sure I am not on a LAN world. The server is run directly on my machine I do have friends join as well. It is all items that are in the mod I cannot place down. I am using the 1.11 version and nothing appears in the console log.

**Comment by ShetiPhian** [comment]
Well if your not in spawn protection and its only my blocks with the issue there would be some sort of mod conflict.

When you try to place the block and it disappears, did you get the item back? You may need to log out and back in to see it.
If you got your item back then something is stopping the placement serverside. If you don't get the item back something removed the block after it was placed.
Both can be done with events added by forge, if someone screwed up it should be effecting most blocks, but if its just mine someone is screwing with me.

I need your full mod list, include mod name and mod version.
Rather then type them out you can copy and paste the jar file names or just send me the fml-client-latest.log via pastebin or download

**Comment by CynicalDrew** [comment]
The item would not return to my inventory. I tried running the mod by itself and same result.
The mods are
multistorage-1.11.0-1.3.1
shetiphiancore-1.11.0-3.4.1

**Comment by ShetiPhian** [comment]
I thought you had more mods, turns out this is an issue with Forge
You need to drop back to forge-1.11-13.19.1.2196
2197 and 2198 wont launch and 2199 is causing this bug.

Looks like you could also go to 1.11.2 as forge-1.11.2-13.20.0.2204 didn't have this bug.

**Comment by CynicalDrew** [comment]
ok thank you so much for the help! ill try it out
