### ISSUE TITLE
[1.15.2] FTBTeams don't work with emerald upgrade

### ISSUE THREAD

**Issue by Kinishina** [ShetiPhian/Localizations-and-Issues#241]
Hi. Could you please check why EnderChests and EnderTanks don't work with FTBTeams on the latest version? Vanilla /team working just fine but it require permissions and not ideal for my server use. Thanks!
Minecraft 1.15.2, ftb-teams-1.0.0.5, enderchests-1.15-1.6.0, endertanks-1.15-1.8.0.

**Comment by ShetiPhian** [comment]
Integration with other mods is not yet updated.
Currently scoreboard teams is the only one supported.

I'll post here when I update the core.

**Comment by ShetiPhian** [comment]
Please provide a link to FTB Teams.
Google is not returning any result and all of FTB's mods on Curse are 1.12

**Comment by Kinishina** [comment]
Sure, you can download everything here, this is the official source at that moment [https://jenkins.latmod.com/downloadlinks/](https://jenkins.latmod.com/downloadlinks/)
Links to GitHub, Discord and everything else are on the main site page [https://latmod.com/](https://latmod.com/) if you ever will need to contact LatvianModder.
FTB mods moved to live on their own, but still have agreement with Curse, thus modpack creators can include and use them freely.

**Comment by ShetiPhian** [comment]
Thank you.

New builds are now up.
Only ShetiPhianCore is needed to enable FTBTeams.
EnderChests/Tanks have updates that correct the displayed owner format, and add extra hud data to one probe.
