### ISSUE TITLE
[1.15.2] Suggestion 

### ISSUE THREAD

**Issue by BedrockLegends** [ShetiPhian/Localizations-and-Issues#242]
I am noticing your Ender Chests dont use the tag system, Could you add them to tag:forge:chests and tag:forge:chests/ender to allow mod compatibility with other mod recipes

**Comment by ShetiPhian** [comment]
Added to newest builds
https://www.curseforge.com/minecraft/mc-mods/enderchests/files

Also created a similar tag for tanks, and added my endertanks to it
https://www.curseforge.com/minecraft/mc-mods/endertanks/files
