### ISSUE TITLE
[1.15.2] Suggestions: Limit usage of capacity upgrades

### ISSUE THREAD

**Issue by TheUntamed** [ShetiPhian/Localizations-and-Issues#244]
Hi, could you add an option that limits the amount of times each capacity upgrade item can be used to 1.
Right now it is possible to set a list of items (e.g. small_capacity = ["minecraft:ender_pearl", ...]) that can be used to upgrade the amount of slots. This also allows to use the same item multiple times until the max slots are reached.
The new limit option would only allow each item to be used once which forces the player to use different items of the defined list.

**Comment by ShetiPhian** [comment]
Added to the newest builds
https://www.curseforge.com/minecraft/mc-mods/enderchests/files
https://www.curseforge.com/minecraft/mc-mods/endertanks/files

In the configs you can define a list of items or tags (all items in a tag can be used once)
