### ISSUE TITLE
[1.15.2 server crash] I just tried to open platformer

### ISSUE THREAD

**Issue by FuryOfFools** [ShetiPhian/Localizations-and-Issues#246]
[crash-2020-08-09_11.03.33-server.txt](https://github.com/ShetiPhian/Localizations-and-Issues/files/5046838/crash-2020-08-09_11.03.33-server.txt)

**Comment by ShetiPhian** [comment]
Should be fixed in the builds just uploaded.
https://www.curseforge.com/minecraft/mc-mods/platforms/files
