### ISSUE TITLE
[Platforms][1.15.2][1.6.1] Rendering Issues with Ramps with PBR Resource Packs

### ISSUE THREAD

**Issue by wchen1990** [ShetiPhian/Localizations-and-Issues#248]
Here's a [link](https://i.imgur.com/pWaFD1h.mp4) showing off the issue.

I'm currently using [OptiFine 1.15.2 HD U G1 pre30](https://optifine.net/downloads), [Sildurs Vibrant Shaders v1.27 Extreme-VL](https://sildurs-shaders.github.io/downloads/), and the [Vanilla PBR](https://www.curseforge.com/minecraft/texture-packs/vanilla-pbr) resource pack. For the most part everything plays nicely with the resource pack except for the ramps. This issue doesn't happen if I'm not using Vanilla PBR, but it'd be nice if it was compatible.

Hopefully, this isn't that hard to fix, but I understand if this use case is pretty niche and not worth the time.

The settings for Sildur's to use the resource pack would be to set the mapping to Parallax and the RP Resolution to >= 128.

**Comment by ShetiPhian** [comment]
This looks like it might be related to the bug in the Forge lighting pipeline that results in incorrect shading on obj models.
In the the Forge config file try setting experimentalForgeLightingPipelineEnabled to true

**Comment by wchen1990** [comment]
Tried setting the experimentalForgeLightingPipelineEnabled to true in the
forge-client.toml file. Unfortunately, it didn't resolve the issue.

I wonder if the issue is that with the Parallax option set in Sildur's and
the way it was modeled it might be looking at textures past the intended
bounding box. Not sure why that would only apply to Ramps though, since all
the other blocks work perfectly fine with the resource pack.

**Comment by ShetiPhian** [comment]
Good point, shading is monochromatic, and that does appear to be other textures.
Only the slanted part of the ramp is an OBJ (and the ramps hand rail), everything else uses json models.
Doodads from Terraqueous would like have the same issue as they also use OBJ models. (or maybe not as they are stand alone and not baked with json models to create the final model)

Can't be an issue with the OBJ model itself, as if the faces where off the shape would be incorrect and if the texture mapping was out of bounds Forge fails to load the model.
That leaves an incompatibility with Forges OBJ models or with my merged model.

**Comment by wchen1990** [comment]
Didn't have Terraqueous installed but checked to see if I had a similar issue with the Doodads. The stone and bone Doodads seem to be fine. The stick one on the other hand only has one face with the issue. Here's a [link](https://i.imgur.com/Rg5ya03.mp4) showing the three.

**Comment by wchen1990** [comment]
Apologies, but I did some sleuthing in the mod files (not sure about your policy on that so, sorry about that), and I get the feeling the issue might be the UV Mapping of the OBJ file along with the extra triangles present in the model.

**Comment by ShetiPhian** [comment]
I think it is a similar issue to the shading one.
The reason shading is messed up is due to the vertex order.
Minecraft expects them to be in a specific order starting with the top-left, but the OBJ loader doesn't always generate the list this way.
gigaherz does the rendering stuff for Forge and was looking into changing the loader to accommodate this requirement.

I thought maybe I could reorder them in the models, but looking at the StormForge caps it appears that rotating the models would mess them up again.

**Comment by wchen1990** [comment]
Oh, I didn't know about that but that's interesting.

I looked at what Blender outputted when I modified the ramp's middle.obj file and compared it to the unmodified one and the ordering does seem different. I'm hesitant on uploading the file that I modified since it's your code after all and it doesn't seem like Platforms has an open source repository.

But, in my modified obj there's less face value lines but each of them now have four values and all of the vertices, etc are grouped together. With all of the v values declared first followed by, vt, vn, and then the f values.

Let me know if there's some way for me to send you the file directly if you want to see the differences between the original and the one I modified.

**Comment by wchen1990** [comment]
So after modifying more of obj files to get ride of any split triangle faces, I think the issue is how Minecraft deals with triangles. I actually disabled my resource pack to make sure my modifications didn't break anything in Vanilla and here are the comparisons.

[This is how the default obj's in Platforms looks like](https://i.imgur.com/kcNNv1q.png) and [this is how it looks like after I modified the obj for that block](https://i.imgur.com/elYOcuE.png). While the latter may look better there is still an issue in how it displays textures on the face and I feel like it's definitely an issue with how textures are applied on non-rectangular objects.

Hopefully this helpful to you.

**Comment by ShetiPhian** [comment]
Interesting;
At one time OBJs could only have triangles as the loader would crash with a too many vertices error. Never tried anything else after that, all new models where just done with triangles.

Fruztrated makes the OBJ models for me (and most textures) I'll have to let him know.
As for the distorted textures, I've seen that happen on a model he just finished, not sure how it was fixed.

**Comment by wchen1990** [comment]
I already modified all of the OBJ files and merged the triangle faces on my end. Let me know if you guys want the modified files. But, it should be fairly quick to do on your end, albeit tedious.

**Comment by ShetiPhian** [comment]
Fruztrated has the blender files prior to converting to triangles (its an export setting) and wants to see about fixing the texture distortion issue.

And that brings me to a snag. I haven't use Optifine since 1.6 or 1.7
When its added my custom models do not load. (All platforms, beds, and tree leaves are just the missing models)
Enabling the shader doesn't fix it (but kills my tile entity renders, thus EnderChests and EnderTable render wrong)

What setting did you change to get the platform models to load?

**Comment by wchen1990** [comment]
That's odd...

I had some rendering issues when I load the mod but reloading the Resource Pack with F3+T fixed the missing texture issues for me. Not entirely sure why that happens though. Let me see if I can reproduce it to show you. For now here's my settings for everything while I was testing out Platforms.

[optionsof.txt](https://github.com/ShetiPhian/Localizations-and-Issues/files/5107328/optionsof.txt)
[optionsshaders.txt](https://github.com/ShetiPhian/Localizations-and-Issues/files/5107329/optionsshaders.txt)
[options.txt](https://github.com/ShetiPhian/Localizations-and-Issues/files/5107330/options.txt)

These are the mods in my mods folder at the moment:
shetiphiancore-1.15-3.7.4.jar
platforms-1.15-1.6.1.jar
preview_OptiFine_1.15.2_HD_U_G1_pre30.jar

The forge version I'm using at the moment is forge-1.15.2-31.2.31.

**Comment by ShetiPhian** [comment]
Turns out there is a difference between Optifine rendering between 1.15 and 1.16
In 1.15.2 they cause _"forge:multi-layer"_ and _"terraqueous:multi-layer"_ to not render at all
In 1.16 they fixed _"forge:multi-layer"_ but now _"terraqueous:multi-layer"_, _"platforms:platform"_, _"multibeds:bed"_, and _"multibeds:ladder"_ display the missing model.

As for the distorted textures, I'm doubting it can be fixed. Custom embroidery art applied and banners applied to the beds are distorted bad enough to be unrecognizable. (it also breaks Minecraft chests and enchanting table, so fixing my table and chest wouldn't be possible)

Anyhow Fruzstrated now has a test environment, if nothing else we can reduce the number of faces our models use as we are no longer restricted to triangles.

**Comment by ShetiPhian** [comment]
Fruzstrateds findings:
The texture distortions can not be worked around, some shaders will only support squares, rectangles, rhombi and parallelograms; not even other four vertex shapes like a isosceles trapezoid work, they twist the texture and triangles strangely stretch the texture in one direction.

Some errors in the models where found also, some parts where still only their alignment shape and not extruded completely, a couple of missing faces, and a few parts completely missing and needs models and code to support it.

**Comment by wchen1990** [comment]
Unfortunately, it does seem like with a lot of shaders. I've opened an issue with Sildur's author and hopefully I'll get a response to see if it's plausible for them to address the issue. I imagine they're all working based off of a common implementation of the Parallax Occlusion Mapping (POM) formula which doesn't support certain shapes and makes assumptions of how faces would be shaped.

Thanks for for the update and looking into the matter. The best solution I've found so far is to decrease the POM Depth to a smaller number so that the issue is as severe.

Also, I don't think I've said this yet, but I think Platforms is a fantastic mod. You made it in such a way that the player can just mix and match textures for basically any block, even modded ones.

**Comment by ShetiPhian** [comment]
It would have been nice to fully correct the issue, :/
The new builds are now up, thank you for the help. (Fruzstrated is already cleaning up the models for our other mods also)

https://www.curseforge.com/minecraft/mc-mods/platforms/files/all
