### ISSUE TITLE
Known Issues when OptiFine is present

### ISSUE THREAD

**Issue by ShetiPhian** [ShetiPhian/Localizations-and-Issues#249]
**Mod:** MultiBeds and Platforms
**Version:** All
**Issue:** Models do not load (purple and black cube)
**Cause:** OptiFine breaks mod added model loaders
**Fix/Workaround:** Install OptiForge

---
**Mod:** Terraqueous
**Version:** All
**Issue:** Can't enable/disable shaders
**Cause:** OptiFine does not fully support Forges OBJ loader and does not reload the models correctly
**Fix/Workaround:** From the main tile screen, enable/disable your shader, then relaunch Minecraft.
You can change shaders and options without a restart, but must relaunch the game to disable or enable shaders

---
~~**Mod:** Terraqueous
**Version:** 1.15
**Issue:** Burnium Ore, Endimium Ore, and Leaves are invisible / broken models
**Cause:** OptiFine breaks Forges multilayer model, and my multilayer model (with is based off of Forges)
**Fix/Workaround:** No known fix or workaround~~
_Terraqueous-1.15-1.6.2 has a workaround_

---
**Mod:** Terraqueous
**Version:** 1.16.2
**Issue:** World generation is broken, not even vanilla trees, flowers, grass, etc generate
**Cause:** No clue. OptiFine changed something between pre2 and pre3 that is causing this incompatibility.
**Fix/Workaround:** ~~Revert back to OptiFine_1.16.2_HD_U_G3_pre2~~ Looks to be fixed in OptiFine_1.16.2_HD_U_G3

---
**Mod:** MultiBeds and Platforms
**Version:** 1.16.2 (maybe others)
**Issue:** "OpenGL error: 1281 (Invalid value), at: Expand VBO"
**Cause:** Unknown
**Fix/Workaround:** Disable Render Regions (options > video settings > performance)

**Comment by GradiusLover2000** [comment]
"You can change shaders and options without a restart, but must relaunch the game to disable or enable shaders"

As of version 1.16.2 G3, this is incorrect, clicking "OFF" in the shaders menu successfully unloads all shaders and reloads default minecraft resources.
