### ISSUE TITLE
[Platforms][1.16.1][1.7.0] Server Crashes When Using Platformer

### ISSUE THREAD

**Issue by fidelitousone** [ShetiPhian/Localizations-and-Issues#250]
[Crash Report](https://pastebin.com/f1034gWT)

**Comment by ShetiPhian** [comment]
Did this crash only happen once? or is it happening frequently?
Are there steps that reproduce it?

I don't know the cause of the crash.
The line numbers in the report have to be off as "Entity.java:206" can't produce a null pointer error.
Tracing from my code into Mojangs ends up in the same method, and looking at all the lines in it only 203 could cause a null pointer, but the only way for that variable to be null is if the tile entity is ticking before the game fully loads (impossible as the world wouldn't have loaded thus no tile entity) or if my entity was removed from the registry (something I have no control of, and should never happen)

**Comment by ShetiPhian** [comment]
The only thing I could think of was the possibility of the tile entity being ticked before its world object is set.

New builds are up, but you'll have to change to 1.16.2
(I only keep one environment per Minecraft version and had already migrated to 1.16.2)
https://www.curseforge.com/minecraft/mc-mods/platforms/files/all
