### ISSUE TITLE
MultiBeds Compatibility issues with Structurize

### ISSUE THREAD

**Issue by Mysteriaa** [ShetiPhian/Localizations-and-Issues#251]
I ran into this issue last night when attempting to move houses to a different world with the Structurize mod due to a major glitch. I was told that MultiBeds was causing the crash.

Here's the original issue, with the crash log included within. https://github.com/ldtteam/minecolonies/issues/5679

**Comment by ShetiPhian** [comment]
The server side TileEntity is on the client. my guess is through the TileEntityType.
While using one of the blocks create tile entity methods work, it appears like the type's create would cause this.

I'll look into simplifying my tiles, by removing the need for a server and client version. Just need to finish up what I'm working on now.

**Comment by ShetiPhian** [comment]
Now I remember why I split the tile. Many client only methods would need to be error checked an redirected.
I've altered the way my tile entities are initialized, everything goes through the TileEntityType create method, which should now be smart enough to create the client tile on the client.

Here is a test build, let me know if it fixes the compatibility issue.
http://www.mediafire.com/file/jf77n1nlirru0b7/file
