### ISSUE TITLE
Flowers don't drop when broken

### ISSUE THREAD

**Issue by 4ilur0phile** [ShetiPhian/Localizations-and-Issues#252]
I'm using minecraft version 1.15.2. When I break most of the flowers, they don't drop themselves. I can only get the trickster blooms.

I don't know which mod might be interfering, but here's the list of what I have installed:

Absent by Design
Artifacts
AutoRegLib
BasseBombeCraft
Better Mineshafts
Cactus Juice
Charm
Compact Ores
CraftingAutomat
Curios
Cyclic
Disenchanting
DoubleDoors
Ender Compass
Falling Tree
forgeautofish
futuremc
gemsnjewels
getinthebucketmod
guard villagers
janoeo
JEI
JEI Enchantment Info
Just Needed
Kotlin
More MobGriefing Options
MyCommands
Neat
no-nitwits
No Increasing Repair Cost
packing tape
Quark
randomite
Ring of Attraction
Ring of Growth
Ring of the Miner
Ring of Repair
ShetiPhian Core
Terraqueous
Xaero's Minimap

**Comment by ShetiPhian** [comment]
Not a mod conflict, I appear to have forgotten to make loot tables for the other flowers.
Trickster bloom was the first flower done, the rest where copies with the needed data changed, but I missed the loot tables.

Have you ran into any other blocks with no/wrong drops?

**Comment by 4ilur0phile** [comment]
> Not a mod conflict, I appear to have forgotten to make loot tables for the other flowers.
> Trickster bloom was the first flower done, the rest where copies with the needed data changed, but I missed the loot tables.
> 
> Have you ran into any other blocks with no/wrong drops?

I'm not aware of any other problems right now, the flowers were just the main thing for me.

**Comment by ShetiPhian** [comment]
I think I made this resource pack correctly.
http://www.mediafire.com/file/r7kakxmek3dbek6/file

That should fix drops until the next build.

**Comment by 4ilur0phile** [comment]
> I think I made this resource pack correctly.
> http://www.mediafire.com/file/r7kakxmek3dbek6/file
> 
> That should fix drops until the next build.

I tried it both zipped and unzipped and unfortunately it doesn't work. I'll just wait for the next build, it's not a major issue.

**Comment by ShetiPhian** [comment]
The new builds have the missing loot tables.
https://www.curseforge.com/minecraft/mc-mods/terraqueous/files/all

**Comment by glindsey** [comment]
I hate to ask this, but is there any way you can backport this fix to 1.16.1? My daughter and I are running that on a server since a lot of mods haven’t been updated to the new worldgen code in 1.16.2, and it would be really nice to be able to pick the flowers. But if you can’t, no big deal!

**Comment by ShetiPhian** [comment]
I can't compile a 1.16.1 build, but that doesn't make the fix impossible.

I've restored the data pack (http://www.mediafire.com/file/r7kakxmek3dbek6/file)
The issue of it not working before was due the using the wrong folder.
As it turns out when adding loot tables you don't add them to the 'resourcepacks' folder. You have to use the per world 'datapacks' folder (/saves/<WorldName>/datapacks/)

**Comment by glindsey** [comment]
Thanks so much!
