### ISSUE TITLE
[Platforms][1.15.2][1.6.2] Missing Textures for some models

### ISSUE THREAD

**Issue by wchen1990** [ShetiPhian/Localizations-and-Issues#254]
Was testing the newest release of Platforms and noticed a small issue with two models:

[Left Ramp](https://i.imgur.com/79ytLa0.png)
[Right Ramp](https://i.imgur.com/fqo6qNv.png)

Let me know if you need more information.

**Comment by ShetiPhian** [comment]
Got the repaired models from Fruzstrated.
I'll upload a 'b' build shortly, just need to apply the fix and compile.

**Comment by ShetiPhian** [comment]
New builds are up.
https://www.curseforge.com/minecraft/mc-mods/platforms/files
