### ISSUE TITLE
Ender Tanks Cannot Be Upgraded

### ISSUE THREAD

**Issue by Gluton-Official** [ShetiPhian/Localizations-and-Issues#256]
Version: 1.9.0 (Minecraft 1.16.1, Forge 32.0.108, singleplayer, config unedited)

Shift + right clicking an Ender Pearl, Eye of Ender, or Piston onto an Ender Tank does not upgrade the tank's storage or pump speed.

Tank orientation, lock, color, and gamemode do not affect this.

Mod list:		
Abnormals Core 			2.0.3
Absent By Design 		1.1.0
Additional Bars			1.5.1
Advanced Hook Launchers		6.0.0.0-build.0006
AI Improvements			0.3.0
AIOT Botania			1.3
Angel Ring			1.3.1
Apotheosis			4.1.3
AppleSkin			1.0.14
Applied Energistics 2		8.0.0-beta.2
Atomospheric			2.0.0
Infernal Mobs			1.16.1.2
AutoRegLib			1.6-43
Back Tools			9.0.0
Bad Wither No Cookie Reloaded	3.8.15
Basic Nether Ores		5.1.0
Biomes O' Plenty		11.0.0.395
Bookshelf			6.3.20
Botania				1.16.1-403
Botany Pots			3.0.6
Building Gadgets		3.5.1
Caelus API			2.0-beta7
Camera Mod			1.0.7
CC: Tweaked			1.90.3
Click Machine			4.0.0
Cloth Config API		4.0.2
Clumps				6.0.0.8
Comforts			3.0.0.1
Compressium			1.0.24
Controlling			7.0.0.3
Cooking for Blockheads		9.0.2
Cosmetic Armor Reworked		1.16.1-v1b
Crafting Station		4.0.0a
Crafting Tweaks			12.0.4
CraftTweaker			7.0.0.23
Cucumber Library		4.0.2
Curio of Undying		4.0
Curios API			3.0.0.2
Curious Elytra			3.0
Cyclic				0.6.1
Dank Storage			3.8
Dark Utilities			4.0.3
Default Options			12.0.1
Ding				1.1.0
Double Slabs			3.3.3
Dungeon Crawl			2.0.2
Dungeons Plus			1.0.2
Enchantment Descriptions	3.0.2
End: Reborn			0.7.5
EnderChests			1.7.0
EnderTanks			1.9.0
Essentials			2.8.4
Extended Caves			2.3
Extended Lights			3.0
Extra Disks			1.3.1
Farming for Blockheads		7.0.2
Fast Leaf Decay			v23
FastFurnace			4.1.2
FastWorkbench			4.2.0
FindMe				2.0.0.0
ForgeEndertech			7.0.1.0-build.0008
FTB Backups			2.1.1.6
FTB Ranks			1.0.0.7
FTB Teams			1.0.1.12
Giselbaer's Durability Viewer	1.8.3
Global Data- & Resourcepacks	1.4.2
GraveStone Mod			1.0.6
iChunUtil			9.0.0
Immersive Engineering		4.0.0-118
Immersive Portals		0.2
Industrial Foregoing		3.0.5-7e692e4
Initial Inventory		5.0.1.3
Inspirations			1.2.0
Inventory Sorter		18.0.0
Iron Chests			11.0.4
ItemZoom			2.2.0
JEI Enchantment Info		1.2.0
JEI Integration			4.0.0.4
JEITweaker			1.0.1.2
Just Enough Items		7.0.1.10
Just Enough JER			0.11.1.96
KleeSlabs			9.0.0
Large Fluid Tank		16.0.2
Light Overlay			5.4.2
Lightest Lamps			4.0.3
Lollipop			3.0.0
Long Fall Boots			1.5.0a
Ma Enchants			3.2.1
Ma Essentials			3.2.5
Macaw's Windows			v1.0.2
Mantle				1.6.27
Mekanism			10.0.9.432
Mekanism Additions		10.0.9.432
Mekanism Generators		10.0.9.432
Mekanism Tools			10.0.9.432
Mining Gadgets			1.4.1
More Dragon Eggs		1.4
Morpheus			4.2.55
Mouse Tweaks			2.13
Moving Elevator			1.2.20
MrCrayfish's Furniture Mod	7.0.0-pre18
MultiBeds			1.7.0
Mystical Agradditions		4.0.0
Mystical Agriculture		4.0.2
Nature's Compass		1.8.5
Neat				1.7-23
NetherPortalFix			7.0.1
Oh The Biomes You'll Go		1.0.16
OpenBlocks Elevator		1.7.3
Overloaded Armor Bar		5.0.0
Packing Tape			0.9.6
Pam's HarvestCraft - Food Core	1.0.5
Pane In The Glass		1.3.0
Patchouli			1.16-39
Pedestals			0.8
Petrock				0.7.1
Placebo				4.1.3
PneumaticCraft: Repressurized	2.1.1-14
Polymorph			0.13
Powah!				2.2.0
Quark				r2.2-262
RandomPatches			1.22.1.1
Ranged Pumps			0.8
Reap Mod			1.0.2
ReAuth				3.9.0
Refined Storage			1.9.2
Refined Storage Addons		0.7
Runelic				1.0.6
Scalable Cat's Force		2.13.2-build-2
ShetiPhianCore			3.8.0
SignEdit			1.16.1-1
Simple Storage Network		1.0.0
Simply Jetpacks 2		2.6.2.2
Simply Light			1.0.2
Sit				v1.3
Spice of Life: Carrot Edition	1.9.7
Storage Drawers			8.1.0
Strucutre Gel API		1.2.1
SwingThroughGrass		1.5.1
TellMe				0.8.1
Tesseract			1.0.12
The Endergetic Expansion	2.0.0
The One Probe			3.0.1-beta
Tinkers' Mechworks		2.2.1
Titanium			3.0.4
Torcherino			11.0.2
Torchmaster			2.3.2-alpha
Towers Of The Wild		1.2.2
Trample Stopper			2.0.0.5
Trash Cans			1.0.3
TrashSlot			12.0.1
U Team Core			3.1.3.170
Uppers				0.3.0
Useful Backpacks		1.11.3.78
Valhelsia Structures		16.0.2
Waddles				0.8.7
Waystones			7.1.1
Wither Skeleton Tweaks		5.0.0
Xaero's Minimap			20.20.1
Xaero's World Map		1.10.1
YUNG's Better Mineshafts	1.3

**Comment by ShetiPhian** [comment]
Ender Pearl, and Eye of Ender are working here, Pistons however are not. (due to my oversight, blocks are force placed while sneaking causing  the block clicked code not to trigger)
I'll need to make code changes to support items that have a sneak+right-click action.

As for the others, here is a few things to check/try
- Has a mod replaced the items? with advanced tooltips on (F3+H) check that their registry names are correct ("minecraft:ender_pearl" and "minecraft:ender_eye") [If the names are different you'll need to change the config entries]
- Verify the config has entries for 'upgrade_items' > 'large_capacity' and 'small_capacity' [if they are missing try adding them]
- Try different items by changing 'large_capacity' and 'small_capacity'
