### ISSUE TITLE
Silverfish iron drop rate

### ISSUE THREAD

**Issue by xenoflot** [ShetiPhian/Localizations-and-Issues#26]
Hi,

Is it Terraqueous that results in silverfish dropping iron ingots and extra leather on cows, etc.? If so, folks on my server feel the drop rates are far too high. 

Would you please make these configurable? Ideally it would be nice to specify what additional items are dropped and a scaling factor.

For example:

I'd set silverfish to drop 1-3 silver nuggets instead of 1-3 iron ingots.

I'd scale down the leather drops on cows to much less than they currently are :)

Thanks!

**Comment by ShetiPhian** [comment]
Not sure what mod adds those but its not me.

My changes:
- chickens randomly molt feathers
- killing a mob with my scythe has a higher chance to drop its head
- extra death drops:
-- zombies = worn leather items
-- blazes, zombie pigmen, and magma cubes = burnium dust and coal dust
-- endermen = endimium dust and ender dust

I also add the branches, stones, and fossles that are found laying around.
The branches drop sticks, fossils drop bonemeal, and the stones drop anything registered as a dust but is configurable with the options under 'tweaks-doodads'

**Comment by xenoflot** [comment]
Fabbo thanks. I'll keep searching then!

A parting suggestion, add details of those changing into the config file so that folks can see what your mod does.

Cheers!

**Comment by WesCook** [comment]
>extra death drops:
>-- zombies = worn leather items

Ah, I've been trying to track down where these leather pieces kept coming from.  I searched through the loot tables but couldn't find them.

Do they serve any use?  I added a recipe to harvest them with a knife for spare leather, but I can't work out what they're actually for.

To be honest I wouldn't mind disabling them, if only to reduce the amount of clutter gained adventuring and mob farms.

**Comment by ShetiPhian** [comment]
@xenoflot 
I added your suggestion.

New build is up on Curse (well under review as I type), you'll need the newest core as well.
Change log snip-it
- Expanded MobDropTweaks config into its own sub category with individual control over each mob

@WesCook 
Your not missing anything, the worn leather items are only used to make scraps, and the scraps are only used to make leather.
These can be disabled in the newest build.
