### ISSUE TITLE
Crash with forge 33.0.59

### ISSUE THREAD

**Issue by MeinKraft** [ShetiPhian/Localizations-and-Issues#262]
shetiphiancore-1.16-3.8.1.jar
Forge 33.0.59
Minecraft 1.16.2

When adding this mod to my modpack the game hard crashes with "Exit Code 0"
The only log I have is [latest.log](https://pastebin.com/tPFLSRWr)

I only have 12 mods (10 not including EnderTanks/EnderChests), and they all load when shetiphiancore is removed

Running forge with just ShetiphianCore and EnderTanks/Chests works fine tho - So Im not sure whats happening

Mods im using:
aiotbotania-1.16.2-1.3.1
Botania-1.16.2-406
curios-forge-1.16.2-4.0.0.1
gardenofglass-1.5
jei-1.16.2-7.3.2.25
Patchouli-1.16-42
refinedstorage-1.9.5
refinedstorageaddons-0.7.1
StorageDrawers-1.16.2-8.1.0

**Comment by ShetiPhian** [comment]
I don't know either.

Its a Mixin crash, but I don't use mixin, Vazkii does for the asm in Botania and Patchouli.
My guess is its a conflict with their mixin asm, and my asm that uses the java script one provided by Forge.
But even if that was confirmed to be the case I still wouldn't know if its something I could solve.

I'll upload my asm files here, maybe someone more versed in them can see the issue and offer a fix.

**Comment by ShetiPhian** [comment]
Another thought, the asm in ShetiPhianCore can safely be disabled. I believe there is a command line flag in Forge to do this, just haven't found it yet.

**Comment by son0fether** [comment]
I confirm this is still a problem for the following:
Minecraft: 1.16.2
Forge: 33.0.61

Minimal repro case (fresh profile in Twitch, add fresh versions of these mods):
Mods:
  | Botania | Vazkii | Botania-1.16.2-406.jar |  
  | Curios API (Forge) | TheIllusiveC4 | curios-forge-1.16.2-4.0.0.1.jar |  
  | EnderChests | ShetiPhian | enderchests-1.16-1.7.2.jar |  
  | EnderTanks | ShetiPhian | endertanks-1.16-1.9.2.jar |  
  | Patchouli | Vazkii | Patchouli-1.16-42.jar |  
  | ShetiPhianCore | ShetiPhian | shetiphiancore-1.16-3.8.1.jar |

Results in the "Re-entrance detected..." crash.

**Comment by ShetiPhian** [comment]
Just tested an idea.
I dropped back to Forge 33.0.23 and it works
So something Forge changed between 23 and 59 broke compatibility between their system and Mixin

**Comment by ShetiPhian** [comment]
Up to 33.0.34 works
33.0.35 Crashed: ClassCastException
33.0.36 and 33.0.37 work
33.0.40 Crashed: MixinInitialisationError
33.0.41 Crashed: ReEntrantTransformerError: Re-entrance error

33.0.37 Is the last build Forge Javascript asm is compatible with Mixin asm.

**Comment by ShetiPhian** [comment]
Here is a workaround build of my core.
https://www.curseforge.com/minecraft/mc-mods/shetiphiancore/files/3054960
