### ISSUE TITLE
UI does not expand beyond 27 slots for ender chest

### ISSUE THREAD

**Issue by Letoric** [ShetiPhian/Localizations-and-Issues#268]
MC 1.16.3
forge 34.1.0
Mod version 1.16-1.7.3

Reproducible by adjusting the max for chests to 54, upgrading, then opening UI.

Mod list:
09/22/2020  09:51 PM           491,390 absentbydesign-1.16.2-1.1.0.jar
09/22/2020  09:51 PM           200,191 aiotbotania-1.16.2-1.3.2.jar
09/22/2020  09:51 PM           533,524 allthemodium-1.1.1-1.16.3-34.0.8.jar
09/22/2020  09:51 PM           240,883 alltheores-0.1.7-1.16.3-34.0.8.jar
09/22/2020  09:51 PM         1,158,659 allthetweaks-1.1.3-pre1-1.16.3-34.0.8.jar
09/22/2020  09:51 PM            19,450 angelring-1.16.3-1.3.3.jar
09/22/2020  09:51 PM           703,698 Apotheosis-1.16.2-4.2.1.jar
09/22/2020  09:51 PM            29,113 AppleSkin-mc1.16.2-forge-1.0.14.jar
09/22/2020  09:51 PM         4,137,628 appliedenergistics2-8.1.0-alpha.3.jar
09/22/2020  09:51 PM           533,828 Aquaculture-1.16.3-2.1.0.jar
09/27/2020  08:59 AM         1,513,095 Ars+Nouveau-1.16.3+0.18.1.jar
09/22/2020  09:51 PM            21,146 atmadditions-1.16.2-1.0.0.jar
09/25/2020  12:51 PM             7,041 AttributeFix-1.16.3-8.0.2.jar
09/25/2020  12:51 PM             7,779 BadMobs-1.16.3-7.0.1.jar
09/22/2020  09:51 PM             5,446 balancedenchanting-1.0.jar
09/27/2020  08:58 AM            62,891 BetterAdvancements-1.16.3-0.1.0.102.jar
09/22/2020  09:51 PM           286,511 BetterMineshaftsForge-1.16.2-1.0.jar
09/24/2020  02:22 PM           201,159 Bookshelf-1.16.3-8.3.10.jar
09/22/2020  09:51 PM        14,767,790 Botania-1.16.2-406.jar
09/22/2020  09:51 PM           277,420 BotanyPots-1.16.3-5.0.1.jar
09/22/2020  09:51 PM           890,519 buildinggadgets-3.7.0.jar
09/22/2020  09:51 PM            11,400 bwncr-1.16.3-3.8.15.jar
09/24/2020  04:40 PM         6,063,463 byg-1.0.7.jar
09/22/2020  09:51 PM           200,024 camera-1.16.3-1.0.1.jar
09/22/2020  09:51 PM         1,829,235 cc-tweaked-1.16.3-1.92.0.jar
09/26/2020  08:26 PM            66,475 chonk-1.16.3-0.1.4.jar
09/22/2020  09:51 PM           378,038 citadel-1.4.0.jar
09/25/2020  12:51 PM            14,009 cleancut-mc1.16-2.2-forge.jar
09/26/2020  08:32 AM            28,826 ClientTweaks_1.16.3-5.2.0.jar
09/25/2020  12:51 PM           398,621 cloth-config-forge-4.1.0.jar
09/22/2020  09:51 PM            13,397 Clumps-6.0.0.10.jar
09/22/2020  09:51 PM           234,855 comforts-forge-1.16.2-4.0.0.0.jar
09/22/2020  09:51 PM           409,876 Compressium-1.16.3-1.0.30.jar
09/22/2020  09:51 PM           150,432 constructionwand-1.16.2-1.3.jar
09/22/2020  09:51 PM            39,092 Controlling-7.0.0.5.jar
09/26/2020  08:32 AM           656,779 CookingForBlockheads_1.16.3-9.2.1.jar
09/22/2020  09:51 PM           140,399 corpse-1.16.3-1.0.3.jar
09/22/2020  09:51 PM            84,836 CosmeticArmorReworked-1.16.3-v1.jar
09/26/2020  08:33 AM           110,838 CraftingTweaks_1.16.3-12.2.0.jar
09/22/2020  09:51 PM         2,051,725 crashutilities-3.4.jar
09/22/2020  09:51 PM           132,776 Cucumber-1.16.3-4.1.2.jar
09/22/2020  09:51 PM           230,974 curios-forge-1.16.3-4.0.2.0.jar
09/22/2020  09:51 PM         2,430,297 Cyclic-1.16.3-0.7.1.jar
09/24/2020  02:19 PM           156,774 dankstorage-3.11.jar
09/22/2020  09:51 PM           191,638 DarkUtilities-1.16.3-6.0.1.jar
09/26/2020  08:33 AM            14,936 DefaultOptions_1.16.3-12.2.0.jar
09/22/2020  09:51 PM            63,566 demagnetize-forge-1.16.2-1.2.2.jar
09/22/2020  09:51 PM           291,281 DoubleSlabs-1.16-3.4.10.jar
09/27/2020  08:58 AM           183,612 elevatorid-1.16.3-1.7.6.jar
09/25/2020  12:51 PM           103,848 EnchantmentDescriptions-1.16.2-4.0.3.jar
09/25/2020  12:51 PM           220,972 enderchests-1.16-1.7.3.jar
09/25/2020  12:51 PM           188,869 endertanks-1.16-1.9.3.jar
09/22/2020  09:51 PM         1,430,868 engineersdecor-1.16.3-1.1.2-b7.jar
09/22/2020  09:51 PM           298,909 engineerstools-1.16.3-1.1.0-b5.jar
09/22/2020  09:51 PM            80,400 entangled-1.2.7-mc1.16.3.jar
09/22/2020  09:51 PM         1,453,445 enviromats-1.16.2-2.0.3.0.jar
09/22/2020  09:51 PM           109,470 extradisks-1.16.2-1.3.2.jar
09/22/2020  09:51 PM            36,717 extremeSoundMuffler-2.1.1_Forge-1.16.2.jar
09/26/2020  08:33 AM           280,105 FarmingForBlockheads_1.16.3-7.2.0.jar
09/22/2020  09:51 PM            14,349 FastFurnace-1.16.2-4.2.0.jar
09/22/2020  09:51 PM            18,175 FastLeafDecay-v25.jar
09/22/2020  09:51 PM            32,249 FastWorkbench-1.16.2-4.3.0.jar
09/25/2020  12:19 PM         1,775,511 forbidden_arcanus-1.16.3-1.0.1.jar
09/27/2020  09:26 AM           336,544 forge-1.16.3-geckolib-2.1.1.jar
09/22/2020  09:51 PM            44,329 ftb-backups-2.1.1.6.jar
09/22/2020  09:51 PM           262,868 ftb-chunks-1.1.1.35.jar
09/22/2020  09:51 PM           404,667 ftb-gui-library-1.0.0.18.jar
09/22/2020  09:51 PM            57,269 ftb-ranks-1.0.0.7.jar
09/22/2020  09:51 PM            56,736 ftb-teams-1.0.1.12.jar
09/22/2020  09:51 PM            49,374 ftb-ultimine-1.1.0.10.jar
09/22/2020  09:51 PM            33,234 globalxp-1.16.2-v1.4.13.jar
09/26/2020  08:31 AM           181,406 gravestone-1.16.3-1.0.1.jar
09/22/2020  09:52 PM         8,699,162 ImmersiveEngineering-1.16.3-4.0.1-121.jar
09/22/2020  09:51 PM         1,506,869 industrial-foregoing-1.16.3-3.1.0-7b7cd48.jar
09/22/2020  09:51 PM            69,502 invtweaks-1.16.2-1.0.0.jar
09/22/2020  09:51 PM           205,744 ironchest-1.16.2-11.1.5.jar
09/22/2020  09:51 PM           116,759 IronJetpacks-1.16.3-4.1.1.jar
09/27/2020  09:00 AM           750,235 jei-1.16.3-7.3.2.36.jar
09/22/2020  09:51 PM            24,711 jeiintegration_1.16.3-6.0.0.8.jar
09/27/2020  08:59 AM             7,823 JEITweaker-1.16.3-1.0.1.4.jar
09/27/2020  08:58 AM           232,022 JustEnoughResources-1.16.3-0.12.0.100.jar
09/22/2020  09:51 PM           742,079 kubejs-2.8.0.65.jar
09/25/2020  12:51 PM           473,003 light-overlay-5.5.3.jar
09/22/2020  09:51 PM            45,067 LightingWand-1.16.2-1.7.0.jar
09/22/2020  09:52 PM           656,669 Lollipop-1.16.3-3.2.0.jar
09/22/2020  09:52 PM           264,887 Ma-Essentials-1.16.3-3.4.0.jar
09/22/2020  09:52 PM         2,234,715 mahoutsukai-1.16.3-v1.23.2.jar
09/24/2020  02:07 PM           550,377 mcjtylib-1.16-5.0.9.jar
09/22/2020  09:51 PM        11,585,985 Mekanism-1.16.3-10.0.9.homebaked-all.jar
09/22/2020  09:52 PM           142,803 metalbarrels-3.3a.jar
09/22/2020  09:52 PM            34,730 mining-helmet-1.16.3-1.0.8.jar
09/22/2020  09:52 PM           534,495 mininggadgets-1.6.0.jar
09/25/2020  12:51 PM         1,066,076 MixinBootstrap-1.0.4.jar
09/22/2020  09:52 PM            10,221 modnametooltip_1.16.2-1.15.0.jar
09/27/2020  06:24 PM                 0 mods.txt
09/22/2020  09:52 PM            79,829 moreoverlays-1.18.8-mc1.16.3.jar
09/22/2020  09:52 PM            23,511 Morpheus-1.16.3-4.2.59.jar
09/22/2020  09:52 PM            57,648 MouseTweaks-2.13-mc1.16.2.jar
09/22/2020  09:52 PM            95,222 MysticalAgradditions-1.16.3-4.1.0.jar
09/22/2020  09:52 PM         1,111,883 MysticalAgriculture-1.16.3-4.1.0.jar
09/22/2020  09:52 PM            34,869 MysticalCustomization-1.16.3-2.1.0.jar
09/22/2020  09:52 PM         1,284,474 NaturesAura-29.0.jar
09/24/2020  02:19 PM           197,783 NaturesCompass-1.16.3-1.8.5.jar
09/26/2020  08:33 AM           109,410 NetherPortalFix_1.16.3-7.2.0.jar
09/22/2020  09:52 PM           525,883 PackMenu-1.16.2-2.2.0.jar
09/22/2020  09:52 PM           568,429 Patchouli-1.16.2-44.jar
09/26/2020  08:34 AM           186,991 PickleTweaks-1.16.3-5.1.2.jar
09/22/2020  09:52 PM            95,537 Placebo-1.16.2-4.2.0.jar
09/22/2020  09:52 PM           515,216 platforms-1.16-1.7.4.jar
09/25/2020  12:20 PM         6,580,046 pneumaticcraft-repressurized-1.16.3-2.4.1-44.jar
09/22/2020  09:52 PM            83,352 polymorph-forge-1.16.2-0.14.jar
09/22/2020  09:52 PM           343,749 potionsmaster-0.1.21-1.16.3-34.0.9.jar
09/22/2020  09:52 PM         1,155,136 Powah-1.16.3-2.3.0.jar
09/22/2020  09:52 PM           209,595 randompatches-1.16.2-1.22.1.2.jar
09/25/2020  05:03 PM            26,035 rangedpumps-0.8.2.jar
09/22/2020  09:52 PM         5,721,175 rats-6.1.0-1.16.3.jar
09/22/2020  09:52 PM            34,757 ReAuth-1.16-Forge-3.9.1.jar
09/25/2020  05:03 PM         3,119,019 refinedstorage-1.9.6.jar
09/25/2020  05:03 PM            30,061 refinedstorageaddons-0.7.2.jar
09/24/2020  02:14 PM            46,429 restrictions-1.16-3.0.3.jar
09/24/2020  02:12 PM           382,382 rftoolsbase-1.16-2.0.5.jar
09/24/2020  02:07 PM           506,746 rftoolsbuilder-1.16-3.0.6.jar
09/24/2020  02:11 PM           613,581 rftoolscontrol-1.16-4.0.5.jar
09/24/2020  02:12 PM           567,290 rftoolspower-1.16-3.0.6.jar
09/24/2020  02:11 PM           341,765 rftoolsstorage-1.16-2.0.5.jar
09/24/2020  02:11 PM         1,431,623 rftoolsutility-1.16-3.0.8.jar
09/22/2020  09:52 PM           854,181 rsgauges-1.16.3-1.2.4-b8.jar
09/22/2020  09:52 PM            39,910 scuba-gear-1.16.3-1.0.1.jar
09/22/2020  09:52 PM           392,133 shetiphiancore-1.16-3.8.2.jar
09/22/2020  09:52 PM             5,571 shutupexperimentalsettings-1.0.0.jar
09/22/2020  09:52 PM            56,877 simplemagnets-1.0.8-mc1.16.3.jar
09/22/2020  09:52 PM           379,644 simplylight-1.16.3-1.0.2.jar
09/22/2020  09:52 PM           241,873 SolarFluxReborn-1.16.3-16.1.1.jar
09/22/2020  09:52 PM           487,526 StorageDrawers-1.16.2-8.1.0.jar
09/22/2020  09:52 PM           103,505 tanknull-2.1-1.16.2.jar
09/22/2020  09:52 PM            75,292 tgcropesmod-1.16.2-1.1.0.jar
09/22/2020  09:52 PM           307,396 theoneprobe-1.16-3.0.4-beta.jar
09/22/2020  09:52 PM           588,017 titanium-1.16.3-3.1.0.jar
09/22/2020  09:52 PM            23,667 ToastControl-1.16.2-4.2.0.jar
09/22/2020  09:52 PM           200,561 ToolBelt-1.16.2-1.14.4.jar
09/22/2020  09:52 PM            93,258 torchmaster-2.3.3-alpha.jar
09/22/2020  09:52 PM             6,469 TrampleStopper-2.2.0+build.1.mcVersion.1.16.3.jar
09/22/2020  09:52 PM           126,381 trashcans-1.0.3-mc1.16.3.jar
09/26/2020  08:32 AM            61,053 TrashSlot_1.16.3-12.2.0.jar
09/22/2020  09:52 PM           105,780 useful_backpacks-1.16.3-1.11.5.82.jar
09/22/2020  09:52 PM           248,037 useful_railroads-1.16.3-1.4.4.31.jar
09/22/2020  09:52 PM           460,441 u_team_core-1.16.3-3.1.9.181.jar
09/22/2020  09:52 PM         1,001,927 valkyrielib-1.16.2-3.0.3.1.jar
09/26/2020  08:33 AM           201,295 Waystones_1.16.3-7.3.0.jar
09/22/2020  09:52 PM            23,948 WitherSkeletonTweaks-1.16.3-5.1.1.jar
09/22/2020  09:52 PM           924,283 woot-1.16.2-1.0.0.0.jar
09/24/2020  02:02 PM           869,468 WorldEdit-CUI-FE3-1.16.2-3.0.7.jar
09/19/2020  10:48 PM         4,527,752 worldedit-forge-mc1.16.3-7.2.0-beta-05.jar
09/24/2020  02:09 PM           542,151 xnet-1.16-3.0.7.jar
09/22/2020  09:52 PM            11,339 xptome-1.16.2-v1.1.6.jar

**Comment by ShetiPhian** [comment]
Another mod might be trying to add information to the gui, and the way I have the data synchronized didn't make it possible for other tracked integers to be added.

Both the EnderChest size and the selection in the PlatFormer would be incorrect if another mod adds a tracked int (also what ever that int was for would never get an update)

Here is new builds that fix the above issue, let me know if it also fixes the reported bug.
http://www.mediafire.com/file/cch0ihqte7ny8r4/enderchests-1.16-1.7.4--TESTER1.jar/file
http://www.mediafire.com/file/tz67vauxkm7rxfk/platforms-1.16-1.7.5--TESTER1.jar/file

**Comment by Letoric** [comment]
The provided updates do not fix the issue for me.

**Comment by ShetiPhian** [comment]
I wanted that to be the fix as it was the most logical and didn't require knowing what the other mod is doing.

There is a faster way then one by one.
Start with just forge and my mods and verify it isn't an environment issue (I've only seen this a couple times, one was due to the java install, the other was due to the folders path)

Clear out the mod folder so its just ShetiPhianCore and EnderChests. (this is your base state, you'll return to this after each test)
Add the mods that start with A-to-M (and any needed dependencies), check for the bug.
Now you know which group the bug is in, so reset the folder, and take roughly half of that group and test again.
Each test clears roughly half of the mods, and eventually your down to the last few which can be tested one by one.
