### ISSUE TITLE
[1.16.3] java.lang.IllegalStateException: Failed to load foliage color texture 'terraqueous:textures/colormap/lightvibrant.png

### ISSUE THREAD

**Issue by ProsperCraft** [ShetiPhian/Localizations-and-Issues#269]
https://gist.github.com/ProsperCraft/2c17479bfdbcb0290ac5a912fd7c96af

[latest.log](https://github.com/ShetiPhian/Localizations-and-Issues/files/5300590/latest.log)

**Comment by ShetiPhian** [comment]
"Caused by: java.io.FileNotFoundException"
File is in the JAR
If it was a one off crash, likely just a loading glitch. (seen a mods language file not load before)
But if it happens every time something is messing up the resource loading as both initial load and reload are working.

**Comment by ProsperCraft** [comment]
Hmm, loaded fine when it was the only mod.
terraqueous-1.16-1.7.3.jar
shetiphiancore-1.16-3.8.2.jar
