### ISSUE TITLE
[1.16.3] CME dedicated server crash - at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) ~[?:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:shetiphiancore:LivingEntity.playFallSound,pl:runtimedistcleaner:A}

### ISSUE THREAD

**Issue by ProsperCraft** [ShetiPhian/Localizations-and-Issues#272]
`at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) ~[?:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:shetiphiancore:LivingEntity.playFallSound,pl:runtimedistcleaner:A}`

Dedicated server crash log-
https://gist.githubusercontent.com/ProsperCraft/e158b752a445d2f74ae2001181656462/raw/f828517ed3d8f756dbf3414f36180b866ba16097/gistfile1.txt

Another one-https://gist.githubusercontent.com/ProsperCraft/d01b6bd06bb9c1f60f4738221667aeac/raw/a688edca2f2a1346928a8ef09f254d3f61cd00f8/gistfile1.txt

forge-1.16.3-34.1.17
shetiphiancore-1.16-3.8.2
Modpack-[https://www.curseforge.com/minecraft/modpacks/towncraft](https://www.curseforge.com/minecraft/modpacks/towncraft)

**Comment by ShetiPhian** [comment]
Switch to my core that doesn't have asm. (https://www.curseforge.com/minecraft/mc-mods/shetiphiancore/files/3054960)
The Forge asm and mixin systems are not as compatible as they once where, and I don't know mixin so I can't convert my asm to it.

**Comment by ProsperCraft** [comment]
Twitch/Curseforge is being buggers about distributing that file -

![image](https://user-images.githubusercontent.com/4427684/95879418-92a96400-0d33-11eb-80c0-df78e87c66da.png)

**Comment by ShetiPhian** [comment]
I can't fix the Twitch issue, for some reason they just won't distribute anything from 'additional files' and from a past mistake I found you can not upload the same file a second time (accidentally tried uploading the same version twice)

So instead I've been looking at Mixins, if the Forge provided javascript asm is going to conflict with them and Mixins look to be the more popular choice, then I should migrate.

I've got them working in the development environment, but they don't load in a compiled runtime one. Haven't figured out how to fix that.

**Comment by ShetiPhian** [comment]
So while changing over to Mixins I noticed an oddity.

`LivingEntity.func_70071_h_` is not the method I hook into, `func_226295_cZ_` is. (also ~700 lines away from that method)


Well, my code isn't in the stacktrace, nor is the methods I inject into, so with these builds using Mixins that should rule out possible conflict.

http://www.mediafire.com/file/yj6p7co2tnejaap/shetiphiancore-1.16-3.8.3--TESTER1.jar/file
http://www.mediafire.com/file/xr5cs8s44u33ppi/terraqueous-1.16-1.7.4--TESTER2.jar/file
^ that build also has the test code for your other reported issue

**Comment by ProsperCraft** [comment]
We test in a live dedicated server environment, will the core 3.8.3 require the same version on the client?

**Comment by ShetiPhian** [comment]
I don't believe a client can connect with an out of date mod, but it shouldn't make a difference if the value change is done via ForagASM or Mixins.

Here is the same build but with its version number set to 3.8.2.
http://www.mediafire.com/file/fufvuiw9ohlxgrc/shetiphiancore-1.16-3.8.2%25283%2529--TESTER1.jar/file

Terraqueous on the other hand would require being on the clients as its dealing with resources and I changed the reload listener it was using in an attempt to fix the texture issue.

**Comment by ProsperCraft** [comment]
Seems to work great, push to curse :)

**Comment by ShetiPhian** [comment]
Now on Curse.
