### ISSUE TITLE
Crash when clicking cog in platformer gui

### ISSUE THREAD

**Issue by hibikutek** [ShetiPhian/Localizations-and-Issues#273]
Minecraft Version 1.16.3
Forge Version 34.1.25
Crashlog [here](https://pastebin.com/GZXEFxCH)

Steps to reproduce:
Crash while client was connected to dedicated server.  Place platformer block in world, open gui and click on settings cog.

**Comment by ShetiPhian** [comment]
Now that is an odd one.
When you compile a mod direct references to Minecraft code are reobfuscated.
This crash is looking for the non-obfuscated name, but this direct reference should have been processed like the rest.

Looking at the class in the decompiler I see that is the case.
IntelliJ:
```blit(matrixStack, this.buttonSave.x, this.buttonSave.y, 208, 208, this.buttonSave.getWidth(), this.buttonSave.getHeight());```
JD-GUI:
```func_238474_b_(matrixStack, this.buttonSave.field_230690_l_, this.buttonSave.field_230691_m_, 208, 208, this.buttonSave.func_230998_h_(), this.buttonSave.getHeight());```

**Comment by hibikutek** [comment]
Maybe it's a change with forge then? I've never heard of a mod crashing due to obfuscation issues!

**Comment by hibikutek** [comment]
Looking at forge changeling, perhaps it's an edit brought in this build?

```
Build: 1.16.3-34.0.6 - Tue Sep 15 19:47:08 GMT 2020
	cyborgmas18:
		Add MatrixStack-aware alternatives to the methods in GuiUtils (#7127) 
```

**Comment by ShetiPhian** [comment]
Looks to be sometime in 1.16.2
The earlier builds I'm using work but the latest has the same crash.

To maximize comparability I build on the lowest version possible, so I'll need to find when this change was made and update to it.

**Comment by ShetiPhian** [comment]
Took longer then expected.
(after updating Forge, had find and update the mappings, and correct name changes throughout code)

New builds are on Curse
https://www.curseforge.com/minecraft/mc-mods/shetiphiancore/files/3090382
https://www.curseforge.com/minecraft/mc-mods/platforms/files/3090383
