### ISSUE TITLE
Config file gets reset on minecraft startup

### ISSUE THREAD

**Issue by darkphan** [ShetiPhian/Localizations-and-Issues#276]
Changes made to the terraqueous.toml file seem to get reset every time minecraft launches. 

Terraqueous Version: terraqueous-1.16-1.7.5
Shetiphiancore Version: shetiphiancore-1.16-3.8.4
Minecraft: 1.16.3
Forge: 34.1.25

**Comment by ShetiPhian** [comment]
I'm not getting a file reset, the few I've changed have persisted.

Maybe a setting isn't loading correctly. What ones are you changing?

**Comment by darkphan** [comment]
Trying to add in a few things into the blacklists for the various doodads. The mod id one works, ie: "mod|silentgear" however trying to do a tag resets things (I must be doing the tag wrong), in a test I did "tag|silentgear:grader_catalysts"

**Comment by ShetiPhian** [comment]
I've used the same regex validator for both lists, forgetting the blacklist doesn't use the count input.
I'll need to correct that.

Adding #0 to the end looks like it will work until I get another build out.
"tag|silentgear:grader_catalysts#0"

**Comment by ShetiPhian** [comment]
Well shit, I forgot to add this to my todo list.
Other then the glance I did 9 days ago, it hasn't been looked into, thus didn't make it into the build I just released.

**Comment by ShetiPhian** [comment]
So my previous suggestion would have only solved the resetting.
An error in how I handled tags in the blacklist, resulted in it doing nothing most of the time.

This looks to be functioning, let me know it it also works for you.
http://www.mediafire.com/file/65pig692q7u2jkm/terraqueous-1.16-1.7.7--TESTER.jar/file

**Comment by ShetiPhian** [comment]
Fixed build is now on Curse
https://www.curseforge.com/minecraft/mc-mods/terraqueous/files
