### ISSUE TITLE
[1.16.3] Ender Chests, Tesselating block model crash

### ISSUE THREAD

**Issue by WhitePhant0m** [ShetiPhian/Localizations-and-Issues#278]
[Crash](https://paste.gg/p/wphant0m/0a6561e1dc7f495ab727665bc9f6c762)

enderchests-1.16-1.7.4
shetiphiancore-1.16-3.8.4
forge 34.1.25

Not sure why this crash happens, but most often it has happened to me when teleporting to my base which has the chests.
I do have OptiFine too, if that is part of the issue.

**Comment by ShetiPhian** [comment]
Unfortunately the line numbers don't line up so I'm not able to see the exact line it crashes on.
Following the code path, world being null may be the cause (possible the tile is trying to render before its world value is set)

This build checks the world variable before rendering. Let me know if that fixes it.
http://www.mediafire.com/file/2hsxjrmwiczn7hu/enderchests-1.16-1.7.5--TESTER.jar/file

**Comment by WhitePhant0m** [comment]
After testing for a couple of days, haven't encountered the crash, tho I'm not 100% sure if it's gone since it was a _random_ crash.

**Comment by ShetiPhian** [comment]
As it appears like the bug is solved, I've included the fix in the recent build.
If its still an issue, just let me know.

https://www.curseforge.com/minecraft/mc-mods/enderchests/files/3106960
