### ISSUE TITLE
Unable to make storm forge

### ISSUE THREAD

**Issue by mhjortdk** [ShetiPhian/Localizations-and-Issues#280]
In 1.16.3 I'm unable to create the storm forge. I made it in 1.15.2 with out any problems.
Also the in the nether the burnium crystals doesn't spawn.

Forge 1.16.3 - 34.1.0
Terraqueous-1.16-1.7.5
shetiphiancore-1.16-3.8.4

**Comment by ShetiPhian** [comment]
Unable to debug currently.
Does the burnium ore spawn but with no crystals on top, or does none of it spawn?

As for the storm forge, are you using the old base that uses water and glass?
If so water is now lapis, the glass touching the lapis is now redstone, and the last bit of glass is iron.

**Comment by ShetiPhian** [comment]
Just tested, StormForge can be created.
Other then the base being different the tops caps may also be different. I changed the forge to support block tags, so the tops are looking for quartz blocks where I think it use to use smooth quartz blocks.

Also I see neither the burnium ore or burnium crystals are spawning (endimium still spawns though)

**Comment by mhjortdk** [comment]
Hi, I
 just tested the StormForge as well, and that works with the new recipe, thanks.
Thanks for looking into the burnium issue too :)

**Comment by ShetiPhian** [comment]
Finally got back to the Burnium issue.
Turns out it was a simple, easily missed typo. I had used '<' where '<=' was intended, resulting in the crystals trying to generate on top of the Nether.

Just have to finish the other bugs and requests before the next release.

**Comment by ShetiPhian** [comment]
New build is in Curse:
https://www.curseforge.com/minecraft/mc-mods/terraqueous/files/3106992
