### ISSUE TITLE
1.16.3 Client crash from server side

### ISSUE THREAD

**Issue by BedrockLegends** [ShetiPhian/Localizations-and-Issues#281]
[crash-2020-11-01_18.00.37-client.txt](https://github.com/ShetiPhian/Localizations-and-Issues/files/5472067/crash-2020-11-01_18.00.37-client.txt)

**Comment by BedrockLegends** [comment]
Cause me to reset my Whole player data just to fix the issue

**Comment by Okimo** [comment]
Same Issue [Keeps crashing the client]:
java.lang.IllegalStateException: Not filled all elements of the vertex

[crash-2020-11-02_06.43.12-client.txt](https://github.com/ShetiPhian/Localizations-and-Issues/files/5473043/crash-2020-11-02_06.43.12-client.txt)

Forge: 34.1.25
EnderChests: 1.16-1.7.4

**Comment by ShetiPhian** [comment]
Not getting this standalone or with the couple of mods I normally test with.
So either someone is changing the BlockRendererDispatcher after I cache the instance, which I can fix by not caching it, or something else in the rendering pipeline is altered, which requires them to fix it.

http://www.mediafire.com/file/hdu7yyxl3bh0df9/enderchests-1.16-1.7.5--TESTER2.jar/file

**Comment by Okimo** [comment]
Ah I'm sorry I forgot to mention pack and add debug + log:

So pack is ATM6

These are with old version:
[2020-11-02-2.log](https://github.com/ShetiPhian/Localizations-and-Issues/files/5474489/2020-11-02-2.log)
[debug-2.log](https://github.com/ShetiPhian/Localizations-and-Issues/files/5474491/debug-2.log)

And this is with the new file:
[crash-2020-11-02_12.07.48-client.txt](https://github.com/ShetiPhian/Localizations-and-Issues/files/5474502/crash-2020-11-02_12.07.48-client.txt)
[latest.log](https://github.com/ShetiPhian/Localizations-and-Issues/files/5474505/latest.log)
[debug.log](https://github.com/ShetiPhian/Localizations-and-Issues/files/5474509/debug.log)

**Comment by Okimo** [comment]
So Update: 
Setting this to **false** inside forge-client.toml

`	#EXPERIMENTAL: Enable the Forge block rendering pipeline - fixes the lighting of custom models.
	experimentalForgeLightPipelineEnabled = false`

Stopped the crashing
Reason for having it enabled was Refined storage for fixing light render on its blocks.

**Comment by ShetiPhian** [comment]
The experimental pipeline looks to be the issue.
With no other mods it will crash if enabled.

Looking of the part before the crash makes me wonder how it should be working.

VertexLighterFlat.processQuad gets the vertex format; which is DefaultVertexFormats.BLOCK and has 6 elements.
A bit further down it loops through the elements calling VertexBufferConsumer.put
The problem happens with the last element (index 5)
VertexBufferConsumer.put at first does nothing with index 5 but at the end calls BufferBuilder.endVertex(); if it is index 5
BufferBuilder throws the crash if the vertexFormatIndex is not 0

It looks like VertexBufferConsumer.put should be calling BufferBuilder.nextVertexFormatIndex for index 5.

(Note: This is all outside of my code and I can't do anything about it)

**Comment by BedrockLegends** [comment]
@ShetiPhian this is pipeline thing is cause of refinedstorage Added a nag message when a player joins the world that asks the player to enable the experimental Forge lighting pipeline to ensure correct rendering (raoulvdberge)

**Comment by BedrockLegends** [comment]
so u may want to yell at them

**Comment by ShetiPhian** [comment]
Not worth yelling at another author over a Forge issue. They likely added the nag to cut back on bug reports.

I see how Forge tampers with the pipeline though. They extend the original renderer, make their changes there, and change the renderer instance variable to point to their version.
This works out better then my original thought (toggle the config option off, render my block, toggle it back on) as I can just create my own instance of the original renderer and use that, thus avoiding the unfinished Forge code.

http://www.mediafire.com/file/qq01m7e9iwkdv27/enderchests-1.16-1.7.5--TESTER3.jar/file

**Comment by BedrockLegends** [comment]
Have not had time to test that been super busy updating to 1.16.4

**Comment by xannor** [comment]
I just ran into this issue, and If I load the latest release I will crash due to placing an enderchest, but the tester3 version loads and run good so far.

This test release saved by bacon, since I had patterns in refined storage and it would crash the game opening the pattern manager with your mod disabled.

**Comment by ShetiPhian** [comment]
New build is now on Curse.
https://www.curseforge.com/minecraft/mc-mods/enderchests/files/3106960
