### ISSUE TITLE
Flickering/Clipping Textures on rise [1.14]

### ISSUE THREAD

**Issue by RangeCreed** [ShetiPhian/Localizations-and-Issues#282]
Hello, 

I noticed that when changing the design of the rise to a specific style, any other blocks/platform pieces below it will cause a clipping and then flickering texture issue when moving around. Does not happen with any other platform pieces.

![2020-11-15_18 04 36](https://user-images.githubusercontent.com/3491652/99192938-9f273f00-276d-11eb-9339-c2a706a74467.png)

**Comment by ShetiPhian** [comment]
Placing a slanted rise on top of a rise was not an expected use case.
The z-fighting between the handrail and board, just requires a slight tweak to the handrail model.

I was wondering how you managed to make the slanted board gray when it should be the wood texture.
Its another model error, in 1.14 the texture is not being applied to the left hand rail, so it is getting a random one (my test world got lava)

The lower horizontal board contains two more errors.
Its 5 tall and should be 3 to match the rest and its texture and its sitting 2 one hundredths lower then is should be.



New build in now up on Curse
https://www.curseforge.com/minecraft/mc-mods/platforms/files
