### ISSUE TITLE
Terraheads look like skeleton heads

### ISSUE THREAD

**Issue by WenXin20** [ShetiPhian/Localizations-and-Issues#285]
`Minecraft v1.16.4`
`Forge v35.1.15`
`Terraqueous v1.7.8`

Wearing any of the Terraheads displays a skeleton head on the player instead.

![2020-12-28_11 46 06](https://user-images.githubusercontent.com/12000593/103233529-f7239a80-4902-11eb-8b0e-27f28eee7472.png)

**Comment by ShetiPhian** [comment]
Fixed build uploaded:
https://www.curseforge.com/minecraft/mc-mods/terraqueous/files/all
