### ISSUE TITLE
Bug with Small Stone Clusters

### ISSUE THREAD

**Issue by KrysEmlyn** [ShetiPhian/Localizations-and-Issues#286]
There seems to be a bug with the small stone and sandstone clusters in your mod. I initially reported this issue to the Dynamic Surroundings developer because it became really noticeable with that mod active. The issue is that the clusters creating burning particles and making hissing noises when they are waterlogged (spawned in pools/rivers/oceans/etc.).

Quote from my (now closed) issue posted on the Dynamic Surroundings GitHub:
> It's not dynamic surroundings. I have a session running without my mod and I still see the same effect. With Dynamic Surroundings installed and debug tracing enabled I can see it is a mod intentionally playing the sound.
> 
> I took a look inside the Terraqueous JAR. It seems they have a bug in their doodads (all their miscellaneous things). Burnium has this special logic so if it is in water it will play effects. However, this check is on the general doodad block and will apply to all doodads. There is a config settings in terraqueous.toml where you can turn this off (burnium_reacts_to_water).
> 
> I recommend reporting it to the Terraqueous author.

Could this be changed to provide a better experience when playing?
I'm running terraqueous-1.16-1.7.8 on Forge-1.16.4-35.1.15 for Minecraft 1.16.4.

**Comment by ShetiPhian** [comment]
Odd that should only be happening with the Burnimum crystals.
Did I accidently remove the doodad type check when I moved the code? ... I did, what a dumb mistake.

This will be corrected in the next build, need to look into another bug first.
For now setting "burnium_reacts_to_water" to false will stop it. (or by going back one version)

**Comment by ShetiPhian** [comment]
Fixed build uploaded:
https://www.curseforge.com/minecraft/mc-mods/terraqueous/files/all
