### ISSUE TITLE
Potted plants render incorrectly

### ISSUE THREAD

**Issue by WenXin20** [ShetiPhian/Localizations-and-Issues#288]
`Minecraft v1.16.5`
`Forge v36.0.1`
`Terraqueous v1.7.10`

Potted plants currently do not render correctly. I was also wondering, will flowers eventually get new textures to match the new minecraft texture style?

![2021-01-23_18 01 00](https://user-images.githubusercontent.com/12000593/105617634-64610900-5da5-11eb-9b0c-9918c0d93da8.png)

**Comment by ShetiPhian** [comment]
Those are using an unaltered instance the vanilla class, and its model.
I've likely missed setting the render layer when it was changed from block level (thus automatically set by the vanilla class) to requiring separate registration in 1.15

**Comment by ShetiPhian** [comment]
Looks like that was the issue, let me know it this build fixes it for you as well
https://www.mediafire.com/file/334dvlojgpqfz4i/terraqueous-1.16-1.7.11.jar/file
