### ISSUE TITLE
missing ShetiPhiancore?

### ISSUE THREAD

**Issue by Antonyvw** [ShetiPhian/Localizations-and-Issues#29]
Ive tried to install platforms but it tells me that shetiphiancore is missing even though I installed it before installing platforms.
As far as I know I'm using the latest versions of both files.

[fml-client-latest.txt](https://github.com/ShetiPhian/Localizations-and-Issues/files/716082/fml-client-latest.txt)

**Comment by ShetiPhian** [comment]
The core your are running is 3.3.0, Platforms needs 3.3.3 or higher.

Where did you get the mods from?
ShetiPhianCore-1.10.2.jar is not the correct name, who knows if there is other tampering.

The only official download for my mods is Curse.
