### ISSUE TITLE
[1.16.5] The bed item is duplicated.

### ISSUE THREAD

**Issue by Daejangnamu** [ShetiPhian/Localizations-and-Issues#290]
forge-1.16.5-36.0.0 ~ 36.0.13
multibeds-1.16-1.7.6

video: https://youtu.be/S1WO8wkmQI0

**Comment by ShetiPhian** [comment]
I overlooked a 1.16 change in the base bed class.

New build:
https://www.curseforge.com/minecraft/mc-mods/multibeds/files/3191619
