### ISSUE TITLE
Crash when using Mekanism Logistical Transporters with CraftBench

### ISSUE THREAD

**Issue by franga2000** [ShetiPhian/Localizations-and-Issues#294]
**EDIT:** I accidentlly posted this before I was done writing it. If it doesn't make sense, wait a minute for me to edit it.

#### Issue description:

When using a Mekanism Logistical Transporter to pull items out of a CraftBench and the CraftBench's configuration is changed, the server is likely to crash. Once restarted, whenever that chunk is loaded, the crash happens again - the only solution is to remove the offending Logistical Transporter *(using "offline" map editors or seting up a command block to spam a `/fill` command on its coords every tick and teleporting to the location to load it)*.

My *uneducated guess* (I work with Bukkit, not Forge) is that Terraqueous doesn't properly invalidate its capability object when settings are changed and/or doesn't fire whatever event Mekanism listens to in order to refresh its pipe network cache, but that's as far as I can figure it out since it's closed source and I don't have a debugging setup ready.

#### Steps to reproduce:
1. Place a CraftBench, set a recipe, set all sides to disabled
2. Connect a Logistical Transporter in Pull mode from the CraftBench to some inventory
3. Change the relevant side in the CraftBench to something different (usually yellow+orange) (make sure to save it)
4. Server should crash
5. If it didn't, goto 3

#### Version:
**Forge:** 1.16.5-36.0.14
**Mekanism:** 1.16.4-10.0.19.446
**Terraqueous:** 1.16-1.7.12

#### Crash log:

https://gist.github.com/franga2000/e74061c087a53f3202357954725fe885

**Comment by ShetiPhian** [comment]
It was a dumber mistake then you gave me credit for.
The method that gets the inventory for a given side will return null if no inventory is assigned. I missed performing a null check before sending the returned value to the capability.


http://www.mediafire.com/file/xdei21vu8ucckqe/terraqueous-1.16-1.7.14.jar/file

**Comment by ShetiPhian** [comment]
Fix has now been uploaded to Curse.
1.14.4 + 1.15.2 + 1.16.[2/3/4/5] - Platforms & Terraqueous
