### ISSUE TITLE
i can't eat food

### ISSUE THREAD

**Issue by Gamestrust-TS** [ShetiPhian/Localizations-and-Issues#295]
i can't eat mod products like fruits etc. The only things I can eat are cooked meat, steak, others I have yet to find and try. I still don't know which mod it depends on.
Use together with the Food mod series (Pam's HarvestCraft) and related mods.
Can the error be resolved or identified? thank you so much

**Comment by ShetiPhian** [comment]
I've checked the current build and fruit is editable.
Another mod is blocking it but I'm not too familiar with other mods, so I don't know of any that stops you from eating.
I remember there was one that made you eat different things by decreasing its value each time you ate the same thing in a row. There was also an RP/Adventure mod that changed your diet. No longer know their names though.
