### ISSUE TITLE
Doodads generate in lava

### ISSUE THREAD

**Issue by WenXin20** [ShetiPhian/Localizations-and-Issues#297]
`Minecraft v1.16.5`
`Forge v36.1.4`
`Terraqueous v1.7.14`

Doodads can sometimes generate in lava.

![2021-04-15_14 10 42](https://user-images.githubusercontent.com/12000593/114926000-6d3a0780-9df5-11eb-946b-dbdba9566646.png)

**Comment by ShetiPhian** [comment]
I think I've located the error.
Did that world have other mods with world gen?
If not could I get the world seed and location, that way I can do a before and after test.

**Comment by WenXin20** [comment]
Oh, uh, it had other mods, but I've already lost that world since the pack is wip and being changed.

**Comment by ShetiPhian** [comment]
Fixed build is now on Curse
https://www.curseforge.com/minecraft/mc-mods/terraqueous/files/3283458

**Comment by WenXin20** [comment]
Thanksn
