### ISSUE TITLE
[1.12.2] Crash creating world

### ISSUE THREAD

**Issue by hoolatehip** [ShetiPhian/Localizations-and-Issues#299]
Tried twice to create new superflat world. Crash both times. 

Saw a similar crash a while back in the middle of playing a world, didn't appear to be from generating chunks (I was near my base). I will see if I can find the log from that one. 

Relevant section of crash log follows. Complete file below. 

> Description: Exception initializing level
> 
> java.lang.UnsupportedOperationException
> 	at java.util.AbstractList.add(AbstractList.java:148)
> 	at java.util.AbstractList.add(AbstractList.java:108)
> 	at java.util.AbstractCollection.addAll(AbstractCollection.java:344)
> 	at shetiphian.terraqueous.common.worldgen.GenFlowers.generate(GenFlowers.java:54)
> 	at shetiphian.terraqueous.common.worldgen.GenBase.generate(GenBase.java:68)
> 	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
> 	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1020)
> 	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:990)
> 	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
> 	at net.minecraft.world.World.func_72964_e(World.java:310)
> 	at net.minecraft.world.World.func_175726_f(World.java:305)
> 	at net.minecraft.world.World.func_180495_p(World.java:911)
> 	at net.minecraft.world.World.func_175623_d(World.java:230)
> 	at net.minecraft.world.World.func_184141_c(World.java:210)
> 	at net.minecraft.world.WorldProvider.func_76566_a(WorldProvider.java:76)
> 	at net.minecraft.world.WorldServer.func_73052_b(WorldServer.java:944)
> 	at net.minecraft.world.WorldServer.func_72963_a(WorldServer.java:866)
> 	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:123)
> 	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:156)
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
> 	at java.lang.Thread.run(Thread.java:748)

[crash-2021-05-26_14.17.58-server.txt](https://github.com/ShetiPhian/Localizations-and-Issues/files/6549193/crash-2021-05-26_14.17.58-server.txt)

**Comment by hoolatehip** [comment]
The world that was being created during the above crash was playable when I relaunched the game. It didn't appear to be corrupted at all. However, it crashed again after a few minutes. Again, the complete crash report is below. 

> Description: Exception ticking world
> 
> java.lang.UnsupportedOperationException
> 	at java.util.AbstractList.add(AbstractList.java:148)
> 	at java.util.AbstractList.add(AbstractList.java:108)
> 	at java.util.AbstractCollection.addAll(AbstractCollection.java:344)
> 	at shetiphian.terraqueous.common.worldgen.GenFlowers.generate(GenFlowers.java:54)
> 	at shetiphian.terraqueous.common.worldgen.GenBase.generate(GenBase.java:68)
> 	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
> 	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1020)
> 	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:985)
> 	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
> 	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
> 	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
> 	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
> 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
> 	at java.lang.Thread.run(Thread.java:748)

[crash-2021-05-26_14.59.35-server.txt](https://github.com/ShetiPhian/Localizations-and-Issues/files/6549400/crash-2021-05-26_14.59.35-server.txt)

**Comment by ShetiPhian** [comment]
No crash in either superflat or normal generation. (Forge 14.23.5.2854, Terraqueous 1.12.2-1.14.18, +other mods)
That crash indicates values are being added to an unmodifiable list, but my generators use ArrayList which supports the addAll method.

Some point between the creation of the ArrayList (populated via addAll), and the attempt to add more flowers via addAll, the list type has been changed to one that can't be modified.

Another mod is probably optimizing lists by changing their type, but it is not seeing the list gets changed in an if block and wrongly making it unmodifiable.

Either my flower generation needs to be disabled (it's a config option), or you'll need to hunt down what is causing the issue. (maybe it has configs to disable it or blacklist my generator)

**Comment by hoolatehip** [comment]
As far as I can tell, none of the mods I'm using are supposed to be messing with other mods' lists. Of course, that doesn't rule out a bug. 

If I disable flower generation, will flowers already in the world be affected?

**Comment by ShetiPhian** [comment]
I was thinking more on the lines of full game/java optimization that happens to also be applying to other mods. I don't know of any though.

Disabling the generation only stops new flowers form being generated with the chunk.
Existing flowers will remain, and will continue to grow and spread. The item remains valid so you can still use the flowers like normal, and obtain them from the creative menu. Bonemeal will also still work, as flowers are added to the per biome registry at setup.

**Comment by AmyRose1288** [comment]
as for me.......not showing anything except stuck at 1% generating world

My Mod List:

<ul>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/bookshelf">Bookshelf (by DarkhaxDev)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/jei">Just Enough Items (JEI) (by mezz)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/terraqueous">Terraqueous (by ShetiPhian)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/toast-control">Toast Control (by Shadows_of_Fire)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/custom-starter-gear">Custom Starter Gear (by brandon3055)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions">Enchantment Descriptions (by DarkhaxDev)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/just-enough-characters">Just Enough Characters (by towdium)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/prefab">Prefab (by wuestman)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/torohealth-damage-indicators">ToroHealth Damage Indicators (by ToroCraft)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/appleskin">AppleSkin (by squeek502)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/architectury-forge">Architectury API (Forge) (by shedaniel)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/ftb-library-forge">FTB Library (Forge) (by FTB)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/dungeon-crawl">Dungeon Crawl (by XIROC1337)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/waila-harvestability">Waila Harvestability (by squeek502)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/wawla">Wawla - What Are We Looking At (by DarkhaxDev)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/bow-infinity-fix">Bow Infinity Fix (by Parker8283)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/libx">LibX (by noeppinoeppi)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/jea">Just Enough Advancements (JEA) (by MelanX)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/gokistats">GokiStats (by lacuda55)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/health-overlay">Health Overlay (by Terrails)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/expanded-storage-forge">[Forge] Expanded Storage (by NinjaPhenix)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/vanilladeathchest-forge">VanillaDeathChest (Forge) (by TheRandomLabs)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/projecte">ProjectE (by SinKillerJ)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/menu-companions">Menu Companions (by Fuzs_)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/trashslot">TrashSlot (by BlayTheNinth)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/patchouli">Patchouli (by Vazkii)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/the-vanilla-experience">The Vanilla Experience (Mod) (by Serilum)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/journeymap">JourneyMap (by techbrew)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/chance-cubes">Chance Cubes (by TurkeyDev)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/catalogue">Catalogue (by MrCrayfish)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/world-handler-command-gui">World Handler - Command GUI (by Exopandora)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/polymorph">Polymorph (Forge) (by TheIllusiveC4)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/exotic-birds">Exotic Birds (by ThePavoReality)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/advancements-tracker">Advancements Tracker (by Kaworru)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/attributefix">AttributeFix (by DarkhaxDev)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/tips">Tips (by DarkhaxDev)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/armor-slots-in-other-inventories">Armor Slots in other Inventories (by tfarecnim)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer">Just Enough Resources (JER) (by way2muchnoise)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/inventory-hud-forge">Inventory HUD+ (by dmitrylovin)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/collective">Collective (by Serilum)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/deathquotes-death-quotes">DeathQuotes / Death Quotes (by lordcazsius)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/better-advancements">Better Advancements (by way2muchnoise)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/enhanced-celestials">Enhanced Celestials - Blood Moons & Harvest Moons (by Corgi_Taco)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/cyclic">Cyclic (by Lothrazar)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/lemon-lib">Lemon Lib (by OneLemonyBoii)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/torcherino">Torcherino (by sci4me)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/xl-food-mod-plus">XL Food Mod+ (by OneLemonyBoii)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/curios">Curios API (Forge) (by TheIllusiveC4)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/configured">Configured (by MrCrayfish)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/wwta">When Was That Again (by HorribleNerd)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/fabric-api">Fabric API (by modmuss50)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/armor-toughness-bar">Armor Toughness Bar (by tfarecnim)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/inventory-tweaks-renewed">Inventory Tweaks Renewed (by David1544)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks">Mouse Tweaks (by YaLTeR)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/mmmmmmmmmmmm">MmmMmmMmmMmm (by bonusboni)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/not-enough-crashes-forge">Not Enough Crashes (Forge) (by NatanFudge)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/controlling">Controlling (by Jaredlll08)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/hwyla">Hwyla (by TehNut)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/shetiphiancore">ShetiPhianCore (by ShetiPhian)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/in-game-account-switcher">In-Game Account Switcher (by The_Fireplace)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/placebo">Placebo (by Shadows_of_Fire)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/jei-integration">JEI Integration (by SnowShock35)</a></li>

**Comment by AmyRose1288** [comment]
[latest.log](https://github.com/ShetiPhian/Localizations-and-Issues/files/6601001/latest.log)

**Comment by ShetiPhian** [comment]
@AmyRose1288 
I pulled your issue into its own report, as it's a different issue (the generators have been changed since 1.12.2), and we don't want to spam hoolatehip with every update.
https://github.com/ShetiPhian/Localizations-and-Issues/issues/300
