### ISSUE TITLE
Can't Hit Coconut With Coconut

### ISSUE THREAD

**Issue by kenijey** [ShetiPhian/Localizations-and-Issues#30]
hit it to harvest... hit with anything except coconut... why?

**Comment by ShetiPhian** [comment]
Odd, I must have overlooked something.
The coconut entity is set to die on hit, dropping the coconut item.

**Comment by kenijey** [comment]
yeah i know that, i mean hit-to-die system won't work if you are hitting with a coconut.

**Comment by ShetiPhian** [comment]
Fixed in terraqueous-1.10.0-1.2.17 and terraqueous-1.11.0-1.3.5
Problem was in the coconut item, it was using the wrong damage entity call.

**Comment by kenijey** [comment]
thaaanks a lot
