### ISSUE TITLE
Game crashes whenever i try to load the mod

### ISSUE THREAD

**Issue by Phrogs** [ShetiPhian/Localizations-and-Issues#303]
I can load all other mods just fine, and have reinstalled both the mods and forge itself. Nothing works. The game freezes as soon as the mojang screen loading bar reaches the end. I have to quit the game because the application is not responding.

**Comment by ShetiPhian** [comment]
Minecraft Version?
Forge Version?
Mod & Version?
Are other mods present?
> If yes: 
Does everything work without my mods?
Have you tested with only my mods?

PasteBin or GitHubGists the latest.log and debug.log

**Comment by Phrogs** [comment]
I found the issue.... it appears when I reinstalled forge I forgot to allocate more ram to the version lol. That seems to have fixed it.
