### ISSUE TITLE
Incompatible with Chisels and Bits MOD

### ISSUE THREAD

**Issue by DocLockWork** [ShetiPhian/Localizations-and-Issues#306]
Black and Purple Block replacing platforms when Chisel and Bits are loaded

**Additional context**
Minecraft Version: 1.16.5
Forge Version: 1.16.5
ShetiPhian Core Version: 1.16-3.8.5
My Mod(s) Name & Version: Platforms-1.16-1.7.11
Are other mods present?
If yes:
- Does everything work without my mods?
Yes (The Mod itself and it alone is bugged when Chisel and Bits are loaded)
- Have you tested with only my mods?
Yes (Working fine without Chisel and Bits)

**Comment by ShetiPhian** [comment]
I know OptiFine breaks mod added model loaders and OptiForge fixes that.
Maybe C&B is making a similar change so they can render parts of a mod block.
Not something I can hunt down and fix though, I understand just enough about the rendering engine to render my blocks, so I keep things as basic as possible. (I've tried to solve the OptiFine issues, but just get lost once the OpenGL calls start)

Platform models are loaded in parts via the built-in json system.
When a block needs to be rendered a custom model collects the needed preloaded parts, applies the required texture, and sends all info to the renderer.
