### ISSUE TITLE
Vanilla Composter broken by Terraqueous

### ISSUE THREAD

**Issue by codewolf219** [ShetiPhian/Localizations-and-Issues#308]
**Describe the bug**
Vanilla Composter acts as if adding material with nothing in hand while Terraqueous is installed

**Additional context**
Minecraft Version: 1.16.5
Forge Version: 36.2.2
ShetiPhian Core Version: 3.8.5
My Mod(s) Name & Version: Terraqueous 1.7.15
Are other mods present? No

**Comment by ShetiPhian** [comment]
That's odd, my only interaction with the composter is adding items.
Maybe there is an order of operations change I missed and its causing the bug.

It will be a while but I'll look into this when I can.

**Comment by ShetiPhian** [comment]
Had a chance to look into this.
It was my grass block causing it, due to having no item of its own and using the vanilla one.

https://www.mediafire.com/file/sndmwmvghtc6ejd/terraqueous-1.16-1.7.16_TESTER.jar/file

**Comment by ShetiPhian** [comment]
Builds are on Curse: https://www.curseforge.com/minecraft/mc-mods/terraqueous/files/all
