### ISSUE TITLE
Pergola wells spawn with waterlogged stairs

### ISSUE THREAD

**Issue by WenXin20** [ShetiPhian/Localizations-and-Issues#309]
**Describe the bug**
- Pergola wells, in this case in the desert village, can spawn with waterlogged blocks
- The village was close to a river.

**Additional context**
`Minecraft v1.16.5`
`Forge v36.2.4`
`ShetiPhian Core v3.8.6`
`Terraqueous v1.7.17`

Are other mods present?
- Yes, but did not get a chance to test without. I can do this later if necessary.

![2021-10-18_12 18 39](https://user-images.githubusercontent.com/12000593/137778854-b1d6c1a4-3a6a-4f71-9a77-edbd89a4b0e4.png)

**Comment by ShetiPhian** [comment]
Can I get the seed.
I flew around for a while and only ever saw two pergola variants, neither of which where wells.

The structure wasn't saved with those waterlogged.
The water must spread before all the blocks are placed, likely why the default wells do not have stairs.

**Comment by ShetiPhian** [comment]
A new build is now up on Curse, I ended up reconfiguring the structures.
When generating structures Minecraft appears to ignore the waterlogged flag, and just waterlogs any block beside a source block.
