### ISSUE TITLE
Tanks and buckets will not accept fluids

### ISSUE THREAD

**Issue by Shedao-Shai** [ShetiPhian/Localizations-and-Issues#312]
**Describe the bug**

Neither the endertank nor linked ender buckets will accept fluids. Upgrades work as normal, as does powering the tank with redstone (texture change), but it is impossible to actually put fluids in the tank.

**Additional context**
Minecraft Version: 1.17.1
Forge Version: 37.0.104
ShetiPhian Core Version: 1.17-3.9.0
My Mod(s) Name & Version: EnderTanks 1.17-1.10.0
Are other mods present? No, verified with no other mods present
If yes:
- Does everything work without my mods?
- Have you tested with only my mods?

PasteBin or GitHub Gists links
latest.log = https://gist.github.com/Shedao-Shai/74ae9a75c63e86f386dd9303f39541ce
debug.log = https://gist.github.com/Shedao-Shai/9bd7ea9b2b6e4defca865a75a58fc239

**Comment by ShetiPhian** [comment]
The new builds on Curse fix this, Forge beta builds are no longer supported though, 37.1.0+ is required.
