### ISSUE TITLE
Broken template is: terraqueous:village/plains/houses/plains_meeting_point

### ISSUE THREAD

**Issue by Reshy** [ShetiPhian/Localizations-and-Issues#313]
**Describe the bug**
****************** Blame Report Processor 1.16.5-3.7.0-forge ******************

 Processor blew up trying to process a block.
 Broken template is: terraqueous:village/plains/houses/plains_meeting_point
 Block being processed: Block{minecraft:jigsaw}[orientation=up_north]
 NBT of the block being processed: {
  "field_74784_a": {
    "joint": {
      "field_74751_a": "rollable"
    },
    "name": {
      "field_74751_a": "minecraft:bottom"
    },
    "pool": {
      "field_74751_a": "minecraft:village/common/cats"
    },
    "final_state": {
      "field_74751_a": "minecraft:dirt_path"
    },
    "id": {
      "field_74751_a": "minecraft:jigsaw"
    },
    "target": {
      "field_74751_a": "minecraft:bottom"
    }
  }
}

**Additional context**
Minecraft Version: 1.16.5
Forge Version: 36.2.19
ShetiPhian Core Version: shetiphiancore-1.16-3.8.6.jar
My Mod(s) Name & Version: terraqueous-1.16-1.7.17.jar
Are other mods present?
If yes:   Usually it's fine.

PasteBin or GitHub Gists links
latest.log = [latest.log](https://github.com/ShetiPhian/Localizations-and-Issues/files/7612766/latest.log)

**Comment by ShetiPhian** [comment]
java.lang.RuntimeException: com.mojang.brigadier.exceptions.CommandSyntaxException: Unknown block type 'minecraft:dirt_path'

Looks like another mod has removed the dirt path block from the game.


Meeting points are the first structure generated when a new village is loading, just happened to be mine that was chosen, but even the vanilla village structures will crash with the path missing.

**Comment by Reshy** [comment]
There is no dirt path block in the game, just installing your mod on it's own in vanilla there's no dirt path block.  You must be thinking the minecraft:grass_path and the mod is misreferencing.

**Comment by ShetiPhian** [comment]
Welp.. I knew the path existed, didn't expect Mojang to have renamed it.
Between that and this build being out for a month and a half, with 3k downloads, I I sure if it was my bug it would have been reported a while ago. On top of that, seeing the "it will break other mods" error, was enough to make me dismiss this report entirely without looking into it.

Sorry.

**Comment by Reshy** [comment]
It's no problem, it is a bit off for a block to be renamed after being in the game for so long.  Just so long as it can get fixed I'll be happy, the mod will be better and less crashes for everyone.

**Comment by ShetiPhian** [comment]
I can spawn the structure in with these builds, so it should solve your crash. (Curse upload will be later)

1.15 : https://www.mediafire.com/file/7kfd1qny4nhmu6i/terraqueous-1.15-1.6.15.jar/file
1.16 : https://www.mediafire.com/file/am7czuongc272bm/terraqueous-1.16-1.7.18.jar/file

**Comment by ShetiPhian** [comment]
1.15 & 1.16 builds are now on Curse (1.17 will be uploaded once their Internal Server Error clears)

Curse builds fix other structure issues found after the test builds.
