### ISSUE TITLE
Minecolonies Banner incompatability

### ISSUE THREAD

**Issue by thepriz** [ShetiPhian/Localizations-and-Issues#314]
**Describe the bug**
The builders in Minecolonies do not recognize banners. It was discovered after removing Multibeds and crafting a new banner they would recognize them. The issue was reported on Minecolonies here: https://github.com/ldtteam/minecolonies/issues/7728

**Additional context**
Minecraft Version: 1.16.5
Forge Version: 36.2.19
ShetiPhian Core Version: 1.16-3.8.6
My Mod(s) Name & Version: Minecolonies 1.0.205
Are other mods present? yes
If yes:
- Does everything work without my mods? yes
- Have you tested with only my mods? no

There are no crashes so I don't think the logs would help. Someone suggested that Multibeds may add something to the NBT of a banner causing it to not be recognized by the builder. I don't know if this can be fixed but I thought it was important to post an incompatibility here.

**Comment by ShetiPhian** [comment]
Just uploaded fixed builds to Curse.
NBT contamination will no longer generate, but existing banners need to be manually cleaned by putting them on a bed.
