### ISSUE TITLE
Terraqueous says java.lang.NoSuchFieldError: DIRT

### ISSUE THREAD

**Issue by coldReactive** [ShetiPhian/Localizations-and-Issues#317]
**Describe the bug**
Terraqueous stops world generation with error `java.lang.NoSuchFieldError: DIRT`

**Additional context**
Minecraft Version: 1.18.1
Forge Version: 39.0.19
ShetiPhian Core Version: shetiphiancore-1.18-3.10.1.jar
My Mod(s) Name & Version: terraqueous-1.18-1.9.0.jar
Are other mods present?
If yes:
- Does everything work without my mods? Yes, loads perfectly fine. It even works with ShetiPhianCore enabled, but Terraqueous disabled.
- Have you tested with only my mods? Yes. Loads perfectly fine, no crashes, no errors in-game.

PasteBin or GitHub Gists links
latest.log = https://pastebin.com/Xj6CN4Bh
debug.log = https://pastebin.com/QECFvBZb
crash-report = https://pastebin.com/8A91BNgw

**Comment by ShetiPhian** [comment]
Use Forge 39.0.17 until I release another build.

Forge is still in beta, thus breaking changes can happen in any build and there was one in 39.0.18

**Comment by ShetiPhian** [comment]
Build now on Curse, launches with Forge 39.0.20 and 39.0.5 so should work with any version between them
https://www.curseforge.com/minecraft/mc-mods/terraqueous/files/3609125
