### ISSUE TITLE
MultiBeds Fabric Quads crash exit code 1

### ISSUE THREAD

**Issue by Enikimm** [ShetiPhian/Localizations-and-Issues#318]
[crash-2022-01-17_14.02.11-client.txt](https://github.com/ShetiPhian/Localizations-and-Issues/files/7884412/crash-2022-01-17_14.02.11-client.txt)
Please fix

**Comment by ShetiPhian** [comment]
I had already responded in the comments, but I'll duplicate it here for those who come after.

> Not me, Sodium is causing it, because they don't support the Fabric Rendering API.
> If Curse supported conditional dependencies I wouldn't have to rely on the description to point people towards Indium.
