### ISSUE TITLE
Placing Terraqueous's craftbench makes the game crash.

### ISSUE THREAD

**Issue by VoxelVixen** [ShetiPhian/Localizations-and-Issues#319]
**Describe the bug**

A player made the Terraqueous craftbench and right after placing it in the world , the server and our clients crashed.
Trying to log back in resulted in more servercrashes till i rerolled to an earlier savepoint.

**Additional context**
Minecraft Version: 1.18.1
Forge Version: 39.0.59
ShetiPhian Core Version: 1.18-3.10.2
My Mod(s) Name & Version: terraqueous-1.18-1.9.1
Are other mods present? - Yes
If yes:
- Does everything work without my mods? - Not tested
- Have you tested with only my mods? -Yes

Made a new profile with same Forge , Core and Terraqueous versions. No other mods .  In singleplayer placing the craftbench resulted in hard crash of the game. Crash log = https://pastebin.com/gnU3EGkk

PasteBin or GitHub Gists links
latest.log = 
debug.log =
servercrash log = https://pastebin.com/fggum0Jc

**Comment by ShetiPhian** [comment]
I'm preforming a null check where an instanceof check was needed. 

https://www.mediafire.com/file/me9db6kgz1akkvl/terraqueous-1.18-1.9.2--TESTER.jar/file

**Comment by VoxelVixen** [comment]
This version has fixed the crash , could you upload it to curseforge so i can add it to my pack ? Thanks for the fix

**Comment by ShetiPhian** [comment]
Just uploaded the build to Curse (with a couple of other fixes)
https://www.curseforge.com/minecraft/mc-mods/terraqueous/files/3632233
