### ISSUE TITLE
Banana Flower Missing Localization

### ISSUE THREAD

**Issue by WenXin20** [ShetiPhian/Localizations-and-Issues#320]
**Describe the bug**
When the banana flower, stalk, or stalk with fruit is view with The One Probe or pick-blocked, it can be seen that it is missing localization. It displays as `block.terraqueous.banana_leaves.stalk`, etc.

**Additional context**
`Minecraft v1.18.1`
`Forge v39.0.29`
`ShetiPhian Core v3.10.2`
`Terraqueous v1.9.2`
Are other mods present?
If yes:
- Does everything work without my mods?
  - yes
- Have you tested with only my mods?
  - yes

**Comment by ShetiPhian** [comment]
Fixed in new builds
https://www.curseforge.com/minecraft/mc-mods/shetiphiancore/files
