### ISSUE TITLE
[1.18.1] Crash when interacting with Immersive Engineering machines

### ISSUE THREAD

**Issue by Shedao-Shai** [ShetiPhian/Localizations-and-Issues#322]
**Describe the bug**
When using the endertank to directly pump out of an Immersive Engineering machine, a crash occurs when the ender tank is turned on

**Additional context**
Minecraft Version: 1.18.1
Forge Version: 39.0.59
ShetiPhian Core Version: 3.10.2
My Mod(s) Name & Version: 1.11.1
Are other mods present? Yes
If yes:
- Does everything work without my mods?   Issue is not present without your mods
- Have you tested with only my mods?  This crash does occur solely with Endertanks and IE, IE is obviously required to reproduce

PasteBin or GitHub Gists links
latest.log = https://gist.github.com/Shedao-Shai/2237eb956291b4244354b8519da15024
debug.log = https://gist.github.com/Shedao-Shai/d5d1989a408ba67c476532393bc1312d
crash log: https://gist.github.com/Shedao-Shai/10364db02c5bca7da3358a82fafc823b

Issue also reported to IE, but I am not sure who's side the issue is on so I thought I would report here to. Awesome mod!

**Comment by ShetiPhian** [comment]
Going by the log, it looks like their custom handler is not expecting/processing an empty fluid stack like the Forge default one does.

This would be possible to solve on either side.
I can add a check to stop a crash when mods don't expect it.
They'll likely want to add a check also to match Forges handling.

**Comment by ShetiPhian** [comment]
I noticed a couple of days after my last post IE's github had the fix.
The latest 1.18 build of EnderTanks also has the fix.
