### ISSUE TITLE
Terraqueous 1.18-1.9.3 causing Minecraft to crash before loading.

### ISSUE THREAD

**Issue by CsillaAria** [ShetiPhian/Localizations-and-Issues#323]
Terraqueous 1.18-1.9.3 causing Minecraft to crash before loading. It's not even giving me a crash report.

**Minecraft Version:** 1.18.1
**Forge Version:**  39.0.66
**ShetiPhian Core Version:**  1.18-3.10.3
**My Mod(s) Name & Version:** terraqueous-1.18-1.9.3
**Are other mods present?** Yes
If yes:
**- Does everything work without my mods?** Yes, it also works with terraqueous-1.18-1.9.0, the last version I downloaded before this one
**- Have you tested with only my mods?** Yes, terraqueous-1.18-1.9.3, and shetiphian core 1.18-3.10.3 it still crashed.

**Comment by ShetiPhian** [comment]
FFS, I had a working jar, fixed the banana stalk translation keys, recompiled and didn't test the new jar as nothing was changed that could cause a problem. Except for the compile not adding all the files and claiming the build was successful -_-

Looks like it didn't copy the refmap into 1.17 either. Last time it did this I needed to purge most of my build environment and rebuild.

**Comment by ShetiPhian** [comment]
Fixed build:
https://www.curseforge.com/minecraft/mc-mods/terraqueous/files/3649528

**Comment by CsillaAria** [comment]
It works now! Thank you!
