### ISSUE TITLE
Cannot pull or push item from ender chest

### ISSUE THREAD

**Issue by Spaceman** [ShetiPhian/Localizations-and-Issues#326]
**Describe the bug**

**Additional context**
Minecraft Version: 1.18.1
Fabric Version: 0.13.2
ShetiPhian Core Version: 1.2.2
My Mod(s) Name & Version: EnderChests [Fabric] 1.0.1
Are other mods present?
If yes:
- Does everything work without my mods? Yes
- Have you tested with only my mods? Yes

**Comment by ShetiPhian** [comment]
When I ported from Forge I removed their system, but looks like I missed a step for implementing the Fabric compatible one.

**Comment by ShetiPhian** [comment]
This was a quick patch. Its working with hoppers, should also work with mod pipes etc.

https://www.mediafire.com/file/ms79tpox2awceoe/enderchests-%255Bfabric%255D-1.18-1.0.2--TESTER.jar/file

**Comment by Spaceman** [comment]
Sweet thanks ill check it out

**Comment by Spaceman** [comment]
Works like a charm!! Tested with hoppers, AE2 and Tech reborn

**Comment by ShetiPhian** [comment]
I'll push that build to Curse.
No need to redownload, but I'd suggest renaming to remove the tester tag
