### ISSUE TITLE
[1.11.2] Platforms stairs are off with collision

### ISSUE THREAD

**Issue by shortybsd** [ShetiPhian/Localizations-and-Issues#33]
Forge 2223
Minecraft 1.11.2
platforms-1.11.0-1.3.1
shetiphiancore-1.11.0-3.4.1.jar

You can see invisible full square blocks every where you place stairs/ramps. You hit a wall rather than walk up them.

**Comment by ShetiPhian** [comment]
Found the issue, Minecraft 1.11.1 made a change to the addCollisionBoxToList method, so my 1.11.0 method is never used.

I've got a code fix that works around the issue so I don't need to drop 1.11.0 support yet.
I'll need to apply this fix to most of my other mods also.

**Comment by shortybsd** [comment]
Nice, thank you sir.

**Comment by ShetiPhian** [comment]
Fixed in platforms-1.11.0-1.3.2

**Comment by shortybsd** [comment]
Sweet! Thank you very much.
