### ISSUE TITLE
Suggestion: Replace vanilla Beds

### ISSUE THREAD

**Issue by TheButterbrotMan** [ShetiPhian/Localizations-and-Issues#330]
It would be nice if the mod would replace vanilla beds in villages

**Comment by ShetiPhian** [comment]
I don't know if that can be done without replacing the village structure files.
The problem with that is two fold, it wouldn't support mod added structures, and I can't add a configuration option for it.

**Comment by ShetiPhian** [comment]
This feature is available in the latest builds.

The config option is off by default.
You'll need to launch the game once to generate the common config, change the option then relaunch the game.

Also only newly generated villages will have the beds changed.

**Comment by TheButterbrotMan** [comment]
Hello @ShetiPhian. Is it possible to for you to replace the beds also in custom structures from other mods?

**Comment by ShetiPhian** [comment]
If they are generated from structure files it should be working, as the code hooks into the loading and replaces any vanilla beds with mine.

**Comment by TheButterbrotMan** [comment]
Hmm, i have structures that still have normal beds.
