### ISSUE TITLE
Suggestion: Change recipes.

### ISSUE THREAD

**Issue by Ackmard** [ShetiPhian/Localizations-and-Issues#332]
Would it be possible to "merge" the Ender Chest/Tank/Bag recipes to a single one like EnderStorage is doing?

**Comment by ShetiPhian** [comment]
When I first red this I thought, "you can't have multiple items using the same recipe" but shortly after it clicked.
You want one recipe per item rather then the one per color per item that it currently is.

I can do that.

**Comment by Ackmard** [comment]
Yeah, as long as it's not a big deal to achieve that it would be really cool since you won't have to find and click the correct color you want in JEI, it will just grab the wool you have.

**Comment by ShetiPhian** [comment]
New builds submitted to Curse, just waiting for approval before they become publicly visible.
Its after hours for them so it may take a while to post.
