### ISSUE TITLE
Breaking an Ender Chest causes a crash with an exception in the server tick loop.

### ISSUE THREAD

**Issue by StormCircuit** [ShetiPhian/Localizations-and-Issues#339]
**Describe the bug**
When a player attempts to break an ender chest, the server crashes with an exception in the tick loop. Might be a mod interaction.

**Additional context**
Minecraft Version: 1.18.1
Forge Version: 39.1.2
ShetiPhian Core Version: 3.10.4
My Mod(s) Name & Version: Ender Chests: 1.9.2
Are other mods present?
If yes:
- Does everything work without my mods?
I can do this if it helps however I am not at my computer right now
- Have you tested with only my mods?
No, see above.

PasteBin or GitHub Gists links
latest.log = https://pastebin.com/1V1EJAJR
debug.log = Server doesn't seem to generate one. Is there a way to enable it in 1.18.1? I haven't explicitly disabled it and am using the forge's dedicated server.

**Comment by ShetiPhian** [comment]
This looks like its going to be a good news bad news situation.

Issue is a code loop with Apoli (but any mod that changes break speed will trigger it), and I caused it by messing up the order of operations, way back when porting (I think from 1.12)

Good news is I already know how to fix it.
Bad news for me is its not limited to just this block, Minecraft version, or even mod.

What your not going to like though is 1.18.1 is not supported anymore.
Mojang made major changes in 1.18.2, breaking forward compatibility so I moved my code to 1.18.2
But Forge has been available for a month now, so maybe all the mods are 1.18.2 now or at least close.

**Comment by StormCircuit** [comment]
Thank you for your timely response! I suppose for now I should look for bandaid fixes. I suppose a simple one would be to remove Apoli? But it sounds like there could be more issues down the line from other mods that do this. I think I get the general idea but figured I'd ask if there's a better bandaid.

Thank you again for the polite and timely response!

**Comment by ShetiPhian** [comment]
There can't be too many mods that trigger this, as both EnderChests and EnderTanks have had the bug since 1.14 and this is the first its been reported.

If your just using it for expanded personal storage, could place a chest somewhere it can stay until 1.18.2 then only use bags. That chest would be used to setup bags by changing its color bands then linking them.

I should be able to compile and test the fix later today,

**Comment by StormCircuit** [comment]
I see, thank you for your help! I presume this fix is for 1.18.2?

**Comment by ShetiPhian** [comment]
Sorry I thought the notification I got was from the previous message.

Yes the 1.18 build needs 1.18.2, and at least Forge 40.0.12
