### ISSUE TITLE
[1.11.2] [Platforms 1.11.0-1.3.1] Client crashes looking at bridge.

### ISSUE THREAD

**Issue by shortybsd** [ShetiPhian/Localizations-and-Issues#34]
Forge 2223
Minecraft 1.11.2
platforms-1.11.0-1.3.1
shetiphiancore-1.11.0-3.4.1.jar

Looking at my bridge from a distance crashes client with following error:
http://pastebin.com/rwQe9Lvn
and another one
http://pastebin.com/najxL0hT
Removed mod for now. The version you have for 1.11 worked perfect in 1.11.

**Comment by ShetiPhian** [comment]
Should be fixed in platforms-1.11.0-1.3.2

**Comment by shortybsd** [comment]
Fixed, but new issues arose out of Terraqueous. Posting the error shortly. Thanks again brother!
