### ISSUE TITLE
Planters let you get infinite buckets

### ISSUE THREAD

**Issue by RadioactiveTurtle** [ShetiPhian/Localizations-and-Issues#341]
It seems that water filled Terraqueous planters drop water buckets when you mine them even though they don't take the bucket away when filling them, thus allowing you to get infinite buckets.

Minecraft Version: 1.16.5
Forge Version: 36.2.30
ShetiPhian Core Version: 3.8.11
My Mod(s) Name & Version: Terraqueous 1.7.21
I've tested it with and without other mods, it still dropped extra water buckets either way.

**Comment by ShetiPhian** [comment]
Give this build a test:
https://www.mediafire.com/file/jch7q9ho43tku65/terraqueous-1.16-1.7.22--TESTER.jar/file

**Comment by ShetiPhian** [comment]
Curse updated
