### ISSUE TITLE
Crashing at start

### ISSUE THREAD

**Issue by TheButterbrotMan** [ShetiPhian/Localizations-and-Issues#344]
**Describe the bug**
Crashing at start

**Additional context**
Minecraft Version: 1.18.2
Fabric Version: 0.13.3
ShetiPhian Core Version: 1.18-1.2.7
My Mod(s) Name & Version: 
Are other mods present?
If yes:
- Havent tested.
PasteBin or GitHub Gists links
latest.log = https://bytebin.lucko.me/t0urZzcLkG

**Comment by ShetiPhian** [comment]
ExtendedScreenHandlerType is part of Fabric API - 0.47.10+1.18.2 and not marked for removal.
You have 0.50.0+1.18.2 and it appear to be gone.

I'll have to look into this later, but for now try rolling back the API

**Comment by TheButterbrotMan** [comment]
Can't :( Some mods depend on it

**Comment by jmdev91** [comment]
This is part of the 0.50.0+1.18.2 changelog for Fabric:
- Expose extended screen handler type creation in SH API (#2104) (Juuxel)
So they must have changed how to access it in some way. Can't dig up any details, you might have to ask in the discord about how it's changed.

**Comment by ShetiPhian** [comment]
All mods are now updated on Curse
