### ISSUE TITLE
Cloud Pressure Plates & Buttons Nonfunctional

### ISSUE THREAD

**Issue by WenXin20** [ShetiPhian/Localizations-and-Issues#345]
**Describe the bug**
- All three types of cloud buttons and pressure plates do not work when stepped on or right-clicked and won't emit a redstone signal.
- I'm also curious about the point of cloud doors and trapdoors if they can just be walked through?

**Additional context**
`Minecraft v1.18.1`
`Forge v39.1.2`
`ShetiPhian Core v3.10.4`
`Terraqueous v1.9.5`

**Comment by ShetiPhian** [comment]
- They require the ability to interact / collide with clouds
Cloud Talisman, Creative Mode, or any 3rd party item registered to my api or added to the item tag.

- People wanted to be able to make structures fully of clouds

**Comment by WenXin20** [comment]
Ah building, of course :D 
I didn't realize the cloud talisman was required either. thanks!

**Comment by WenXin20** [comment]
Actually, even with the cloud talisman equipped, cloud pressure plates still doesn't work. And the button can be right-clicked but won't emit a redstone signal. Although it works in creative.

I also noticed this, it happens with both double doors and single doors, but doesn't occur in creative.
(The textures are different for a resource pack I'm making)

https://user-images.githubusercontent.com/12000593/163009597-6de51715-9806-4909-ab71-425a4ba3f376.mp4

**Comment by ShetiPhian** [comment]
Looks to be a server issue, all works fine in single player.
Wonder when that broke.

**Comment by WenXin20** [comment]
Ah yeah, I should've mentioned I'm using a server. :D

**Comment by WenXin20** [comment]
Thanks!
