### ISSUE TITLE
[Anti virus] False positive breaking modpack

### ISSUE THREAD

**Issue by itsdinkd** [ShetiPhian/Localizations-and-Issues#349]
I'm not sure about other modpacks, however, with mine, Another Quality Modpack 2,  and the most recent version of ShetiPhianCore, people who download the modpack (myself included) have been getting false positives from Windows Defender where it quarantienes your mod, effectively breaking the modpack if they are trying to join a server. 

![image](https://user-images.githubusercontent.com/35115304/166403618-5c7b0adf-e24b-47c8-91c4-14436ecad87d.png)

I have had over 10 reports of "missing" mods today when joining a server, These are from other people when they try to launch the pack. Some have several different mods removed, not sure whats going on. 

![image](https://user-images.githubusercontent.com/35115304/166403672-b5009f6c-a462-4ff5-9c3a-301d959ddda9.png)

![image](https://user-images.githubusercontent.com/35115304/166403661-78f84398-6e00-4ece-ba63-e071557249f2.png)

**Comment by ShetiPhian** [comment]
**Immediate solution**
For now revert to the previous build, it is exactly the same as the latest just missing Korean Localization, and Defender isn't complaining.



**Full Response it Issue**
You have three mods marked as being infected with the same thing.


Using Kaspersky (https://opentip.kaspersky.com) I've checked the file on my system, and the file on Curse
They both report clean and the MD5's match D6776042AEEEAFE90C87BB8C6BF6216C
Downloading from Curse does trigger Windows Defender though.


If Defender is your only AV you'll want to remove the file exception.
Windows Defender handles them in the dumbest way possible. Rather then ignoring the file itself it ignores the detected issue. So adding an exception for a false positive opens your system up to be infected by the real thing.


I've submitted to Microsoft for review, you should report this to the other two mods also so they can.

**Comment by ShetiPhian** [comment]
And they've rejected it for too many files -_-
their system unzipped the jar file, scanned just over 200 and called it quits.
I guess I'll have to do the same to find out exactly what file it doesn't like

**Comment by ShetiPhian** [comment]
Wow this is the most pain in the ass thing I've had to deal with in a long time.
Defender is stopping me for doing anything and everything I do in defender opens up an annoying UAC prompt.

After dealing with that, Defender has no issue with the files, only the jar itself. 
Since they unzip jars to scan them and have a file limit I can't even use their submission to get it corrected.

**Comment by itsdinkd** [comment]
:( it sounds like a pain in the ass. And whats weird is why today? why not before? they had to release a update or something, Its killlllling players right now (not blaming you) but yeah, fuck Microsoft. lol.

**Comment by itsdinkd** [comment]
I'll report it to them right now.

**Comment by ShetiPhian** [comment]
There was a recent Defender definition update, I didn't have it before this report so triggered an update.

I've resubmitted the file, but used Software developer rather then Home customer.
Used Home before as I saw the "Software Assurance ID" field and left as I don't have one (enterprise customers only), but looking at it again I saw it wasn't required. Just get a lower priority without it.

So far not rejected, but only a few files looked at.

**Comment by ShetiPhian** [comment]
Microsoft Security Intelligence has responded to my submission, and cleared the file.

---

Analyst comments:

At this time, the submitted files do not meet our criteria for malware or potentially unwanted applications. The detection has been removed. Please follow the steps below to clear cached detections and obtain the latest malware definitions.

1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender
2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
3. Run "MpCmdRun.exe -SignatureUpdate"

Alternatively, the latest definition is available for download here: https://docs.microsoft.com/microsoft-365/security/defender-endpoint/manage-updates-baselines-microsoft-defender-antivirus

Thank you for contacting Microsoft.

**Comment by itsdinkd** [comment]
Thank you @ShetiPhian
