### ISSUE TITLE
[1.10.2] - terraqueous-1.10.0-1.2.16 - Forge 221 - On Server - Its Raining Oranges!

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [ShetiPhian/Localizations-and-Issues#35]
Client Logs
https://www.dropbox.com/s/ug7eaf5d4ymtbvk/logs-Client.zip?dl=0

Server Logs
https://www.dropbox.com/s/snntn7jqfgih991/logs%20Server.zip?dl=0

Youtube Video
https://youtu.be/6jf0cX9Epx8

In all the time I have been debugging mods I have never seen a bug like this.

**Comment by ShetiPhian** [comment]
What? How?

Okay this will be a fun one to figure out.
Ignoring the raining of fruit I see a few other oddities.
- Fruit will only drop if the leaves have fruit, that leaf block was empty.
- The drop code is only ran server side, it appeared like they couldn't be picked up making them client side spawned.
- The leaf block decayed and it kept raining.

Questions:
1. What happened just before the rain started?
2. Can you reproduce it?
3. Could the items be picked up?
4. Is it still happening / how long did it take to stop?
5. After leaving the server and rejoining where things normal? how many oranges where on the ground?
6. Did other players also see it happening?

**Comment by ShetiPhian** [comment]
I'm not seeing anything helpful in the logs.

The server's latest.log does have a concerning, and possibly related, error repeating constantly.
`[Server thread/WARN]: Fetching addPacket for removed entity`

Something is either removing an entity incorrectly, or is trying to sync an entity that no longer exists.

**Comment by P3rf3ctXZer0** [comment]
That is why they were ghost oranges?

**Comment by ShetiPhian** [comment]
Likely, are there any mods in you pack that control entity spawning?

**Comment by P3rf3ctXZer0** [comment]
I have no idea what caused it. I will re-open it if I figure it out.
