### ISSUE TITLE
Server Crash "Exception in server tick loop"

### ISSUE THREAD

**Issue by 87527z** [ShetiPhian/Localizations-and-Issues#350]
Server Crash when using ender bucket on lava (Other Fluids untested on server)
Game does not crash when dealing with this issue, testing concludes that its a serverside issue.
Attempted clearing config because another issue stated that that fixed a similar issue but didnt fix it here.

**Additional context**
Minecraft Version: 1.7.10
Forge Version: 1.7.10 - 10.13.4.1614
ShetiPhian Core Version: 1.7.10-3.0.0 
My Mod(s) Name & Version: EnderTanks-rev16-beta1
PasteBin or GitHub Gists links
latest.log = https://pastebin.com/tKbNHvnB
debug.log = https://pastebin.com/1cCK0Kib

**Comment by ShetiPhian** [comment]
1.7 hasn't been supported for many years now.

That build of ShetiPhian Core changed the Localization class to be client only, and that build EnderTanks does not work with the change.

If your not using one of the mods that need 3.0.0, using the older [ShetiPhianCore-v3-beta2](https://www.curseforge.com/minecraft/mc-mods/shetiphiancore/files/2295765) should fix it.

If you do need 3.0.0 you could try replacing the shetiphian/core/Localization.class file in 3.0.0 with the one from v3-beta2
Jar files are zip archives and can be opened/edited as such.

**Comment by 87527z** [comment]
Yeah Changing to that version fixed it. Thanks for the help!
