### ISSUE TITLE
Request: Release mods on Modrinth

### ISSUE THREAD

**Issue by iwillreku3206** [ShetiPhian/Localizations-and-Issues#352]
As title says, I would like to request for a Modrinth release of all mods (such as EnderChests, ShetiphianCore, etc.)

**Comment by ShetiPhian** [comment]
The 1.19.3 builds are under review now.
(I'll need to edit the mod downloads after as I couldn't add ShetiPhianCore as a dependency before it was approved)

**Comment by ShetiPhian** [comment]
Took over half a day, but they are now approved.
