### ISSUE TITLE
color coding and upgrades are lost after breaking chest

### ISSUE THREAD

**Issue by iLLHunter** [ShetiPhian/Localizations-and-Issues#353]
Thank you for trying to update this mod, so we have something to use for MC 1.18.2

I spotted some bugs. If we break an ender chest or ender tank using pickaxe, the color coding and upgrades are lost and the chest/tank resets itself to 000, default size. This is not normal behavior for these items. They should retain their color coding, and privacy setting after breaking. The upgrades are new to mod, previously we just changed the server config to make them bigger, but those seem like they should be retained as well.
(the chests are dropping themselves as items when broken but not retaining any NBT or other essential data)

Also, please add ability to color code the chests/tanks in a crafting grid, like previous versions can. This is a more efficient way to make 5 or 10 chests of the same color code

MC 1.18.2
Forge 40.1.20
enderchests-1.18-1.9.5.jar
endertanks-1.18-1.11.6.jar

Happy to provide more information if it is needed.

**Comment by iLLHunter** [comment]
Another bug: sometimes a band will reset it self to white, after we use dye on the band after it

**Comment by ShetiPhian** [comment]
I haven't been able to reproduce either bug.
Do you have other mods in your pack / have you tested with just mine?
Is this a dedicated server, or LAN host/client? and does it work in single player?

The loss of the NBT sounds like either the loot table is being altered or for some reason the tile entity isn't being passed to it.

The band reverting to white, assuming it was all white to begin with, sounds like the client is processing the change normally and updating the renderer, but the server is having the click canceled thus the code doesn't change. So the following click updates the status to the client causing the band to be white again.

Actually this might be the root issue. If the server side click event is being blocked the network will always be public and the code will be all white.


Side Note:
Upgrades have always existed, there was a bug in a few builds that broke applying upgrades on servers though.
Configs still have the ability to set the min and max.

**Comment by iLLHunter** [comment]
No worries. Ender Storage has been updated.
