### ISSUE TITLE
Incompatible with Quilt

### ISSUE THREAD

**Issue by MaliciousZoroark** [ShetiPhian/Localizations-and-Issues#355]
**Describe the bug**
Possibly one of the tamest bugs ever. Crashes on startup using quilt because you have characters "[" and "]" in your file names

**Additional context**
Minecraft Version: 1.18.2
Quilt Version : 0.17.0
ShetiPhian Core Version: 
shetiphiancore-[fabric]-1.18-1.2.10.jar
My Mod(s) Name & Version: 
Are other mods present? Yes
If yes:
Works without your mod

PasteBin or GitHub Gists links
latest.log = 
debug.log =

**Comment by ShetiPhian** [comment]
While I will not be making builds for a 3rd launcher, and will not be providing support for any bugs the Fabric builds have on Quilt, this is a simple and reasonable request/fix.

Future 1.18 and all 1.19 builds will not contain the square brackets.
