### ISSUE TITLE
Incompatible with MineGate MoreBlocks mod

### ISSUE THREAD

**Issue by atomiicos** [ShetiPhian/Localizations-and-Issues#356]
**Describe the bug**
Shetiphancore and any mods that use it are incompatible with [Minegate . More Blocks](https://www.curseforge.com/minecraft/mc-mods/minegate)
Items from Multibeds will be invisible while any MineGate blocks will appear as purple and black squares in the inventory

**Additional context**
Minecraft Version: 1.18.1
Fabric Version: (cant remember how to find this, will update if I figure this out)
ShetiPhian Core Version: v1.2.4
My Mod(s) Name & Version:  ShetiPhianCore v1.2.4, MultiBeds v1.2.2
Minegate Info: v1.1.8 by Mr.FantiVideo

**Comment by Brittank88** [comment]
Should link [this comment](https://github.com/MrFantiVideo/MineGate/issues/33#issuecomment-1152220027) from the Minegate dev explaining the likely cause.

**Comment by MrFantiVideo** [comment]
The issue comes from Myron #310 and the author of Myron had to close the [issue](https://github.com/Haven-King/myron/issues/5) in relation to that.

**Comment by Footage2-Amply-Pounce** [comment]
> The issue comes from Myron #310 and the author of Myron had to close the [issue](https://github.com/Haven-King/myron/issues/5) in relation to that.

I don't think this is the same issue as the one I had. It was fixed a while ago. Unless it's somehow broke again in 1.18.1, I suspect it's caused by something else, as the issue is not reproducible in 1.18.2.
