### ISSUE TITLE
Invisible beds

### ISSUE THREAD

**Issue by bobaa-tea** [ShetiPhian/Localizations-and-Issues#357]
As I said
The beds are not visible.

**Comment by ShetiPhian** [comment]
If this is on Fabric, a mod in your pack is breaking the Fabric Rendering API

**Comment by notmaroun** [comment]
On Fabric too, and beds are invisible on servers. I'm running AOF5. What's weird is this is only serverside, not clientside. Promenade Doors/Trees also have similar issues when summoned.

I'm convinced its a mod breaking them both - I just don't know what. Can I get your modlist @bobaa-tea? Here is mine:

[promenadebygbuglist.txt](https://github.com/ShetiPhian/Localizations-and-Issues/files/8991987/promenadebygbuglist.txt)
