### ISSUE TITLE
Crash with ShetiPhianCore 3.10.10

### ISSUE THREAD

**Issue by jburrows82** [ShetiPhian/Localizations-and-Issues#358]
**Describe the bug**
Generated new world, started exploring and then have a crash (immediately when re-loading the world). Disabling ShetiPhianCore & Endertanks lets me back into the world with no crash. 

>
[14Jun2022 23:35:32.598] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: Cannot invoke "java.util.function.Supplier.get()" because "this.val$stripped" is null
	Index: 2
	Listeners:
		0: NORMAL
		1: net.minecraftforge.eventbus.EventBus$$Lambda$4077/0x00000008019bc438@6f2dfc10
		2: ASM: shetiphian.core.internal.EventHandler@3288494e onApplyBonemeal(Lnet/minecraftforge/event/entity/player/BonemealEvent;)V
		3: ASM: mob_grinding_utils.events.ChickenFuseEvent@53ba4794 startChickenFuse(Lnet/minecraftforge/event/entity/living/LivingEvent;)V.
java.lang.NullPointerException: Cannot invoke "java.util.function.Supplier.get()" because "this.val$stripped" is null

<hr>

**Additional context**
Minecraft Version:  1.18.2
Forge Version: 40.1.51
ShetiPhian Core Version: 3.10.10 (latest on CF)
My Mod(s) Name & Version: EnderTanks 1.18.2-1.11.17 (latest on CF)
Are other mods present? Yes
If yes:
- Does everything work without my mods? **Yes**
- Have you tested with only my mods? **No**, only started with latest version.

PasteBin or GitHub Gists links
latest.log = https://gist.github.com/jburrows82/223bcd3c9326da3fe0d00c9337bf5446
debug.log = https://gist.github.com/jburrows82/5e13df468056da9894f89180be8a49d5

**Comment by ShetiPhian** [comment]
Looks like a Hummingbird form Alexs Mobs is bonemealing something. (not the issue, just start of events)
Triggering my bone meal handler, which is having a compatibility issue with something in Project Vibrant Journeys.

Until I get that corrected, in the ShetiPhianCore config, disable the "bonemeal_restores_bark" option.
(It worked fine in tests but all of those logs where strippable, this is likely an issue when a log isn't and my currently handler doesn't properly handle it)

**Comment by ShetiPhian** [comment]
This should be fixed in the latest builds just submitted to Curse.
