### ISSUE TITLE
[1.11.2] [Terraqueous 1.11.0-1.3.5] Server crashing due to entity 

### ISSUE THREAD

**Issue by shortybsd** [ShetiPhian/Localizations-and-Issues#36]
Minecraft 1.11.2
Forge 2223
Terraqueous 1.11.0-1.3.5

Server crashed while standing on the ground in normal chunks, not due to exploring. I guess a zombie collided with a cloud? 
Error Report: http://pastebin.com/3AJWHLpX

**Comment by ShetiPhian** [comment]
It appears I caused this back at the beginning of December when large chunks of the cloud walk system was rewrote.
I made it purely server side and enabled mobs to have cloud walk, but it seems like I ended up using a few client only methods.

**Comment by ShetiPhian** [comment]
1.11.0-1.3.6 was just uploaded to Curse
I ran it on a server and dropped mobs onto clouds and nothing died.... except for the mobs that fell over 100 blocks and hit the ground.

**Comment by shortybsd** [comment]
Thank you once again sir. By far one the best Minecraft mod developers out there for sure. Love your work.
