### ISSUE TITLE
Stacker Mod Compatibility

### ISSUE THREAD

**Issue by ardissaps** [ShetiPhian/Localizations-and-Issues#361]
Whenever we leaver more than 64 stacked item on the Platform table and opened again, the stack will displayed as 64 pieces. I actually insert 995 pieces, but when returned to inventory it back again to original 995 value. So it mean the issue is the number is displayed 64 when we first open the inventory again (display glitch).
![image](https://user-images.githubusercontent.com/82106625/180340018-9ad0bee9-6d57-467c-9965-935e66d22b10.png)
[Stacker](https://modrinth.com/mod/stacker)

**Comment by ShetiPhian** [comment]
Looks like its in my base inventory class.
When I wasn't limiting the stack size I defaulted to 64 as it was the games default.
Instead of hardcoding that, if I defer to the interfaces default method it would that value, be it the default 64 or whatever a mod changes it to.

**Comment by ardissaps** [comment]
Maybe can be changed to like 10K? Personally I only use 995x stack size. But the function is no problem, only display glitch, the amount is back like in original when removed from table to inventory.

**Comment by ardissaps** [comment]
@ShetiPhian I found out it is not only display glitch, the value actually messed up, tested on survival mode.
To reproduce :
- Install Stacker mod, set max item stack to 995x or any
- Install Platform mod

1. Play Creative Mode
2. Get material with max stack, then insert whole stack to Platformer table
3. Switch to Survival
4. The amount is reduced to 64

**Comment by ShetiPhian** [comment]
https://www.mediafire.com/file/9pjesw5gp50b47z/shetiphiancore-fabric-1.18-1.2.13--TESTER2.jar/file
^ fresh out of the compiler, untested but should support >64 stacks


As for the new info:

I thought it was odd that it was just a display glitch.
setStack is called to add to the inventory, and it has a stacksize check
```
if (!stack.isEmpty() && stack.getCount() > getMaxCountPerStack()) {
  this.contents[slotId] = stack.split(getMaxCountPerStack());
} else {
  this.contents[slotId] = stack;
}
```
getMaxCountPerStack was set to 64
so any stack > 64 should have only inserted 64 and the remainder stayed in the original inventory


The vanilla SimpleInventory just outright deletes excess
```
if (!stack.isEmpty() && stack.getCount() > this.getMaxCountPerStack()) {
  stack.setCount(this.getMaxCountPerStack());
}
```
That may be a clue.

Does this happen with both drag & drop, and shift-click insertion or just one of them?

**Comment by ardissaps** [comment]
> Does this happen with both drag & drop, and shift-click insertion or just one of them?

The **display only glitch** happen when we close and open again the crafting GUI.
The **real glitch** happen when we craft any product from the GUI.

**Comment by ShetiPhian** [comment]
So I know what is going on.
Client sync, crafting, insertion via mouse, and shift-click insertion into an empty slot, all validate the stack size is less or equal to the slots maximum (which checks the inventory maximum)

Shift-click has a quirk and bug.
the quirk: if the stack isn't fully used it runs again
the bug: when trying to stack the item with another it only checks max stack size, not once validating the slots.

So what happens:
On Shift-click the >64 stack ends up fully inserted. Either by stacking into an existing item or by first placing 64 into an empty slot then taking a second pass and stacking the rest into the first 64. (resulting in too many items in the slot)
When the GUI is reopened the stack data is sent and anything over the maximum is trimmed. (resulting in the visual glitch)
Crafting has redundant code, after decrementing the stack it sets it back to the slot. (resulting in the stack being limited to the slots maximum on craft)

https://www.mediafire.com/file/8lb2fxmvzb2q8az/shetiphiancore-fabric-1.18-1.2.13--TESTER3.jar/file
- maximum default stack size no longer hardcoded as 64 (will pick up change made to parent class)
- custom insertItem code that checks the slot maximum when stacking items

The redundant code in Platforms can be removed later as the fixes in ShetiPhianCore stop it from being an issue.

**Comment by ardissaps** [comment]
Thanks it now works with stacker with latest version of ShetipianCore.
