### ISSUE TITLE
Crash when hovering over some items in Trinket slots and chests (java.lang.IllegalArgumentException: Unknown TooltipComponent)

### ISSUE THREAD

**Issue by CookieGD** [ShetiPhian/Localizations-and-Issues#363]
**Describe the bug**
The game crashes when hovering over a Band of Mana (Botania) in the Ring Trinket slot and when hovering over Wither Skulls. 

**Additional context**
Minecraft Version: 1.18.2
Fabric Version: Loader version 0.48.0 + API 0.58.0
ShetiPhian Core Version: 1.2.12
My Mod(s) Name & Version: https://www.curseforge.com/minecraft/modpacks/sky-fabrication-3
Are other mods present?
If yes:
- Does everything work without my mods? Not sure as it's present in older versions of the modpack
- Have you tested with only my mods?

PasteBin or GitHub Gists links
latest.log = https://pastebin.com/cL4pp6g2
debug.log = none

**Comment by ShetiPhian** [comment]
Bit of a hot issue today ;)
https://github.com/ShetiPhian/Localizations-and-Issues/issues/360
https://github.com/ShetiPhian/Localizations-and-Issues/issues/362

I didn't expect mods to return, what vanilla deems, invalid data from getTooltipData
Mojang coded TooltipComponent.of to crash if the passed data wasn't an instance of BundleTooltipData
So like the vanilla renderer I didn't code a check to make sure it was "valid"

https://www.mediafire.com/file/19skdt2vd5590tz/shetiphiancore-fabric-1.18-1.2.13--TESTER.jar/file
You can use that build for now, it stops the crash but the mod added data that causes it won't be rendered.
OR in the current build you can disable the tooltip wrapper via the client config.

When I get the time I'll be reworking it so it's more compatible.

**Comment by CookieGD** [comment]
I just downgraded to .11 and it works perfectly fine, maybe MSandro will use .13 in the next update of his modpack tho :)
