### ISSUE TITLE
No data fixer registered for shetiphiancore:gui_item

### ISSUE THREAD

**Issue by ardissaps** [ShetiPhian/Localizations-and-Issues#364]
**Describe the bug**
Found little error :
[Render thread/ERROR] No data fixer registered for shetiphiancore:gui_item

Full Log : 
https://paste.atlauncher.com/view/3dfea829-a191-4dae-9093-d96197b48ef2

**Comment by ShetiPhian** [comment]
You'll see this warning from several mods.
It happens when there is no data fixer to register, generally because there is no data saved thus nothing to fix between versions.
Its safe to ignore.

**Comment by ardissaps** [comment]
Ok, thank you.
