### ISSUE TITLE
Light go through Ramp and some question.

### ISSUE THREAD

**Issue by ardissaps** [ShetiPhian/Localizations-and-Issues#365]
The light go through ramp with shaders on.
![image](https://user-images.githubusercontent.com/82106625/180640422-2c3f35ef-f6e7-4f06-82db-111154d80807.png)

Also, How do we put rail on ramp?

**Comment by ShetiPhian** [comment]
Allowing light to pass through was a compromise to a bigger issue without needing to edit vanilla code.
(though edits where done with bytecode asm then, now we have mixins which are easier to write and update)
I don't remember what the original issue was anymore.

Right-Click with the addon to apply. (the offhand wrench preview also shows addon placement)
Rise and Rail can be applied to Flat, Floor, or Ramp as long as the under structure is visible.
Frames have a light upgrade via a Torch (normal/redstone/soul) and that can be upgraded via glowstone dust

**Comment by ardissaps** [comment]
> Right-Click with the addon to apply. (the offhand wrench preview also shows addon placement)
> Rise and Rail can be applied to Flat, Floor, or Ramp as long as the under structure is visible.
> Frames have a light upgrade via a Torch (normal/redstone/soul) and that can be upgraded via glowstone dust

Does the rail mean the one that we can put minecart on?

**Comment by ShetiPhian** [comment]
There are two handrails in Platforms;
Rise which are rough construction in appearance, and can be seen in the mineshaft image.
Rail is more traditional in appearance, and are in the wooden coaster image.

The Minecart rails are on top of the Frame platform.
Basically impossible to see that in the wooden coaster image. It can be seen in the mineshaft one but even then you need to view the original image as the one embedded in the description is too small.
(either via right click option or clicking it in the screenshots tab https://www.curseforge.com/minecraft/mc-mods/platforms/screenshots)

I asked Fruzstrated if he remembered what issue the ramps had; Not only couldn't he remember but the it never crossed his mind as all other roof block mods he has used did the same thing, so he figured it was just part of the game.

Typing this out has sparked a memory; I remember rain and snow passing through ramps, and having snow build up inside of your house. But maybe that was a different issue.
