### ISSUE TITLE
Crash report platforms

### ISSUE THREAD

**Issue by lostopkk** [ShetiPhian/Localizations-and-Issues#367]
**Describe the bug**
Crash report

**Additional context**
Minecraft Version: 1.19
Forge Version: 
ShetiPhian Core Version: 1.3.1
My Mod(s) Name & Version: 

PasteBin or GitHub Gists links
latest.log = https://www.toptal.com/developers/hastebin/japojoseme.properties
debug.log =

**Comment by ShetiPhian** [comment]
Related issue: https://github.com/ShetiPhian/Localizations-and-Issues/issues/366
