### ISSUE TITLE
Hand Rail Z-Fight Texture

### ISSUE THREAD

**Issue by ardissaps** [ShetiPhian/Localizations-and-Issues#368]
Z-Fight when we watch from other edge of block below that. (1.18.2 Fabric)
![image](https://user-images.githubusercontent.com/82106625/181695679-4757abc4-01d2-45b8-abff-5b59179c6a6f.png)

Maybe can be moved a little deeper instead  in very edge?

**Comment by ShetiPhian** [comment]
Fruzstrated overhauled the models for the recent builds.
