### ISSUE TITLE
 [Bug]: External Storage on Ender Tank breaks RS network

### ISSUE THREAD

**Issue by TheonlyTazz** [ShetiPhian/Localizations-and-Issues#369]
### Describe the bug

Attaching an external storage from Refined Storage to an Ender Tank causes the Refined Storage system to not allow the player to pull any items out of it. Problem was resolved when external storage on the tank was removed. All other external storages working just fine. You can insert items into the system but there is a slight desync in the fact that even if the item already exists in the system, the items you deposit show as a different item stack in the grid. Tried with both an empty and full ender tank. 

### Steps to reproduce

1. Attach external storage to ender tank using pre-existing RS network. 
2. Open refined storage network via grid or wireless grid. 
3. can not pull items out, de-sync of items. 

### Expected behaviour

expected external storage to read fluid data from ender tank and recognize the tank as valid fluid storage for the system to access. 

**Additional context**
Minecraft Version:  1.18.2
Forge Version: 40.1.68
ShetiPhian Core Version: 3.10.10
My Mod(s) Name & Version: EnderTanks 1.11.7
Are other mods present?
If yes:
- Does everything work without my mods?
    yes
- Have you tested with only my mods?
   no

This issue was posted on the FTB Modpacks Issue Tracker, found in Direwolf20 1.18 v1.8.0 but possibly in every other pack that has RefinedStorage and Endertanks
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1203

**Comment by ShetiPhian** [comment]
Can you reproduce this problem with just EnderTanks and RefinedStorage?
If so please explain the setup used, as I wasn't able to.

I have a Grid on top of a Creative Controller, and a Fluid Grid beside the Grid.
A single Cable runs from the controller and splits to two External Storage, one connected to a chest and configured for items, the other to the top of an EnderTank and configured for fluids.
I can see and manipulate the item storage from the Grid, and see the and add fluid at the Fluid Grid.

**Comment by TheonlyTazz** [comment]
@ShetiPhian i actually just tried it with just RS and Endertanks and could not replicate it either.
Still curious why it borks on the Direwolf20 pack

**Comment by ShetiPhian** [comment]
Is there a mod in the pack that adds Mekanism gas/pigment/slurry support to
RS?
Might be some kind of conflict there. The EnderTanks config file has an
option to disable Mekanism support.
