### ISSUE TITLE
Embroidery Tool crash

### ISSUE THREAD

**Issue by darthvader45** [ShetiPhian/Localizations-and-Issues#370]
**Describe the bug**
Had an outofmemoryerror when using the fill tool part of the embroidery tool.  Sure, I was running a 32x resource pack and Chocapic's Extreme Shaders, but really.  A simple MSPaint-like program causing an outofmemory error with 8GB maximum allocated?  Seems a bit odd.

**Additional context**
Minecraft Version: 1.16.5
Forge Version: 1.16.5 = 36.2.39
ShetiPhian Core Version: 3.8.15
My Mod(s) Name & Version: MultiBeds 1.16.5 - 1.7.15
Are other mods present?
If yes:
- Does everything work without my mods?
- Have you tested with only my mods?

PasteBin or GitHub Gists links
latest.log = 
debug.log =
https://paste.ee/p/GUZrN

**Comment by ShetiPhian** [comment]
Your java instance had to be riding the very edge of its heap memory, at the time the fill was triggered.

The array being copied is a list of pixels that need to be checked, and the reference is removed once processed.
It branches out from the clicked pixel, tracking neighbors of the same color.
Even it it manages to run back on itself (two pixels having the same neighbor) it won't add one that has been processed.

Figuring the very worst case, with no location being removed, the array would have:
(30x30 pixels with x4 neighbors) + (30pixels x4 edges x3 neighbors) + (4 corners x2 neighbors)
3600 + 360 + 8 = 3968 values

so an array of 3967 being copied into a new array of 3968
7935 integers, at 32bits each 253,920bits = 31,740bytes so about 31kb even adding the array overhead this is still less then a megabyte.

If the heap wasn't already full, some bazar edge case would have had to happen causing the scan to get stuck in a loop adding the locations tens of thousands of times before enough memory was used, and there would have been a lag spike to go with it.
I can think of a couple of extra checks I could add to eliminate that possibility.

**Comment by darthvader45** [comment]
Thanks, I increased the amount of RAM that I had allocated, and hopefully this problem won't occur again.  Gotta remember to be a bit careful as well with the fill tool.

**Comment by ShetiPhian** [comment]
I was working on this the other day and triggered a similar crash.
Ended up double clicking with the fill tool, turns out while the scan code was alright the start code didn't verify the colors where different, resulting in the scan getting stuck.

I've uploaded new builds to Curse.

**Comment by darthvader45** [comment]
Thank you, I'll try working on new bedsheets for my world.
