### ISSUE TITLE
hey i need help this mod crashes

### ISSUE THREAD

**Issue by narendranlkook** [ShetiPhian/Localizations-and-Issues#375]
hey i have a problem this mod crashes when i add them  
can you help me 

My:
Minecraft Version: 1.18.2 forge
Forge Version: lastest version
ShetiPhian Core Version: 1.18-3.10.10
My Mod(s) Name & Version:  it is very big i cant tell
Are other mods present?
If yes: 
![image](https://user-images.githubusercontent.com/106260614/194757757-156e649b-2ce4-43b6-87e5-c5bf17b38dda.png)
![image](https://user-images.githubusercontent.com/106260614/194757784-7d94ed12-1240-4e6c-b550-85b691f9b4d5.png)
![image](https://user-images.githubusercontent.com/106260614/194757799-a8340a9e-a020-4347-9cb7-23cbf8f7830b.png)
![image](https://user-images.githubusercontent.com/106260614/194757819-78e60f93-442d-4ae3-aff9-b9fc7b5718a9.png)
total 109 mods

- Does everything work without my mods? yes
- Have you tested with only my mods? i tested with and without but i think one of my mods is not supported can you find it 
- if you found it thankyou

**Comment by ShetiPhian** [comment]
After it crashes copy the 'latest.log' to PasteBin or GitHub Gist and post the URL here.
