### ISSUE TITLE
Wrong file uploaded to CurseForge

### ISSUE THREAD

**Issue by Footage2-Amply-Pounce** [ShetiPhian/Localizations-and-Issues#377]
The latest ShetiPhian Core for fabric was uploaded to the wrong page, messing up auto-updating in launchers: https://www.curseforge.com/minecraft/mc-mods/platforms-fabric/files/4053279

**Comment by ShetiPhian** [comment]
Well it was bound to happen eventually, though I figured it would be a Forge/Fabric error not a completely different mod.

I've submitted the correction to Curse, just have to wait now.
Shouldn't be an issue for Platforms as it was a normal upload, but ShetiPhianCore may require manual moderator action as the file was uploaded before.
