### ISSUE TITLE
1.19.2 - server world startup out of bounds index array crash terraqueous-1.19-1.10.0

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [ShetiPhian/Localizations-and-Issues#378]
**Describe the bug**

During server startup worldgen sometimes fails due to out of bounds index array.

**Additional context**
Minecraft Version: 1.19.2
Forge Version: 43.1.47
ShetiPhian Core Version: shetiphiancore-1.19-3.11.0
My Mod(s) Name & Version: Modpack - Fiction Friction 8GB version 21.0.0
Are other mods present?

Don't know I have a modpack to run I am just reporting it because my friend Thutmose says even if players don't give people don't test a bunch info is info. Back to work - hope this helps. Please note you should be able to test on latest version as the next patch I put out will not have your mod and also I am fixing a crash in my modpack.

PasteBin or GitHub Gists links
latest.log = https://gist.github.com/P3rf3ctXZer0/dba38742aac833864abd21978cfcd1dd
debug.log = https://gist.github.com/P3rf3ctXZer0/93ac1f283462304ffc735f87435e754c

**Comment by P3rf3ctXZer0** [comment]
https://github.com/P3rf3ctXZer0/Fiction.Friction/issues/22

**Comment by ShetiPhian** [comment]
I'm using the add method of ObjectArrayList nothing out of the ordinary there, and the crash is happening a few steps into its code.
Looking over the libraries code, the tracked size must be larger then the backed array to cause that crash, but none of their methods appear to cause that to happen. 
I figure either 1.19.2 uses a different build of the fastutil library which has a bug, or something else is directly altering the internal values.

I'll add an error handler; looks like I can use a couple of methods in ObjectArrayList to resync the values, which might not be a bad idea, could stop something else from crashing later.

If you plan on re-adding the mod later, the structure generation can be disabled in the config file by setting everything to false under "world_gen > structures" (saves worlds from loosing blocks and items)

**Comment by P3rf3ctXZer0** [comment]
Hm let me see what I can dig up too I am about to remove all my performance mods too because ever since I added pluto I think things are going awry with chunk manager in general. Unless something off topic this stands out to you in some way.

https://gist.github.com/P3rf3ctXZer0/e0482de9a5242d6004a9e382f4f98840 I am stumped.

**Comment by P3rf3ctXZer0** [comment]
I don't have time to test sorry. Good luck on your mods.
