### ISSUE TITLE
"door must be placed in a 2x2 or 3x3 opening that is framed with vault blocks"

### ISSUE THREAD

**Issue by Saphrym** [ShetiPhian/Localizations-and-Issues#38]
I've done it in creative. I've done it in survival. I leave a 2x2 or 3x3 opening in a hollow cube made of vault wall blocks and I get that error every time I try to place a vault door.

MultiStorage v. 1.2.14
ShetPhianCore v. 3.3.7

**Comment by ShetiPhian** [comment]
I don't remember changing anything with door placement.
Did this just start with 1.2.14?
Are you in 1.11.0 or 1.11.2?

I'm heading off to get some sleep but will look into this tomorrow.

**Comment by Saphrym** [comment]
1.10.2 and no idea. Just installed it into a pack and tried it out for the first time.

**Comment by Saphrym** [comment]
And take your time. I'm not in a hurry. :)

**Comment by AstralDestiny** [comment]
Same here, Using 
multistorage-1.11.0-1.3.2.jar
 on 1.10.2, 
Using Latest builds of the mod and core.

"Door must be placed in a 2x2 or 3x3 opening that is framed with vault blocks"

**Comment by ShetiPhian** [comment]
This is a far more sever bug then it first appeared.
I've pinpointed the cause and fixed it but need to code a repair system for existing vaults as they are not a secure as they once where.

**Comment by ShetiPhian** [comment]
1.10.0-1.2.15 and 1.11.0-1.3.4 are up on Curse

**Comment by Saphrym** [comment]
Awesome! Thanks!
