### ISSUE TITLE
Crash when attempting to use the /spc_teams_sysadmin command

### ISSUE THREAD

**Issue by TheDoctor1977** [ShetiPhian/Localizations-and-Issues#380]
I entered the command to see what it did and the game crashed before I even hit enter, crashlog can be found here.
https://mclo.gs/N8RTLrm

**Comment by ShetiPhian** [comment]
I've never tried reading team data when I knew there wasn't any so completely missed this crash scenario.

**Comment by ShetiPhian** [comment]
There is a bigger issue here then it first appears. Looking at a client server data sync issue which will require some rework to fix.
Any remote client will likely crash if trying to use a command that has team id suggestions.
For now I'll disable suggestions for remote clients until I can get the time to rework it.
"/spc_teams teams" can be used to fetch the ids so it would only be a minor inconvenience. (well less so then a crash)

I've got another bug to fix (two in fabric) before I release a new build.

**Comment by ShetiPhian** [comment]
Fixed in latest builds.
