### ISSUE TITLE
server crash 

### ISSUE THREAD

**Issue by 3dguru** [ShetiPhian/Localizations-and-Issues#383]
**Describe the bug**
causes world crash when new chunk spawn

**Additional context**
Minecraft Version:  1.19.2
Forge Version:  Fabric  loader 0.14.10  Fabric api 66.0
ShetiPhian Core Version:  1.3.3
My Mod(s) Name & Version:  ShetiPhianCore, Multibeds
Are other mods present? yes 
If yes:
- Does everything work without my mods? yes
- Have you tested with only my mods? yes 

PasteBin or GitHub Gists links
[latest.log = 
debug.log =](https://pastebin.com/BvJMyrgR)

**Comment by ShetiPhian** [comment]
Newest builds should solve this.
