### ISSUE TITLE
Planter Z-Fighting

### ISSUE THREAD

**Issue by WenXin20** [ShetiPhian/Localizations-and-Issues#384]
**Describe the bug**
Planters filled with water have  z-fighting when lily pads are planted on top. I'm not sure which mod changes the lily pad texture.

**Additional context**
Minecraft Version: 1.19.2
Forge Version: 43.1.52
ShetiPhian Core Version: 3.11.2
Terraqueous Version: 1.10.1
Are other mods present? Yes
If yes:
- Does everything work without my mods? If it does, I suspect Rubidium.
- Have you tested with only my mods? I can try later when I have more time to check.

![2022-11-24_12 26 19](https://user-images.githubusercontent.com/12000593/203848184-372228b6-f6f4-441e-969b-9c2f438249f4.png)

**Comment by ShetiPhian** [comment]
Just changing the texture wouldn't cause this.
Either the lily pad model was changed lowering it, and will also z-fight on normal water)
or something is "optimizing" rendering and for whatever reason thinks moving faces closer improves performance.
Its not something I can fix. (technically the planter could be shorter, but that will make everything look like its floating)

**Comment by WenXin20** [comment]
It doesn't have z-fighting on normal water. Although it does appear that the texture may have been lowered a teeny tiny bit. I believe this is because the water level in the planter is two pixels higher, which is where the lily pad texture is at.

![image](https://user-images.githubusercontent.com/12000593/211128673-024afd4f-0dfd-46c7-ac6c-13f137b90515.png)
