### ISSUE TITLE
[Multibeds} Incompatibility with Tofucraft

### ISSUE THREAD

**Issue by Scarlet-Phonavis** [ShetiPhian/Localizations-and-Issues#390]
**Describe the bug**
Incompatibility with Tofucraft villagers, causes server crash when they attempt to do a task.

**Additional context**
Minecraft Version: 1.19.2
Forge Version: 43.1.64
ShetiPhian Core Version: 1.19.3 - 3.11.2 
My Mod(s) Name & Version: 
multibeds-1.19-1.10.1.jar  
Are other mods present?
TofuCraftReload-1.19.2-2.8.0.0.jar 

PasteBin or GitHub Gists links
Crash and Latest, have never figured out how to enable Debug on GD, tell me if you need it
https://gist.github.com/Scarlet-Phonavis/ded3c5281834ec0fb25ccd3fff2ed54b

**Comment by ShetiPhian** [comment]
Tofucraft must be checking another POI before the Home is set, and since my code checks Home this triggers a crash.
I'll change my code to handle Home being null

**Comment by ShetiPhian** [comment]
I couldn't get the crash to happen, but the report made it clear enough.
This should be fixed in the newest builds
