### ISSUE TITLE
Fabric Versiyon

### ISSUE THREAD

**Issue by Rogenar** [ShetiPhian/Localizations-and-Issues#391]
Will Ender Tanks mod come for fabric version 1.19.3?

**Comment by ShetiPhian** [comment]
I was waiting for the fluid api to not have this message anymore:
> Experimental feature, we reserve the right to remove or change it without further notice.
> The transfer API is a complex addition, and we want to be able to correct possible design mistakes.

But its been several versions now so I've started working on it.
More or less I just need to figure out the details of Fabric fluid storage and adapt the code.

**Comment by ShetiPhian** [comment]
A Fabric build is now on Curse and Modrinth.
(though can't download from Curse yet as the new project is currently pending approval)
