### ISSUE TITLE
bug related to connecting ender tank to a Refined storage external storage

### ISSUE THREAD

**Issue by Kevengg** [ShetiPhian/Localizations-and-Issues#392]
**Describe the bug**
connecting a Refined storage external storage to the ender tank causes the Refined storage interfaces to lose functionality after searching.
don't know if this is an issue with Refined storage or EnderTanks 

Refined storage version: 1.11.4

**Additional context**
Minecraft Version: 1.19.2
Forge Version: 43.2.3
ShetiPhian Core Version: 3.11.3
My Mod(s) Name & Version: EnderTanks 1.12.1
Are other mods present?
Yes, se AllTheMods 8 modlist
If yes:
- Does everything work without my mods? Yes
- Have you tested with only my mods? 
Yes/No haven't tested much only stumbled upon the issue found it to be the ender tank

PasteBin or GitHub Gists links
latest.log = https://gist.github.com/Kevengg/837446457c03284f6a838d240528a4cf
debug.log = https://gist.github.com/Kevengg/bd1910b75143017ab6b96c478676c1fa

**Comment by ShetiPhian** [comment]
Happens in a 1.18 pack also (https://github.com/ShetiPhian/Localizations-and-Issues/issues/369)
Doesn't seem to be just EnderTanks and Refined Storage, or Mekanism, some other mod or mods are likely involved.
This bug doesn't throw an error so the log is no help in tracking it down.

I've installed the pack (minus Oculus as its mixin kept crashing while loading a world)
But even in the pack I can't trigger the bug.

I used the same test setup as the the report:
```
I have a Grid on top of a Creative Controller, and a Fluid Grid beside the Grid.
A single Cable runs from the controller and splits to two External Storage, one connected to a chest and configured for items, the other to the top of an EnderTank and configured for fluids.
I can see and manipulate the item storage from the Grid, and see and add fluid at the Fluid Grid.
```
Also tested the following setups:
- Tested Chest before Tank and vice versa
- Tank and Chest on separate cables
- Connecting to each side of the tank
- Two fluid connections on a tank (top and bottom results in double in display but correct operation)
- A fluid and item connection on same tank (item one is ignored, fluid functions normally)
- Connection on two linked tanks (same as two on a single tank)
