### ISSUE TITLE
ShetiPhian redirect mixins causing mod conflict issues on Quilt (And possible other loaders too)

### ISSUE THREAD

**Issue by TelepathicGrunt** [ShetiPhian/Localizations-and-Issues#393]
Terrestia issue report: https://github.com/TerraformersMC/Terrestria/issues/278

It appears with latest mc versions and ShetiPhian + Terrestria and/or Balm will cause Balm's mixins to blow up on Quilt. A quick look and it seems ShetiPhian make heavy use of redirect mixins which is bad for compatibility. 

Terrestria and ShetiPhian does a redirect to getAvailableMoisture which is what Balm is trying to modify variable at. 
https://github.com/TerraformersMC/Terraform/blob/1.19.3/terraform-dirt-api-v1/src/main/java/com/terraformersmc/terraform/dirt/mixin/MixinCropBlock.java

Redirects are not stackable and are an unsafe mixin. A push should be done to remove or replace all redirects with better alternatives that do not break other mod's mixins. You can even look into using MixinExtras if needed to wrap calls easier or try something similar to what balm is doing. https://github.com/LlamaLad7/MixinExtras/wiki/ModifyExpressionValue

Unless the crash can still be reproduced without a redirect, I would say the redirect here is the issue and cause. Since Terrestria also does a redirect to the same method spot and will conflict with ShetiPhian definitely so this is an issue. Just ask if you need help with figuring out how to replace the redirect mixins with safer alternative

**Comment by SplendidAlakey** [comment]
Just chiming in to say, that if the decision will be made to implement the suggested changes, please backport them to 1.19.2, if possible. I saw a note in the changelog for the latest ShetiPhianCore update on 1.19.2, stating that it will be the last build for 1.19.2, so I'll understand, if the fixes won't be backported.

**Comment by ShetiPhian** [comment]
I'd rather not add another mod as a dependency, so I'll see if I can remove all the redirects without MixinExtras first. If not I'll use it.

**Comment by ShetiPhian** [comment]
Redirect mixins are gone in the new builds.
