### ISSUE TITLE
Placing blocks onto Ender Chests or Ender Tanks via shift-clicking fails.

### ISSUE THREAD

**Issue by James103** [ShetiPhian/Localizations-and-Issues#396]
**Describe the bug**
When attempting to place a block next to an Ender Chest or Ender Tank by shift-clicking on it, the block placement fails.
Most likely during handling of the event, the item in the player's hand is checked and if it is not an ender pearl, the event gets canceled and the block placement fails.

**Additional context**
Minecraft Version: 1.19.2
Forge Version: 43.2.3
ShetiPhian Core Version: 3.11.3
EnderChests Version: 1.10.1
EnderTanks Version: 1.12.1
Originally found in modpack "All the Mods 8" version 1.0.9.
See also https://github.com/AllTheMods/ATM-8/issues/661

Log files: https://gist.github.com/James103/fc68a8e9b441286bbe9db562d4417613

**Comment by ShetiPhian** [comment]
Fixed in the new builds
