### ISSUE TITLE
Crash with "Vanilla Permissions" mod

### ISSUE THREAD

**Issue by rjuven2401** [ShetiPhian/Localizations-and-Issues#398]
Minecraft: 1.19.2
Fabric Loader 0.14.10
Fabric API: 0.67.1

Vanilla Permissions: [0.1.3](https://modrinth.com/mod/vanilla-permissions/version/0.1.3)
ShetiPhianCore: [1.3.3](https://www.curseforge.com/minecraft/mc-mods/shetiphiancore-fabric/files/4085842)

When both of the mods are present, my server stops. When only one of the mod is present, the server runs fine.
I don't know which mod causes the problem, so I also reported this issue to [Vanilla Permissions's side](https://github.com/DrexHD/VanillaPermissions/issues/6).

Here is the log file: [latest.log](https://gist.github.com/rjuven2401/e0a571d0d853214b8df16dae68e51102)

**Comment by ShetiPhian** [comment]
Vanilla Permissions has marked this as fixed, so I'll close the issue here as well.
