### ISSUE TITLE
Crashes with RFTools Liquid Monitor

### ISSUE THREAD

**Issue by Mohron** [ShetiPhian/Localizations-and-Issues#4]
EnderTanks: endertanks-1.10.0-1.4.3.jar
RFtools: rftools-1.10-5.59.jar
MJtyLib: mcjtylib-1.10-2.2.0.jar
Forge: forge-1.10.2-12.18.2.2124-universal.jar

Server crashes sometimes when a endertank is in range and always when an endertank is selected on a liquid monitor.

[Crash](http://hastebin.com/igizulobez.scala)

https://github.com/McJty/RFTools/issues/841

**Comment by ShetiPhian** [comment]
I see the issue.
If something interacts with the sides of the tank hasCapability returns true but getCapability will return null.
hasCapability should be returning false.

I'll get that fixed later today.

**Comment by ShetiPhian** [comment]
Sorry for the delay,
This build should fix your issue,
http://www.mediafire.com/file/3kdo236z9iqcw38/endertanks-1.10.0-1.4.5-test_build.jar

You'll want to back up the endertanks as I rewrote how/when the tank network loads/saves/unloads its data to fix the other reported bug.
There shouldn't be an issue but it's better to backup just in case.

**Comment by ShetiPhian** [comment]
New build is up on Curse
