### ISSUE TITLE
crash with Forge Microblocks

### ISSUE THREAD

**Issue by Meowticia** [ShetiPhian/Localizations-and-Issues#40]
There's a crash with either Terraqueous or Shetiphian Core with Forge MicroBlocks (for MC 1.10.2) when attempting to break a placed micro block.
[crash-2017-02-12_19.14.05-client.txt](https://github.com/ShetiPhian/Localizations-and-Issues/files/769797/crash-2017-02-12_19.14.05-client.txt)  Just thought I'd put this out there.  I don't know if this is something you wish to know about or not but it's a bummer because I love both mods and don't want to sacrifice either of them.

**Comment by ShetiPhian** [comment]
Looks like MicroBlocks is using the deprecated version of EntityPlayer.getDigSpeed.
I'll make some changes to handle that but it likely wont be until the weekend.

**Comment by ShetiPhian** [comment]
New build has been submitted to Curse, just waiting for the download link to become publicly available.
Note: You'll need to update ShetiPhianCore also.
