### ISSUE TITLE
MC 1.19.2 Fabric ShetiPhianCore breaks Chorus Plant functionality

### ISSUE THREAD

**Issue by EvionFox** [ShetiPhian/Localizations-and-Issues#400]
**Describe the bug**
When Shetiphian is installed, Chorus fruit are unable to grow  - the "Chorus Plant" block is unable to be stacked vertically, and all generated chorus fruit trees explode/break into fruit in the ticks that they would grow instead. I believe this is a problem specifically with the **Chorus Plant** block and something causing the hitbox to not be able to connect vertically.

**Additional context**
Minecraft Version: 1.19.2
Fabric Loader: 0.14.13
Fabric API: 0.73.2
ShetiPhian Core Version: 1.19-1.3.4

My Mod(s) Name & Version: 
Are other mods present?
- Yes
If yes:
- Does everything work without my mods?
This was run through a series of 16+ tests filtering out mods to find which one caused the chorus fruit to not grow vertically. 

- Have you tested with only my mods?
Yes. I have done a test with only Fabric API, Cloth Config, and ShetPhianCore [Fabric], and the issue occurred. I have tested it with only cloth config, with Sheti disabled, and the problem was gone. It is definitely ShetiPhianCore that is causing the bug.

PasteBin or GitHub Gists links
latest.log = https://gist.github.com/EvionFox/0d30986b133cb56470ea16a75d69f6cd
debug.log = None available

**Comment by ShetiPhian** [comment]
I've injected code changes into my 1.19.2 build that should fix this.
https://www.curseforge.com/minecraft/mc-mods/shetiphiancore-fabric/files/4390882
