### ISSUE TITLE
ShetiPhianCore causes ground crops from Croptopia and ChocoCraft to not spawn

### ISSUE THREAD

**Issue by Dreghert** [ShetiPhian/Localizations-and-Issues#401]
**Describe the bug**
With ShetiPhianCore installed, ground crops from Croptopia (58 varieties) and ChocoCraft (Ghysal Greens) do not spawn in game. In creative, you can spawn the seeds, and they grow fine if planted, but they will not spawn in the wild at all.

**Additional context**
Minecraft Version: 1.19.2
Forge Version: um, Fabric 0.73.2
ShetiPhian Core Version: 1.3.4
My Mod(s) Name & Version: Ender Chests 1.1.1
Are other mods present? Yes
If yes:
- Does everything work without my mods? Yes.
- Have you tested with only my mods? Yes. Even without Ender Chests, and just ShetiPhianCore, it does not spawn ground crops.

PasteBin or GitHub Gists links
latest.log = https://pastebin.com/GnK4GuCk
debug.log = Dont have one

**Comment by ShetiPhian** [comment]
In 1.19.2 if your not using Terraqueous fall back a version, part of the code added for it appears to have a bug.
A new 1.19.3 build will be released soon that should correct it.

**Comment by ShetiPhian** [comment]
I've injected code changes into my 1.19.2 build that should fix this.
https://www.curseforge.com/minecraft/mc-mods/shetiphiancore-fabric/files/4390882

**Comment by Dreghert** [comment]
Thank you for the quick turnaround on that issue! It is greatly appreciated!
