### ISSUE TITLE
ShetiPhianCore (Fabric) causes pistons to break nearby melon stems

### ISSUE THREAD

**Issue by RiceGnat** [ShetiPhian/Localizations-and-Issues#402]
I've build a typical automatic melon farm similar to this layout:
https://www.youtube.com/watch?v=t8cKHWohh3U

The pistons are frequently breaking the melon stems even though they are only above the spaces where the melons grow. It does not happen 100% of the time, but at a fairly high frequency.

Minecraft Version: 1.19.3
Fabric Version: 0.73.2
ShetiPhian Core Version: 1.3.3, 1.3.6 (just updated to .6 since I saw the patch from today, but no luck)
My Mod(s) Name & Version: MultiBeds, Platforms (**issue is with Core only, tested without these mods**)
Are other mods present?
Yes, tested with only Fabric API, Iris, Sodium, Mod Menu, and ShetiPhianCore (with Cloth Config). Issue does not occur without ShetiPhianCore. Tested in a fresh single player world.

PasteBin or GitHub Gists links
latest.log = https://pastebin.com/VWDMD29B
debug.log =

**Comment by ShetiPhian** [comment]
New build: https://www.curseforge.com/minecraft/mc-mods/shetiphiancore-fabric/files/4390889
I currently have it running an autofarm one side using vanilla farmland the other my planters
