### ISSUE TITLE
[Bug] EnderTanks (endertanks) encountered an error during the common_setup event phase

### ISSUE THREAD

**Issue by vertay** [ShetiPhian/Localizations-and-Issues#405]
**Describe the bug**
During the startup sequence of my Exaroton server, startup fails with the crash log providing the following error:
```
EnderTanks (endertanks) encountered an error during the common_setup event phase
java.lang.ArrayIndexOutOfBoundsException: Index 128 out of bounds for length 65

```

**Additional context**
Minecraft Version: 1.19.2
Forge Version: 43.2.6
ShetiPhian Core Version: shetiphiancore-forge-1.19.0-3.11.3.01
My Mod(s) Name & Version: endertanks-forge-1.19.0-1.12.1.01
Are other mods present?
If yes:
- Does everything work without my mods?
- Have you tested with only my mods?

Yes there are other mods present, the server is running AllTheMods 8 version 1.0.13. However I don't know how to run the tests on the server as it was automatically set up to run ATM8, I don't think I am able to make changes without breaking something.

PasteBin or GitHub Gists links
latest.log = 
debug.log =

Crash report from exaroton server: https://mclo.gs/JdLycSL
Not sure where to find latest.log or debug.log

**Comment by ShetiPhian** [comment]
Possibly a performance mods doing.
Outside of the pack; server and client run fine (I don't have the newest pack build)
The crash is inside of 'fastutil' while its copying data from one internal array to a new one
Both Minecraft's code and my own add the same way.
Prior to the crash while adding the water handler, the empty one ran successfully.

----
looks like somehow the maps tracker value 'n' is wrongfully 128  while the array its accessing 'value' only has 65 entries

----
ran a search for similar crashes and they all seem to have:  (real-size - 1) *2 = crash-value

----
looks like it might be a threading issue
explains why it doesn't happen every time, and large packs trigger it.
if that's the case its an easy fix, testing it to make sure however is the issue.

**Comment by ShetiPhian** [comment]
If you get the crash every time and have access to the mods folder you have a perfect test environment.
replace the EnderTanks jar with this one:
https://www.mediafire.com/file/hhigahpdgkopvyu/endertanks-forge-1.19.0-1.12.1.02-TESTER.jar/file

If that fixes the crash I'll upload it to Curse so the pack can update and fix it for everyone.

**Comment by vertay** [comment]
Hey, thanks for looking into it! Unfortunately I can't access the mods folder, the server hosting we're using prevents access to the folder entirely. I've tried loading it up again and it's fine this time, not sure if you pushed the fix already(?) or its just not an every time bug. If you still need it testing I could try and locally host a server and see if the same problem happens?

**Comment by ShetiPhian** [comment]
It wasn't pushed

I wasn't seeing the issue but if its not happening every time it would be hard to determine if the fix works.
But, it does make it sound more like a threading issue.
Myself and at least one other must be adding cauldron behaviors, if we land on the same thread, no issues as one just loads before the other. Different threads however if we both register at the same time the problem will occur.

I've just upload new builds to Curse.
Until it becomes available to packs and they update, your stuck on the current version. But its only an issue at setup so once everything is running your in the clear. (still sucks to need to relaunch until it does though)
