### ISSUE TITLE
Terraqueous Door item textures are inconsistent and flipped

### ISSUE THREAD

**Issue by Kitteh6660** [ShetiPhian/Localizations-and-Issues#409]
Not a bug per se but an inconsistency.

The door item textures are flipped and facing the wrong way. In addition, they are shifted up by 1 pixel. I think it would not be too hard to fix the issues.

**Comment by ShetiPhian** [comment]
Fixed in the latest builds, also contains 8 styles per door and new textures by Fruzstrated.
