### ISSUE TITLE
 Game crashed when add EnderChests [Fabric] in Create Astral

### ISSUE THREAD

**Issue by Icewater661** [ShetiPhian/Localizations-and-Issues#410]
**Describe the bug**
I add EnderChests [Fabric] in package: [Create Astral(v2.0.4)](https://legacy.curseforge.com/minecraft/modpacks/create-astral) and game crashed .

**Additional context**
Minecraft Version: 1.18.2
Fabric Version: 0.14.14
ShetiPhian Core Version: 1.2.16
My Mod(s) Name & Version: 

 ad_astra-fabric-1.18.2-1.0.9.jar
adopt-a-floppa-1.1.0.jar
alternate-current-mc1.18-1.4.0.jar
AmbientEnvironment-fabric-1.18.2-7.0+19.jar
another_furniture-fabric-1.2.2-1.18.2.jar
appleskin-fabric-mc1.18.2-2.4.1.jar
appliedenergistics2-fabric-11.7.1.jar
architectury-4.11.90-fabric.jar
astraladditions-1.2.0.jar
astralvinery-1.1.1.jar
autoconfig1u-3.4.0.jar
automobility-0.3+1.18.2.jar
auudio_fabric_1.0.3_MC_1.18-1.18.2.jar
badpackets-fabric-0.1.3.jar
bakadanmaku-fabric-1.18.2-2.0.1.jar
balm-fabric-3.2.1+0.jar
BetterAdvancements-Fabric-1.18.2-0.2.0.146.jar
bettercombat-fabric-1.6.2+1.18.2.jar
campanion-3.0.3.jar
camsbackpacks-2.2.jar
cardinal-components-api-4.2.0.jar
catwalks-inc-1.3.0.jar
cc-restitched-1.100.8.jar
cccbridge-1.3.1-fabric.jar
cem-0.7.1_S8_1.18.jar
Chassis-Fabric-1.1.0.jar
chat_heads-0.6.0-fabric-1.18.1.jar
chipped-fabric-1.18.2-2.0.1.jar
Chunky-1.2.164.jar
CITResewn-1.1.1+1.18.2.jar
cloth-config-6.4.90-fabric.jar
Clumps-fabric-1.18.2-8.0.0+17.jar
cobblegen-v2.1b57-BETA.jar
Companion-1.18.2-fabric-2.0.1.jar
completeconfig-lib-1.4.1.jar
Compressor-Fabric-0.2.0.jar
continuity-2.0.1+1.18.2.jar
cookingforblockheads-fabric-1.18.2-12.2.0.jar
create-fabric-0.5.0.i-988+1.18.2.jar
createaddition-fabric+1.18.2-20230211a.jar
createdeco-1.2.13-1.18.2.jar
createsifter-1.18.2-1.3.3.g.jar
ctm-fabric-1.0.0+1.18.jar
CullLessLeaves-1.0.1.jar
CustomMachinery-fabric-1.18.2-0.7.6.jar
datapackportals-1.1.1-1.18.jar
dbe-1.18.2-1.0.0.jar
debugify-1.11.0-fabric-1.18.2.jar
disable-trading-0.1.1.18.2.jar
DisableCustomWorldsAdvice-2.0.jar
disableportals-0.2.0-1.18-github-fork.jar
doodads-0.1.2-github-fork.jar
drinkbeer-3.2.0-1.18.2.jar
drippyloadingscreen_fabric_1.6.6_MC_1.18-1.18.2.jar
dustrial-decor-fabric-0.5.jar
ears-fabric-1.17-1.4.5_01.jar
enderchests-fabric-1.18-1.0.12.jar
entity_texture_features_fabric_1.18.2-4.3.1.jar
environmentalcreepers-fabric-1.18.0-1.6.0.jar
ExplorersCompass-1.18.2-2.2.0-fabric.jar
extendedflywheels-1.18.2-0.5.0.g-1.2.5.1.jar
extractinator-fabric-1.18.2-2.0.1.jar
fabric-api-0.76.0+1.18.2.jar
fabric-carpet-1.18.2-1.4.69+v220331.jar
fabric-language-kotlin-1.9.3+kotlin.1.8.20.jar
fallingleaves-1.11.1+1.18.2.jar
fancymenu_fabric_2.13.3_MC_1.18.2.jar
farmers-delight-fabric-1.18.2-1.2.5.jar
fastfurnace-1.18.2-4.1.jar
Fastload+1.18.2-1.5.10.jar
ferritecore-4.2.1-fabric.jar
fm_audio_extension_fabric_1.1.1_MC_1.18-1.18.2.jar
ForgeConfigAPIPort-v3.2.4-1.18.2-Fabric.jar
ftb-chunks-fabric-1802.3.16-build.247.jar
ftb-library-fabric-1802.3.11-build.177.jar
ftb-quests-fabric-1802.3.14-build.191.jar
ftb-teams-fabric-1802.2.10-build.96.jar
ftbbackups2-fabric-1.18.2-1.0.18.jar
GearReborn-1.18.2-0.1.14.jar
geckolib-fabric-1.18-3.0.80.jar
global_packs-fabric-1.18.2-1.12.3_fabric.jar
harvestwithease-1.18.2-4.0.0.2-fabric.jar
Hephaestus-1.18.2-3.5.2.155.jar
Iceberg-1.18.2-fabric-1.0.38.jar
idwtialsimmoedm-0.1.1+1.18.jar
ImmediatelyFast-1.1.10+1.18.2.jar
immersive_aircraft-0.3.0+1.18.2-fabric.jar
indium-1.0.7+mc1.18.2.jar
InventoryProfilesNext-fabric-1.18.2-1.3.8.jar
InventoryProfilesNext-fabric-1.18.2-1.9.1.jar
iris-flywheel-compat-1.18.2-0.1.9-BETA.jar
iris-mc1.18.2-1.5.2.jar
item-filters-fabric-1802.2.8-build.47.jar
itemscroller-fabric-1.18.2-0.16.0.jar
Jade-1.18.2-fabric-5.99.10.jar
JadeAddons-1.18.2-fabric-2.0.1.jar
jmi-fabric-1.18.2-0.13-32.jar
journeymap-1.18.2-5.9.4-fabric.jar
konkrete_fabric_1.6.0_MC_1.18-1.18.2.jar
krypton-0.1.9.jar
kubejs-create-fabric-1802.2.2-build.28.jar
kubejs-fabric-1802.5.5-build.567.jar
lazydfu-0.1.2.jar
letmedespawn-1.18.x-1.19.x-fabric-1.0.2.jar
libIPN-fabric-1.18.2-2.0.1.jar
limitedchunks.fabric-1.18.2-2.5.jar
litematica-fabric-1.18.2-0.11.3.jar
lithium-fabric-mc1.18.2-0.10.3.jar
loadmyresources_fabric_1.0.4_MC_1.18-1.18.2.jar
lootr-1.18.2-0.3.24.61.jar
malilib-fabric-1.18.2-0.12.1.jar
MasaGadget-1.18.2-2.0.9.1.jar
mcdw-5.0.4-1.18.jar
memoryleakfix-fabric-1.17+-1.0.0.jar
midnightlib-0.4.4.jar
minihud-fabric-1.18.2-0.22.0.jar
mixintrace-1.1.1+1.17.jar
modmenu-3.2.5.jar
mysticaloaktree-1.18.2-1.0-fabric.jar
naturalist-fabric-1.1.1-1.18.2.jar
numeralping-1.0.3.jar
observable-2.2.3-fabric.jar
packages-fabric-1.18.2-3.4.jar
packed-inventory-0.2.2+1.18.2.jar
passivepiglins-1.0.1.jar
per_aspera-1.3.2.jar
phonos-0.3+1.18.2.jar
Ping-Wheel-1.2.0-fabric-1.18.2.jar
player-animation-lib-fabric-1.0.2+1.18.jar
polaroidcamera-1.2.9.jar
polymorph-fabric-0.0.21-1.18.2.jar
projectiledamage-fabric-2.2.0+1.18.2.jar
puzzle-1.4.1-1.18.jar
PuzzlesLib-v3.3.5-1.18.2-Fabric.jar
quarry-reborn-1.18.2-0.7.3.jar
questsadditions-fabric-1.18.2-1.4.1.jar
reeses_sodium_options-1.4.9+mc1.18.2-build.66.jar
reinforced-chests-2.2.0+1.18.jar
rer-2.5.0.jar
rhino-fabric-1802.2.1-build.255.jar
RoughlyEnoughItems-8.3.588.jar
searchlight-1.18-fabric-1.1.7.jar
servercore-1.2.9-1.18.2.jar
servertick-mc1.18-1.6.jar
shetiphiancore-fabric-1.18-1.2.16.jar
ShowMeWhatYouGot-1.18-1.0.1.jar
smoothboot-fabric-1.18.2-1.7.0.jar
smoothchunk-fabric-1.18.2-1.9.jar
sniffer-fabric-1.18.2-1.1.2.jar
sodium-extra-0.4.16+mc1.18.2-build.89.jar
sodium-fabric-mc1.18.2-0.4.1 (replaymod compatible).jar
spark-1.9.11-fabric.jar
starlight-1.0.2+fabric.89b8d9f.jar
subterrestrial-fabric-1.18.2-2.0.0.jar
suggestion-tweaker-1.18.2-1.3.0-fabric.jar
TechReborn-5.2.1.jar
tooltipfix-1.0.4-1.18.jar
towns_and_towers_fabric-1.10.0.1+1.18.2.jar
trinkets-3.3.1.jar
tweakeroo-fabric-1.18.2-0.13.3.jar
twilightforest-fabric-1.18.2-4.1.313.jar
vinery-1.1.4.jar
WI-Zoom-1.4-MC1.18.2.jar
worldedit-mod-7.2.10.jar
xlpackets-3.1-1.18.2.jar
youre-in-grave-danger-1.3.13.jar

Are other mods present? Yes
If yes:
- Does everything work without my mods? Yes
- Have you tested with only my mods?Yes

PasteBin or GitHub Gists links
latest.log = 
[latest.log](https://github.com/ShetiPhian/Localizations-and-Issues/files/11860761/latest.log)

debug.log =
[crash-2023-06-26_03.49.32-client.txt](https://github.com/ShetiPhian/Localizations-and-Issues/files/11860762/crash-2023-06-26_03.49.32-client.txt)

**Comment by Icewater661** [comment]
I found the promblem.This mod is conflict with the mod .[Packed Inventory](https://www.curseforge.com/minecraft/mc-mods/packed-inventory) After I delete it,this mod works Well.

**Comment by ShetiPhian** [comment]
Currently the lookup database uses the world, but that fails when another mod tries to access the inventory when the tile entity has no world (likely due to checking too soon or accessing a cached entity that has been unloaded)

I've got an untested fix (rewrote code so the world wasn't needed) in the 1.20.1 port I'm working on. 1.18 will get the fix backported to it and will be uploaded at the same time as 1.20.
