### ISSUE TITLE
[modrinth] 1.19.2 support

### ISSUE THREAD

**Issue by ColonelGerdauf** [ShetiPhian/Localizations-and-Issues#413]
It will be nice for the mods, including the Core, to include support for 1.19.2 on Modrinth. That version has much better support in modpacks and has a wider userbase than 1.19.4.

Unfortunately, 1.19 is strange in its volume of breaking updates across sub-versions.

**Comment by ShetiPhian** [comment]
I've resumed support for 1.19.2 Fabric and backported to it (including EnderTanks and Terraqueous, which originally where not on 1.19.2)

With that done Modrinth now has 1.19.2 Forge & Fabric builds available.

**Comment by ColonelGerdauf** [comment]
Platforms is still absent a 1.19.2 version on Modrinth ATM.

**Comment by ShetiPhian** [comment]
It didn't have a new file to upload so was missed; its posted now though.
