### ISSUE TITLE
tree saplings will not grow 

### ISSUE THREAD

**Issue by SaturnVguy** [ShetiPhian/Localizations-and-Issues#419]
**Describe the bug**
any tree sapling from this mod will not grow no matter the biome or the time of day or the amount of bonemeal 

**Additional context**
Minecraft Version:  1.20.2
fabric: most recent
ShetiPhian Core Version: most recent 
Are other mods present?
yes: everything works fine just not the trees

**Comment by ShetiPhian** [comment]
I just tested this, and I'm guessing another mod is conflicting.
On average saplings took 6 bonemeal to grow. (best was 2, worst was 15)
(Overworld Plains biome, most where tested during the day but it became night while testing)
