### ISSUE TITLE
Server crashes when RFTools builder gets a null return from getItem() on terraqueous:foliage2 blocks

### ISSUE THREAD

**Issue by thejims** [ShetiPhian/Localizations-and-Issues#42]
When an RFTools builder is mining a block of type terraqueous:foliage2, it is receiving null from the getItem() method call, this in turn crashes the server.

See report to RFTools: https://github.com/McJty/RFTools/issues/1037

**Comment by ShetiPhian** [comment]
Oh look another 1.11 null ItemStack error -_-

Mojang changing from null being valid for itemstacks to requiring the new ItemStack.Empty is the most annoying change they have done. At least the other changes created errors reported in the IDE.

Prior to 1.11 null was used and everything is coded for null. Forge made transitioning to the new requirement simpler by using the nonnull flag but vanilla code doesn't have this flag, so no error is generated by the IDE making it very easy to miss.

The odd one will be likely still be found in 1.12 -_-

**Comment by ShetiPhian** [comment]
Apologies for being a moron and forgetting to link you a build that fixes this.

Here is the build I just compiled recently, rather then link you to the older rb1.
http://www.mediafire.com/file/tol9so7bba1b6pz/terraqueous-1.11.0-1.3.7-rb2.jar

**Comment by ShetiPhian** [comment]
New build has been submitted to Curse, just waiting for the download link to become publicly available.
Note: You'll need to update ShetiPhianCore also.
