### ISSUE TITLE
will we  ever get endertanks for fabric 1.18.2?

### ISSUE THREAD

**Issue by Kleptoplasm** [ShetiPhian/Localizations-and-Issues#420]
will we  ever get endertanks for fabric 1.18.2?

**Comment by ShetiPhian** [comment]
Can't say it is planned.
Though I was thinking about making 1.19.2 a long term support version, but 1.18.2 looks like it is more popular, so backporting it it might be the better option.

**Comment by ShetiPhian** [comment]
Well I was working on porting MultiStorage from 1.12 and while moving its code back I though why not.
Ended up backporting the 1.19.2 builds to 1.18.2 and releasing them.
There wasn't much code changed between the two versions. (With the exception of systems Terraqueous uses, it will need a few things rewritten so its still on 1.19)
