### ISSUE TITLE
EnderChest Upgrade not working

### ISSUE THREAD

**Issue by TheRedDraqon** [ShetiPhian/Localizations-and-Issues#422]
When changing the Max from 27 to 54, the gui only shows 27 but I can put items in.

**Additional context**
Minecraft Version: 1.20.1
Forge Version: 47.2
ShetiPhian Core Version: Not sure but the glitch happened 2/3 months ago regardless.
My Mod(s) Name & Version: EnderChests (once again, this happened in previous updates, I made this pack a day or two ago, so it would likely be the latest version)
Are other mods present?
If yes:
- Does everything work without my mods? Yes
- Have you tested with only my mods? Yes

**Comment by ShetiPhian** [comment]
Was this on a server/lan? was the configs set on both client and server?
It sounds like the client is still using the old value.
