### ISSUE TITLE
[question] how are you supposed to get `terraqueous:drying_hay`?

### ISSUE THREAD

**Issue by 800020h** [ShetiPhian/Localizations-and-Issues#424]
terraqueous-fabric-1.19.2-1.1.7

https://github.com/ShetiPhian/Localizations-and-Issues/issues/64
makes it sound like it involves stone, lava, and grass items but I can't figure it out

**Comment by ShetiPhian** [comment]
Obtain grass via shears or scythe (or any other mod added way) and just sneak place it on the ground.
The grass will change color as it dries eventually transitioning from Loose Grass to Drying Grass ending as Loose Hay.
You can make it dry faster if placed on sand in a hot biome (Nether works also), or on top of a stone that is over lava.
Won't dry in cold biomes (think the stone over lava works though)

**Comment by 800020h** [comment]
it seems to be bugged
I made a new instance with only terraqueous and dependencies and sneak placing grass behaved like vanilla

**Comment by ShetiPhian** [comment]
Sorry, I thought I had upload the fix back in my November builds.
It was broken more then not being placeable, I had overridden the wrong tick method so it would have never dried
The new builds available on Curse and Modrinth
