### ISSUE TITLE
[MultiStorage] [Crash] Incompitable with PrimalMagick

### ISSUE THREAD

**Issue by shBLOCK** [ShetiPhian/Localizations-and-Issues#427]
**Describe the bug**
Crash when inserting things into the Research Table from Primal Magick.
The client crashes if you insert in the GUI, the whole server crashes if you do it with automation.

This could be on primal magick's side (getInventoryIndexForFace() returning null), but I think there should be some error handling of this.

**Additional context**
Minecraft Version: 47.2.16
My Mod(s) Name & Version: 1.0

[crash-2023-12-20_18.40.14-server.txt](https://github.com/ShetiPhian/Localizations-and-Issues/files/13726386/crash-2023-12-20_18.40.14-server.txt)

**Comment by ShetiPhian** [comment]
The direction variable of getCapability is nullable, PrimalMagick needs to check for null before using it.
(I missed that a few years back and was causing a crash with an inventory searching mod)

**Comment by shBLOCK** [comment]
Oh sorry, I think I got it the whole way around. I thought it was PrimalMagick that's returning null and causing problem here, upon checking primal magick's code, it's indeed their problem. I'll report this to them.
