### ISSUE TITLE
Ender Tanks forget contents on relog.

### ISSUE THREAD

**Issue by MindBrain27** [ShetiPhian/Localizations-and-Issues#428]
**Describe the bug**
When logging out and back in some Ender Tanks forget their contents.

I have GTCEu Modern and when I have a machine exporting into an Ender Tank everything is fine until I log out and back in. 1 Ender tank will remain full but a second Ender Tank will go to empty, the tooltip from The One Probe shows 1 empty and 1 full. Essentially it starts voiding the fluids, if you pick up the Ender Tank and replace it down everything goes back to normal.

**Additional context**
Minecraft Version: 1.20.1
Forge Version: 47.2.17
ShetiPhian Core Version: 1.2
My Mod(s) Name & Version: Small pack with 150ish mods, gtceu-forge-1.20.1-1.0.18.a.jar
Are other mods present?
If yes:
- Does everything work without my mods? No other tanks in the pack do this.
- Have you tested with only my mods? Yes

PasteBin or GitHub Gists links
latest.log = PasteBin crashes when i paste anything into it.
debug.log = ?

After relogging the tank being input into is like this. It doesn't just look like it's empty, it actually accepts fluids.
![2023-12-26_05 53 56](https://github.com/ShetiPhian/Localizations-and-Issues/assets/74363414/15b16685-119b-4cda-83e9-7f66b8a43d95)

After relogging the tank being output from is like this.
![2023-12-26_05 53 59](https://github.com/ShetiPhian/Localizations-and-Issues/assets/74363414/a9c850bc-5092-455d-a811-26f2b50a8e29)

After replacing the tank down it is fine.
![2023-12-26_05 54 33](https://github.com/ShetiPhian/Localizations-and-Issues/assets/74363414/b8c09195-c091-4236-a4d6-c8b071d561f9)

**Comment by MindBrain27** [comment]
This same issue happens for 2 setups i have every time I relog, 1 for Liquid Rubber and 1 for Glue.

**Comment by ShetiPhian** [comment]
I was sure the default progress bars also used server side data, but if its resetting it must be looking at client data. (might have to sync the data myself so the bar renders correctly)
The data added by EnderTanks correctly indicates its full, so server side it will not be accepting anymore.

If you stop rubber/glue production, relog so the tank appears empty, wait for the machines output to drop, and relog again, is the machine still missing material?
This should just be a client side visual issue, it material is being lost the machine might be doing the transfer client side
