### ISSUE TITLE
[MultiStorage] Upgrades lost when breaking container

### ISSUE THREAD

**Issue by tovvl** [ShetiPhian/Localizations-and-Issues#432]
**Describe the bug**
Any MultiStorage container that had upgrades applied will lose their upgrades when the container is broken

**Additional context**
Minecraft Version: 1.20.1
Forge Version: 47.1.3
ShetiPhian Core Version: shetiphiancore-forge-1.20.1-1.2
My Mod(s) Name & Version: multistorage-forge-1.20.1-1.0
Are other mods present? No

**Comment by ShetiPhian** [comment]
This is working correctly in 1.16, but for some reason broke when porting.
Sneaking properly drops the upgrades separately.

Oddly Ender Chests & Tanks also use a sneak check in their loot table, and it works.
noticeable difference is those have separate paths for sneaking, while MultiStorage is only enabling additional functions, maybe 1.17 removed that option.

**Comment by ShetiPhian** [comment]
Fixed; new builds on Curse and Modrinth
