### ISSUE TITLE
Display issue with doodads?  1.19.2 fabric Terraqueous

### ISSUE THREAD

**Issue by Lozf** [ShetiPhian/Localizations-and-Issues#435]
**Describe the bug**

The doodads do not appear as in the display picture- I've included a picture below showcasing them.  Is this how they are supposed to look?  They look like this regardless of whether other mods/resource packs are present or not.  

**Additional context**
Minecraft Version:  1.19.2
Forge Version: FABRIC loader 1.19.2 0.14.22
ShetiPhian Core Version: Fabric 1.19.2-1.3.12
My Mod(s) Name & Version: Terraqueous 1.1.7
Are other mods present? Yes
If yes:
- Have you tested with only my mods? Yes
![Terraqueous](https://github.com/ShetiPhian/Localizations-and-Issues/assets/69091548/a2b8effb-93a0-4f98-8423-fbae31c469a5)

**Comment by ShetiPhian** [comment]
Those are correct, Fruzstrated updated the models. (mod page hasn't been updated yet)
The old ones where obj files and while they worked okay in Forge, the mod adding support to Fabric caused compatibility issues, so all obj models where converted to the Minecraft json model format.
