### ISSUE TITLE
Sheets and Pillows not showing color (they stay white) when Chipped and/or Rechiseled are installed.

### ISSUE THREAD

**Issue by Dumpling00** [ShetiPhian/Localizations-and-Issues#441]
Fabric 1.20.1

The title explains it all, could this please be looked into? For some reason the presence of Chipped and Rechiseled (even just one of them) impedes pillows and sheets to display colors when dyed. They keep their hexcode and all, but they will remain white.

Thank you for your time and consideration.

**Comment by Dumpling00** [comment]
Update, it's actually because of SuperMartijn642's Core and Config Libs, which are Rechiseled's dependencies.

Is it possible to have a compatibility patch?

**Comment by ShetiPhian** [comment]
Sounds like the same issue as Sodium. (https://github.com/ShetiPhian/Localizations-and-Issues/issues/385)
Does it also have a blending option?

**Comment by Dumpling00** [comment]
> Sounds like the same issue as Sodium. (#385) Does it also have a blending option?

Hi, uh, I'm not sure about the blending option. What am I supposed to look at? The patch suggested isn't available for 1.20.1.

**Comment by Dumpling00** [comment]
Seems like it's impossible to set biome blending to 0 in 1.20.1 :(

**Comment by Dumpling00** [comment]
@ShetiPhian I'm sorry but can this be fixed at all?

**Comment by Dumpling00** [comment]
Oh nevermind I guess it really just is on Sodium's hands :) hopefully it gets fixed soon then.
Thank you for your time.
