### ISSUE TITLE
Japanese localization file for EnderChests and EnderTanks

### ISSUE THREAD

**Issue by nyx-2525** [ShetiPhian/Localizations-and-Issues#444]
I've created Japanese language json file for EnderChests and EnderTanks. 

[(EnderChests)ja_jp.json](https://github.com/user-attachments/files/15619458/EnderChests.ja_jp.json)
[(EnderTanks)ja_jp.json](https://github.com/user-attachments/files/15619465/EnderTanks.ja_jp.json)

**Comment by ShetiPhian** [comment]
Sorry I started today by accepting the pull requests; one was Japanese localizations.
They are different though, if corrections are needed on the other one open a pull request with the changes and I'll merge it.
