### ISSUE TITLE
Error executing task

### ISSUE THREAD

**Issue by gwynhefar** [ShetiPhian/Localizations-and-Issues#445]
**Describe the bug**
 
No crash, but significant lag that may or may not be related to the errors I'm getting from Ender Tanks

---
**Additional context**
- Minecraft Version: 1.12.2
- ModLoader & Version: (Fabric|Forge|NeoForge)  Forge 14.23.5.2860
- Side: (SinglePlayer|Server|LAN-Host|LAN-Client)  Single Player
- ShetiPhian Core Version: 1.12.0-3.5.9
- My Mod(s) Name & Version: Ender Tanks  1.12.0-1.6.8

PasteBin or GitHub Gists links
- latest.log = https://pastebin.com/FGHink4u

**Comment by ShetiPhian** [comment]
1.12 is not supported anymore

I'm aware of this bug, but the first time it was reported was after I stopped supporting 1.12 and the development environment died.

There is no known workaround; I don't remember when I added the problematic code, but an older build may work.
