### ISSUE TITLE
Terraqueous Unexpected Error - Accidentally adding the same item stack twice [Pergola Gate] to a Creative Mode Tab

### ISSUE THREAD

**Issue by Kaytra** [ShetiPhian/Localizations-and-Issues#448]
Upon opening the creative menu in a single player world with the mod installed, the game crashes with a exit code -1. According to the error log, this is due to an item [Pergola Gate] being added to the creative menu twice, and Minecraft not liking that.

---
- Minecraft Version: 1.20.1
- ModLoader & Version: Quilt 0.26.0
- Side: SinglePlayer
- ShetiPhian Core Version: 1.20.1-1.2
- Mod Name & Version: Terraqueous 1.20.1-1.4, fabric version

Are other mods present?
- Does everything work without my mods?
- Have you tested with only my mods?
Yes, other mods are present. See the crash report for the list of other mods in the pack. And yes the modpack works as expected without Terraqueous included.

PasteBin or GitHub Gists links
- [crash report](https://gist.github.com/Kaytra/13e23ba15347b296b1b2ef515d5b3f7b)

**Comment by ShetiPhian** [comment]
That and all of my other colored blocks are added multiple times, though each as a new ItemStack with different NBT data.
Its working correctly in Fabric, Forge, and NeoForge, I don't know why its crashing on Quilt.
It would be odd if someone changed the compare to look at the item only, as Enchanted Books and Potions would crash also.
