### ISSUE TITLE
[1.10.2] Terraqueous: java.lang.NullPointerException: Tesselating block model

### ISSUE THREAD

**Issue by DeadSix27** [ShetiPhian/Localizations-and-Issues#45]
Version: terraqueous-1.10.0-1.2.18.jar

Client crashes upon join with this stacktrace:

http://pastebin.com/wZBS5GGv

**Comment by ShetiPhian** [comment]
Either somehow the tileentity data became corrupted, or something is messing up the server to client sync packet.

The facing value is preset to north, the value gets set correctly when the sync packet arrives. The only way for it to be null is if the server sent a bad packet or if the packet got messed up.

This build should enable you to get in world, it just sets a null facing back to north:
http://www.mediafire.com/file/gmloc1e6yyggm4z/terraqueous-1.10.0-1.2.19-rb2.jar

**Comment by DeadSix27** [comment]
@ShetiPhian thanks a lot, ill check it out and see whats going in.

**Comment by ShetiPhian** [comment]
@DeadSix27 
I've applied the same fix to all my tile entities, to prevent this crash from happening again.

New build is up on Curse (well under review as I type), you'll need the newest core as well.

**Comment by DeadSix27** [comment]
@ShetiPhian thanks. I have not encountered this issue again yet. I had a feeling it was caused by those tiny branch thingies laying on the ground as I tinkered in an area where many of those were.
But that's just all I remember in terms of Terraqueous things around me during that time.
