### ISSUE TITLE
When adding the mod terraqueous for some reason it crashes out

### ISSUE THREAD

**Issue by xaxilin** [ShetiPhian/Localizations-and-Issues#454]
When adding the mod terraqueous for some reason it crashes out
---
**Additional context**
- 1.11.2: 
- Forge latest
- Single player
- shetiphiancore-1.11.0-3.4.9: 
- terraqueous-1.11.0-1.3.18.: 

Are other mods present?
yes
- Does everything work without my mods?
yes
- Have you tested with only my mods?
no
PasteBin or GitHub Gists links
[- latest.log = ](https://pastebin.com/x2EZ4P2E)

**Comment by ShetiPhian** [comment]
1.11 is no longer supported.

A quick glance, the errors I saw where mod interactions. Not able to add to Forstry backpacks, and a JEI recipe issue.
But the crash itself was to do with model / texture stitching.
Maybe an incompatibility with the forge version or another mod.
