### ISSUE TITLE
Error al iniciar el juego con el mod terraqueous

### ISSUE THREAD

**Issue by jhon05117** [ShetiPhian/Localizations-and-Issues#457]
**Describe the bug**.
Error al  iniciar 
Al cargar el minecraft muestra el avance de carda el mod y al terminar de cargar el mod me manda  error -1
---
**Additional context**
- Minecraft Version: 1.11.2
- ModLoader & Version: (Fabric|Forge|NeoForge) forge 1.11.2
- Side: (SinglePlayer|Server|LAN-Host|LAN-Client) single player
- ShetiPhian Core Version: 1.11.2
- My Mod(s) Name & Version:  terraqueous 1.11.2

Are other mods present? no
- Does everything work without my mods? si
- Have you tested with only my mods? si

PasteBin or GitHub Gists links
- latest.log = 
- adjunto reporte del problema incluso al abrir el mod en versiones nuevas con el mod y el complemento actualizado sigue fallando
- 
[crash-2024-09-26_21.32.06-client.txt](https://github.com/user-attachments/files/17248449/crash-2024-09-26_21.32.06-client.txt)

**Comment by ShetiPhian** [comment]
1.11 is long out of support.

Your Java ran out of memory: java.lang.OutOfMemoryError: Java heap space
Looks like only 2GB is allocated (2048MB) if you can bump that to 4GB (4096MB) or even 3GB (3072MB) you should be able to launch the game.
