### ISSUE TITLE
ShowMeYourSkin Incompat

### ISSUE THREAD

**Issue by Zevyrus** [ShetiPhian/Localizations-and-Issues#459]
**Describe the bug**

"Terraqueous" crashes due to the coconut death somehow having a conflict with "show me your skin" 

---
**Additional context**
- Minecraft Version: 1.20.1
- ModLoader & Version: Fabric 0.16.7
- Side: Singleplayer
- ShetiPhian Core Version: 1.20.1-1.2
- My Mod(s) Name & Version: Terraqueous 1.20.1-1.4

Are other mods present?
Yes
- Does everything work without my mods?
Yes
- Have you tested with only my mods?
Yes

PasteBin or GitHub Gists links
- latest.log = 
[https://pastebin.com/dAwHCX1e](url)

**Comment by ShetiPhian** [comment]
New builds are uploaded.

Should work fine now.
I changed how I initialized my damage sources, and the error no longer happened while testing.
