### ISSUE TITLE
Clouds Should be Bigger and Moving

### ISSUE THREAD

**Issue by kenijey** [ShetiPhian/Localizations-and-Issues#46]
However, i'm using shader and they have shadows. It's pretty nice. But they should be bigger as real clouds, and moving. And please make them compatible with the weather. Thanks!

**Comment by ShetiPhian** [comment]
While that would be nice, Minecraft is not built in a way where that would be possible without major performance loss.

If you not using the blocks for building or crafting there is a config option to disable them.

Side Note:
This is a nice weather mod http://coros.us/mods/weather2 only 1.10 though.
