### ISSUE TITLE
Stack of Ender bags turn into single Ender bag when linking

### ISSUE THREAD

**Issue by kirlu1** [ShetiPhian/Localizations-and-Issues#460]
**Bug description**

If you hold multiple Ender bags with the same colors in your hand and attempt to link them to a chest of a different color, you end up with only a single linked bag.

---
**Additional context**
- Minecraft Version: 1.20.1
- ModLoader & Version: Forge-47.3.7
- Side: SinglePlayer
- ShetiPhian Core Version: 1.20.1.-1.3
- My Mod(s) Name & Version: EnderChests 1.20.1-1.2

Are other mods present?
- This is within ATM9, but issue seems contained to EnderChests.

**Comment by ShetiPhian** [comment]
Well there's an oversight of making the bags and buckets stack.

Should I link the whole stack, or one at a time like filling buckets... maybe I'll leave it a config option.

**Comment by ShetiPhian** [comment]
New builds are uploaded.
By default the whole stack is linked, but there is a config option to to make it only do one at a time.
