### ISSUE TITLE
Tinkerer's Smithing Incompatibility on 1.20.1 Fabric Server

### ISSUE THREAD

**Issue by ElectroArtifex** [ShetiPhian/Localizations-and-Issues#464]
When attempting to launch a 1.20.1 Fabric server with Terraqueous and Tinkerer's Smithing installed, the server crashes due to this incompatibility. Is there any way this could be potentially fixed? I've [opened a bug report](https://github.com/sisby-folk/tinkerers-smithing/issues/56#issue-2665280861) on both sides in case a dialogue is needed. I'd hate to choose between them! 

---
**Additional context**
- Minecraft Version: 1.20.1
- ModLoader & Version: Fabric 0.16.9
- Side: Server
- ShetiPhian Core Version: 1.20.1-1.2
- My Mod(s) Name & Version:  1.20.1-1.4

PasteBin or GitHub Gists links
- latest.log = [latest.log](https://github.com/user-attachments/files/17788914/latest.log)

**Comment by ShetiPhian** [comment]
Looks like my issue.
_I'm guessing the abstract String method_7694() is getName() and not something Tinkerer's Smithing added, as they would have added a defaulted method not an abstract one_

My class has getName() flagged client only, therefore its missing on the server, but the interface it is from doesn't mark it client only, so this make my class wrong.

Not sure if getName was ever client only on Fabric or if it was an error when porting from Forge.
This is a great example why the mod loader maintainers say mods shouldn't use the sided flags in their own classes.

The next build will correct this.
(also sided flags are being removed while porting to 1.21)

**Comment by ShetiPhian** [comment]
New builds are uploaded.
