### ISSUE TITLE
Crash near Banana Flower in Survival

### ISSUE THREAD

**Issue by Aimaina** [ShetiPhian/Localizations-and-Issues#48]
The game crashes when I am near a Banana Flower in Survival Mode. It happens whether I walk to it in Survival or switch from a different mode while near it. 

http://pastebin.com/FAJpgjzX

I apologize for any mistakes on my part. I'm fairly new to using mods.

**Comment by ShetiPhian** [comment]
Not you, error in my code.

1.11 and Null error
Likely its the same issue as: https://github.com/ShetiPhian/Localizations-and-Issues/issues/49

**Comment by ShetiPhian** [comment]
Here is a quick build that should correct this issue (and a few others that where fixed previously)
http://www.mediafire.com/file/tol9so7bba1b6pz/terraqueous-1.11.0-1.3.7-rb2.jar

**Comment by Aimaina** [comment]
Thanks!

**Comment by ShetiPhian** [comment]
New build has been submitted to Curse, just waiting for the download link to become publicly available.
Note: You'll need to update ShetiPhianCore also.
