### ISSUE TITLE
Crash When Look To Banana Flower (TOP installed)

### ISSUE THREAD

**Issue by kenijey** [ShetiPhian/Localizations-and-Issues#49]
please help it... 
[crash-2017-03-01_23.37.35-client.txt](https://github.com/ShetiPhian/Localizations-and-Issues/files/811978/crash-2017-03-01_23.37.35-client.txt)

https://github.com/McJty/TheOneProbe/issues/125

**Comment by ShetiPhian** [comment]
Oh look another 1.11 null ItemStack error -_-
Everyone I get makes me hate Mojang a little more due to that asinine change.

Real life is finally calming down, so soon I should be able to get through the testing and bug fixes I have piled up.

**Comment by ShetiPhian** [comment]
Here is a quick build that should correct this issue (and a few others that where fixed previously)
http://www.mediafire.com/file/tol9so7bba1b6pz/terraqueous-1.11.0-1.3.7-rb2.jar

**Comment by ShetiPhian** [comment]
New build has been submitted to Curse, just waiting for the download link to become publicly available.
Note: You'll need to update ShetiPhianCore also.

**Comment by kenijey** [comment]
thank you. should i delete old config file after update?

**Comment by ShetiPhian** [comment]
No need;
I generally clean up any old keys when I do config changes, and if I forget to they would have no effect on the game as I no longer check them.
