### ISSUE TITLE
[Crash]: - Ticking Block Entity

### ISSUE THREAD

**Issue by Lanse505** [ShetiPhian/Localizations-and-Issues#5]
**Forge Version:**
Forge{12.18.2.2124}

**Core and Mod Versions:**
shetiphiancore{3.3.3} & platforms{1.2.2}

**Crashlog:**
https://gist.github.com/Lanse505/c4d74e6a3aad15095faea0d1ca2a45d6#file-gistfile1-txt

**What did you do?:**
We shift-clicked in a Platformer into the Platformer and it crashed and corrupted both the server world and everyone on the server crashed.

**Why should I look at this?:**
Because bugs are never fun and Pancakes tastes yummy :P

**Comment by ShetiPhian** [comment]
Only items crafted in the PlatFormer should go into the deconstruct slot, I need to fix that.
I'll also add code to stop the deconstruction process if its not a platform.

**Comment by ShetiPhian** [comment]
New version is up on Curse

ChangeLog:
PlatFormer deconstruct fixes
- Fixed automation not restricting what it placed into the slot
- Fixed being able to place a PlatFormer into the slot
- Fixed crash if an invalid item is in the slot by aborting the deconstruction process
