### ISSUE TITLE
Placing/crafting Cloud blocks

### ISSUE THREAD

**Issue by Winddbourne** [ShetiPhian/Localizations-and-Issues#50]
I really like the cloud blocks you added to the game; not so much the actually generated clouds in the sky. I prefer to let mods like Optifine add clouds to the background, use Coro's weather mod, or simply have no clouds at all. It saves on world generation and lets my mod packs be a bit more robust. I always ship with a default file that turns off minecraft's normal clouds too. 

I can turn off your clouds in the config file too and prevent them from generating. But I can't find a way to let players craft water vapor, or place down a cloud block in mid air. It seems that they only can be placed on already existing cloud blocks though. 

What I'd like you to do, if possible, is this:

- Add a recipe that lets us cook a bucket of water and get water vapor, obviously returning the bucket to our inventory. :)

-Make the first level of "clouds" able to be placed in mid air just like an angel block from extra utilities. 

This wouldn't just solve my problem but would make a GREAT replacement for angel blocks in skyblock worlds while also allowing people to build huge platforms out of cloud blocks without having to have those "starting platforms" generate all over the place just to provide a spot to start construction from.

**Comment by ShetiPhian** [comment]
There is a shapeless recipe: 1x water bucket = 4x water vapor
From there everything can be crafted, but noting can be placed. Which is an overlooked issue caused when I split up the original mod.

Terraqueous was PixelPowers-World, PixelPowers-Player has yet to be remade.

Cloud related items needed to be reworked to make Terra standalone.
In PixelPowers you had to have magic to craft the Talisman, and to understand the EnderTable. Cloud manipulation was needed to craft and place clouds.

I got rid of the Talisman's magic requirement in and added the EnderMonicule, added a recipe to craft vapor but overlooked they couldn't be placed without another cloud block.

I'll need to add a 'Staff of the Mists', or another name if its already used by another mod.

**Comment by Winddbourne** [comment]
Interesting I wonder why I wasn't able to find the recipe in JEI. I'll have to try again because I may have made a mistake in my search. :)

Definitely will be glad to be able to place the clouds too. Thanks for the quick reply.

**Comment by ShetiPhian** [comment]
Only the Blue vapor is craftable, the others are colored in world.
Another mod may have overwritten it.
I know there is a conflict with HarvestCraft but I think I use their water barrel when that's detected.

I'll likely remove the recipe and have the staff do it all.

**Comment by Winddbourne** [comment]
I found the problem with searching for the recipe in JEI . . . it's minor and mostly on my end. Whenever you pull up any of the cloud recipes it pulls them all up and you have to scroll through a number of pages to find the water bucket recipe. So if you are looking quickly it is easy to miss.

**Comment by ShetiPhian** [comment]
It will be a bit before I get a new build up on Curse, If you want to check out the new staff before then:
http://www.mediafire.com/file/5t2cjz3gih2mgb0/shetiphiancore-1.11.0-3.4.3-rb1.jar
http://www.mediafire.com/file/3egn62cg6j5y9yl/terraqueous-1.11.0-1.3.7-rb3.jar

The water bucket recipe is gone, to get blocks just put the staff into a crafting grid to pull some out. The staff needs enough stored water to place 8 blocks before the recipe works. Block count is in the tooltip.

**Comment by Winddbourne** [comment]
Sweet. Yes I do need the 1.10.2 builds. A lot of mods haven't updated yet
and I've been trying to keep things as stable as I can. Looks like there is
a rush towards 1.11 though so I may have to consider a jump soon. lol

**Comment by ShetiPhian** [comment]
Here you go:
http://www.mediafire.com/file/cbdsd9bflqhdy0x/terraqueous-1.10.0-1.2.19-rb3.jar

The core is available on Curse now, seen no point in holding it and the other mods back when it was just Terra and MultiStorage that needs some final testing done.

**Comment by Winddbourne** [comment]
Thanks :)

**Comment by ShetiPhian** [comment]
Uploaded to Curse, just waiting for them to make the downloads publicly available.
