### ISSUE TITLE
[Terraqueous][1.11.2-1.3.7] Bunnies ignoring mod's cactuses, dying due to that.

### ISSUE THREAD

**Issue by starg09** [ShetiPhian/Localizations-and-Issues#53]
Not sure if you can work with their AI so they try to avoid them. Otherwise living on a desert may become a bit annoying, with the constant sounds of bunnies being killed...

**Comment by ShetiPhian** [comment]
Looks like it can be done for 1.11 but not 1.10

**Comment by starg09** [comment]
Good enough for me 👌 

A shame for those using the mod on 1.10 though :/

**Comment by ShetiPhian** [comment]
Turns out Forge added the function in 1.11.2, but I'm not dropping my 1.11.0 support yet. (I'll do that when 1.12 is out)
The change I made works in 1.10.x though, I simply made it so rabbits are no longer harmed by cactus.

I've submitted the build to Curse, should be available for download soon.
