### ISSUE TITLE
Removing door leaves broken ghost blocks

### ISSUE THREAD

**Issue by FractalPhoenix** [ShetiPhian/Localizations-and-Issues#54]
We were trying stuff and had to remove it twice, and both times when we removed it above where it was there are now 2 invisible blocks that can't be broken or when right clicked causes a client side crash.

**Comment by ShetiPhian** [comment]
I'm not getting this with either the 2x2 or 3x3 door.

Are you placing the door or using a block placer to do it? 
They need to be player placed, machine placing causes issues and is prevented in the latest builds.

Are you using the newest build?
If its a pre-made pack its likely using an out of date version (some are several versions behind) you'll either need to wait for the pack to update or update manually (you'll need the newest ShetiPhianCore also)

I also need the crash report.
