### ISSUE TITLE
[Config request] Cloud generation height

### ISSUE THREAD

**Issue by thephoenixlodge** [ShetiPhian/Localizations-and-Issues#56]
Really love the concept of the clouds, but with the height range covered by ATG's worldgen, they can end up being a bit too close to the ground, so would find a config option to make them generate a bit higher up quite useful.

**Comment by ShetiPhian** [comment]
I'll add it to the next build.

**Comment by ShetiPhian** [comment]
Sorry for the delay,
New builds are up on Curse now.
