### ISSUE TITLE
[Suggestion] Config to disable Trickster bloom mob transformations

### ISSUE THREAD

**Issue by WesCook** [ShetiPhian/Localizations-and-Issues#58]
In the modpack I'm working on, there's a large significance placed upon finding animals and taming them.  I've included Terraqueous to add some new variety to trees and decoration.

However, I didn't know until just recently that the Trickster Bloom is able to transform hostile mobs into friendly ones.  This introduces a problem of balance, as instead of searching out animals, it's easy enough to just lure hostile mobs over the Trickster Bloom instead.

Would you consider adding a config option to disable this transformation effect?  Thank you.

e: typo

**Comment by ShetiPhian** [comment]
Can do.

**Comment by ShetiPhian** [comment]
Sorry for the delay,
New builds are up on Curse now.

**Comment by WesCook** [comment]
Excellent, works great.  Much thanks!
