### ISSUE TITLE
[1.11.2] Platforms.jpg unable to load, causing crash on the /FruzstratedsGuide guide.

### ISSUE THREAD

**Issue by GeekBeam** [ShetiPhian/Localizations-and-Issues#60]
I was looking at the guide screen you have included as a command in-game, and moused over the storm cloud block in the Craft furnace recipe screen.

this may be due to being paired with ItemZoom, as a mod, which gives a zoomed in version of item textures to the left of the screen. Further Testing will be done on my part to confirm.

[[crash log]](http://puu.sh/valEq/ec41b97a1b.txt) plus error log before crash that points to "platforms.jpg" 's inability to load being the cause of the crash.

**Comment by ShetiPhian** [comment]
Two different errors here.

The crash is due to a null ItemStack;
up until 1.11 these where valid, and by java still are, but Mojang requires ItemStack.EMPTY now.

Looks like platforms.jpg is in fact missing, I've been including the png version for who knows how long.

**Comment by ShetiPhian** [comment]
New builds are on Curse.
Updating ShetiPhianCore will remove the crash, and updating Platforms will remove the error.
