### ISSUE TITLE
[Terraqueous][1.11.2]Weird game freezing on uncertain conditions, possibly related to the mod (and maybe

### ISSUE THREAD

**Issue by starg09** [ShetiPhian/Localizations-and-Issues#62]
Ok, so this has been happening to me a lot since I started developing my modpack. When opening/creating a world, there's a chance from time to time that the game will freeze completely, at the loading screen saying "`0%`". Not a crash, not a hang up (with windows offering to close the game). It simply stayed there, while mods wouldn't do anything (except dynamic surroundings, for some odd reason).

Now, so far I hadn't been able to reduce it to a certain mod causing it, mostly because I couldn't reproduce the issue effectively. 

Today, however, I noticed the following pattern allowed me to cause a freeze 99.9% of the time on my instance: As soon as the main menu pops up, go to Single Player, and create a new world in creative with regular Superflat.

With the help of that, I noticed the issue stopped ocurring when removing Terraqueous. While I cannot prove for certain the mod is guilty of this, I have my suspicions it might be. [Here's the log of one time](https://gist.githubusercontent.com/starg09/3bee14981e46aa227312d1e55701fd0a/raw/84cb5bb8eafa58d226e33b9b193bab05aab13b9e/gistfile1.txt) where I do as I mentioned above. Emphasis on [this section](https://gist.github.com/starg09/845d574a4a10517e93bc42885b88b25c).

I also tested with only the mod and forge, but it didn't work. Then tried adding crafttweaker and the scripts I have that involve the mod, but worlds still seemed to load fine... Do you think it might have to do with Terraqueous?

Versions used:

* Forge 2279
* ShetiPhianCore 3.4.4
* Terraqueous 1.3.9
* **Edit below:** Astral Sorcery 1.3.0

**Edit right before submitting:** Ok, added Astral Sorcery to a clean instance, with only forge, Terraqueous and CraftTweaker, following steps mentioned above for reproducing; and while not exactly the same, I did get kicked out of my world. Reopening it causes the 0% error. This happens even with no scripts loaded, it seems.

**Comment by ShetiPhian** [comment]
You caught me just before I uploaded a new build.

**Comment by starg09** [comment]
Well... So far I tested a couple times on both test instance and the full pack one, and haven't got any more of those. So for now I'd say it got fixed with the update :smile:

**Comment by ShetiPhian** [comment]
The build is up on Curse now,
