### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by wizard1399** [ShetiPhian/Localizations-and-Issues#63]
[crash-2017-04-10_18.15.44-client.txt](https://github.com/ShetiPhian/Localizations-and-Issues/files/911732/crash-2017-04-10_18.15.44-client.txt)

**Comment by ShetiPhian** [comment]
Your version of ShetiPhianCore is too low
MultiStorage 1.10.0-1.2.17 requires ShetiPhianCore-1.10.0-3.3.8

There is a mod that breaks the Forge version check when the same dependency is needed by more then one mod but the minimum version is different.

**Comment by wizard1399** [comment]
Will try updating the core and then try the latest version to see if that fixes the problem. Will report back after doing so.
