### ISSUE TITLE
Hay uncraftable

### ISSUE THREAD

**Issue by PenguinMan98** [ShetiPhian/Localizations-and-Issues#64]
I put stones down over lava and cooked my grass that I harvested with shears to make loose hay.  Many recombinations later (are so many steps really necessary?) I get to the final step of combining 4 hay blocks into a bale.  Trying to do this whether in my personal grid or the crafting table, always results in the game briefly showing the bale in my inventory but then returning the ingredients to the crafting grid.

No error is given.
This issue was in versions 1.9 and 2.0 of colonial expansion using terraqueous mod version 1.11.0-1.3.10

https://www.screencast.com/t/ysUcNvFu8Wt

**Comment by ShetiPhian** [comment]
I won't be able to look into this until after work but it sounds like the server has disabled the "replaceHayBaleRecipes" config option but the client still has it enabled. If this is the case the client thinks the recipe needs 4 hay blocks, but the server requires the original 9 wheat recipe.

Try setting this config option to false: terraqueous.cfg > crafting > replaceHayBaleRecipes
Then restart Minecraft.

**Comment by PenguinMan98** [comment]
That does allow me to craft hay bales from 9 wheat.

This issue happened on both our group server and on the public kreezCraft server so the issue is definitely present with the default installation.

**Comment by ShetiPhian** [comment]
I just downloaded the server files.
They have changed "replaceHayBaleRecipes" to false in the Server config, but left it as the default true in the client config.

If you haven't done so already you should let the pack maker know.
