### ISSUE TITLE
Suggestion: Add coconut milk

### ISSUE THREAD

**Issue by kenijey** [ShetiPhian/Localizations-and-Issues#65]
please add this :D making coconut milk from coconut. we really like it, please ^^ thanks

**Comment by ShetiPhian** [comment]
It would be simple to add it as just another food item, but I think I'd want to do more with it.
Maybe make it work a bit like milk, but only able to remove one negative status effect at a time.

**Comment by kenijey** [comment]
yes, exactly; work like milk. and you can add some food items that produced with it. we are waiting for it ^^

**Comment by ShetiPhian** [comment]
Recipe added in the newest build.
1x bucket + 3x coconut = 1x bucket of coconut milk

I kinda cheated though.
to work like milk and be compatible will other mods and recipes would require copying most of the original milk bucket (and it may not work with all mods), so rather then create a new item the recipe just gives you a bucket of milk that is renamed :)

**Comment by kenijey** [comment]
thanks! :)
