### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Abbadonsin** [ShetiPhian/Localizations-and-Issues#66]
[crash-2017-04-20_16.18.51-server.txt](https://github.com/ShetiPhian/Localizations-and-Issues/files/945393/crash-2017-04-20_16.18.51-server.txt)
[crash-2017-04-20_16.10.57-server.txt](https://github.com/ShetiPhian/Localizations-and-Issues/files/945395/crash-2017-04-20_16.10.57-server.txt)

**Comment by ShetiPhian** [comment]
You'll need to update to 1.11.0-1.3.7 or higher, best to get the newest build.
ShetiPhian Core will also need to be updated.

**Comment by Abbadonsin** [comment]
As far as I can tell I had the latest release of shetiphiancore. the latest version i can find is 1.11.0-3.4.4

**Comment by ShetiPhian** [comment]
Apologies;
I never read the version of ShetiPhianCore your where using, just assumed 3.4.2 due to Terraqueous being 1.3.6.

You done need to update the core then :) just Terraqueous.
