### ISSUE TITLE
[Suggestion] Allow other players to break/upgrade Ender-Link Chests and Ender Tanks

### ISSUE THREAD

**Issue by Mohron** [ShetiPhian/Localizations-and-Issues#68]
Players often play in groups of 2 or more. Unfortunately when using personal (diamond-locked) storages, part of the usability is hindered by the fact that other players cannot pickup your chests/tanks. It's easy to have one player lock all the ender chests needed to make a base and just share them with their teammates protecting them from the possibility of somebody figuring out their global color combo. What would you propose to solve this issue? I'd like to see the ability to add players to your "ender-network" but a simple config to disable the default locking behavior would do as well.

**Comment by ShetiPhian** [comment]
While I don't know when I'll get the change to look into it or code a solution, I have thought it over.

A few ideas:
1) add an item that the owner uses on a chest/tank and afterwards another user holds it in their offhand to use the block without restriction.
- can be done but can quickly become annoying

2) use the built in scoreboard and check if the second user is on the same team as the owner
- not sure if I can access that data though

3) support ftb utilities teams
- requires another mod

Using both 2 and 3 seems like the best option.

**Comment by Mohron** [comment]
I agree that 2 & 3 would be the best options. I personally don't use FTB Utilities so I would be highly disappointed if that was the only option, plus all 1.10.2 FTB packs include EnderStorage :( last I checked... This limitation could be part of the reason, I can't really say, but I do prefer your modern take on these old classics! If nothing else, I'll just disable the lockout when your new config is available since I offer claiming to all my players anyways.

**Comment by ShetiPhian** [comment]
So I had the chance to tinker for a bit today (the upcoming week doesn't look good however)

To avoid breaking existing personal chests, adding complexity to the data structure, and increasing the amount of data saved per tank. I'll be adding a third type for the teams, it will use an emerald (configurable) to set.

---
Here is the new config option for EnderTanks. (MultiStorage will be getting similar ones)

Name | Default | Description
-----|---------|------------
"allowPublicTanks" | true | "Enables the usage of public tanks, if disabled tanks must be upgraded before use."
"allowPersonalTanks" | true | "Enables the creation of personal tanks, if disabled tanks can not set personal.\nDoes not effect tanks that are already set as personal"
"allowTeamTanks" | true | "Enables the creation of team tanks, if disabled tanks can not be set team.\nDoes not effect tanks that are already set as team"
"allowPublicBuckets" | true | "Enables the usage of public buckets, if disabled buckets must be linked to an upgraded tank before use."
"allowPersonalBuckets" | true | "Enables the linking of buckets to personal tanks.\nDoes not effect buckets that are already linked to personal tanks"
"allowTeamBuckets" | true | "Enables the linking of buckets to team tanks.\nDoes not effect buckets that are already linked to team tanks"
"enableAutomationPublic" | true | "Public tanks can be used with automation"
"enableAutomationPersonal" | true | "Personal tanks can be used with automation"
"enableAutomationTeam" | true | "Team tanks can be used with automation"
"lockPersonalEdit" | true | "While true only a tank can only be edited (upgrade, move, etc) by the owner"
"lockTeamEdit" | true | "While true only a tank can only be edited (upgrade, move, etc) by a team member"
"lockPersonalLink" | true | "While true only the owner can link a bucket to their tanks"
"lockTeamLink" | true | "While true only a team member can link a bucket to team tanks"
"lockPersonalUse" | false | "While true only the owner can use the tank"
"lockTeamUse" | false | "While true only a team member can use the tank"

---
Small history tidbit:
EnderTanks predate Chicken's by over a month, releasing the same day King added tesseracts.
The EnderChests where never going to be a thing as I didn't want to step on Chickens mod, when he stopped updating and a couple of Minecraft versions passed I finally caved to the pressure to add them. Dispite EnderStorage being updated again, I've already added the chests so they are staying.

**Comment by Mohron** [comment]
I'm glad you had the opportunity to release your chests/tanks. I love them! What did you end up deciding as far as joining/leaving a team?

**Comment by ShetiPhian** [comment]
Though I didn't runs tests (if all else fails I'll need to add my own system)
The plan is to use FTBLib as the default team data, with the scoreboard as a fall back.

FTBLib has all the team code, and an api to hook into. The scoreboard just saves the team data in the players data tag making it easy to read.

**Comment by Mohron** [comment]
Sounds good, should be a fantastic feature to aid many players/servers/modpack makers.  Have you ever considered adding your own API? Especially with this feature, it could come in handy 👍.

**Comment by ShetiPhian** [comment]
New options are in the newest builds, now available on Curse

I put the team fetching into ShetiPhianCore,
Anything used by more then one of my mods, or may be used by another mod, or might be useful to someone else gets put in my core.
