### ISSUE TITLE
[Suggestion] Allow disabling "global" Ender-link chests/tanks

### ISSUE THREAD

**Issue by Mohron** [ShetiPhian/Localizations-and-Issues#69]
This request will allow packs and servers to more easily prevent players from trading with others in a progression based modpack where trading outside a team can be highly detrimental to the longevity and feeling of accomplishment provided from completing the challenges the right way. 

This would either require chests and bags to lock on creation or require locking before they could be opened.

**Comment by ShetiPhian** [comment]
Just linking to the other suggestion as my recent post is relevant to this request also.
https://github.com/ShetiPhian/Localizations-and-Issues/issues/68
