### ISSUE TITLE
Server Console Spam with EnderTanks 1.4.5

### ISSUE THREAD

**Issue by glyphtheory** [ShetiPhian/Localizations-and-Issues#7]
Every 45 seconds, the following appears in my server console:
`[Server thread/INFO] [endertanks]: Saving EnderTank Data`
This is only since updating to the latest `endertanks-1.10.2-1.4.5.jar` and its new data logging system. Seems like this should be a DEBUG level console log event instead of INFO, as it's bloating my log files pretty badly. I'm running a custom modpack with 75 total mods, Forge 12.18.2.2125, pretty much all bleeding-edge stuff. I'd love to know if there's a way to disable/mute this. Thanks!

**Comment by ShetiPhian** [comment]
The server console must hide the world saving.

On the client I figured whats one extra line, and it looks like this:
```
[Server thread/INFO]: Saving chunks for level 'New World'/Overworld
[Server thread/INFO] [endertanks]: Saving EnderTank Data
[Server thread/INFO]: Saving chunks for level 'New World'/Nether
[Server thread/INFO]: Saving chunks for level 'New World'/The End
```

There wasn't a way coded in to turn it off, 
In the next build it is set as debug, I need to get the chance to test the newest changes to save functions (stops data lost if something happens during writing)
Should be uploading tonight.

**Comment by ShetiPhian** [comment]
New build uploaded
