### ISSUE TITLE
Allow disabling of Burnium and Endinium entirely

### ISSUE THREAD

**Issue by mileswest07** [ShetiPhian/Localizations-and-Issues#70]
Currently, there is no way to prevent burnium and endinium assets from being created. Case example: Blaze Powder + Coal Dust -> Burnium powder . Should include config to completely disable these two add-ons.

**Comment by ShetiPhian** [comment]
No assets to disable, they share an item id with all the other miscellaneous items.
The only thing to disable is the recipe, not really a need to though (unless they conflict with another mod) as Endinium dust would be pointless to craft and Burnium dust is used by the Ender Table and as a fuel.

**Comment by mileswest07** [comment]
Given the frequency of modpacks nowadays, that conflict is a viable possibility.
