### ISSUE TITLE
Recipe Bugs

### ISSUE THREAD

**Issue by kenijey** [ShetiPhian/Localizations-and-Issues#71]
![1](https://cloud.githubusercontent.com/assets/24831406/25774537/6f263986-3299-11e7-8771-10d0f3e58138.PNG)
![2](https://cloud.githubusercontent.com/assets/24831406/25774538/710e0f76-3299-11e7-91af-d979fe2d2303.PNG)
what could be effecting this?

**Comment by ShetiPhian** [comment]
Well its just a standard shapeless recipe, not much can go wrong.
Either that craft table isn't seeing/using the recipe, or the recipe has been removed.

If you can see the recipe in JEI and/or craft elsewhere (your inventory, the stone craft bench, etc.)
Then its that craftbench (or what ever mod is adding the buttons to the craftbench)

If the recipe is missing, it might be removed by a minetweaker script (if that is the case the pack maker didn't want the flowers craftable into dyes.)

**Comment by kenijey** [comment]
ok it's fixed, after i updated a bunch of mods.
