### ISSUE TITLE
enderlink crash (1.11.2)

### ISSUE THREAD

**Issue by SDUBZ** [ShetiPhian/Localizations-and-Issues#77]
shetiphiancore-1.11.0-3.4.5
multistorage-1.11.0-1.3.7
forge-1.11.2-2309
crash:
[crash-2017-05-28_12.03.15-client.txt](https://github.com/ShetiPhian/Localizations-and-Issues/files/1033952/crash-2017-05-28_12.03.15-client.txt)

**Comment by ShetiPhian** [comment]
Fixed version pushed to curse.
