### ISSUE TITLE
crash with new version of bookshelf

### ISSUE THREAD

**Issue by Hypsellis** [ShetiPhian/Localizations-and-Issues#78]
The 2.0.0.379 version of bookshelf causes Terraqueous to crash https://pastebin.com/nV7md0uP

**Comment by ShetiPhian** [comment]
Looks like Bookshelf has a recipe wrapper, any my use of ArrayList is causing a conflict.
Switching over to using List rather then using ArrayList should fix it.

Give this build a try:
http://www.mediafire.com/file/dype3ep815bv9il/shetiphiancore-1.11.0-3.4.6-rb1.jar

**Comment by Hypsellis** [comment]
It still crashes :(

**Comment by ShetiPhian** [comment]
Could you post the new report?
If its another issue I might be able to fix it, but if its a problem casting ModTrackingList to List Bookshelf is going to need to fix it.

**Comment by Hypsellis** [comment]
Already did, look my old post.

**Comment by ShetiPhian** [comment]
Well at least its not the same spot, that one is in Terraqueous.

This build should solve it.
http://www.mediafire.com/file/512cq71i1pkccem/terraqueous-1.11.0-1.3.12-rb1.jar

Ran a project scan, looks like those where the only two spots I ended up using ArrayList when fetching the recipe list.

**Comment by Hypsellis** [comment]
It seems to work now, but now it's another mod which crash. ^^'

**Comment by ShetiPhian** [comment]
If its the same bug it would be understandable, at one time the recipe list was an ArrayList.
Changes like that go unnoticed until an error happens.

In a couple of days I'll put those versions up on Curse. (gives time to make sure no further errors happen)

**Comment by Mohron** [comment]
I've ran into this problem too but I've just been refusing to update Bookshelf ¯\_(ツ)_/¯.  Glad to see it's getting fixed!

**Comment by ShetiPhian** [comment]
Just uploaded new 1.11 builds, they are now available on Curse.

**Comment by Hypsellis** [comment]
You submitted the api of Terraqueous, not the mod itself. ^^'

**Comment by ShetiPhian** [comment]
Oops,
Corrected.

Thank you. :)
