### ISSUE TITLE
Terraqueus Dense Ores Compatability 

### ISSUE THREAD

**Issue by Mohron** [ShetiPhian/Localizations-and-Issues#79]
terraqueous-1.11.0-1.3.11
shetiphiancore-1.11.0-3.4.5
denseores-1.11-1.0.2

Not sure if we're just using the wrong texture or what but we are having trouble setting up burnium as a dense ore (didn't even try endium). As you can see in the image below the item form is transparent and renders way too large.

![image](https://cloud.githubusercontent.com/assets/3623122/26757967/a13b50f8-4894-11e7-910b-06d67acc1006.png)

Dense Ore Config:
```
    "terraqueous burnium ore" {
        S:baseBlock=terraqueous:earth_ore
        I:baseBlockMeta=1
        S:baseBlockTexture=terraqueous:blocks/burnium_dust
        I:retroGenID=0
        S:underlyingBlockTexture=blocks/netherrack
    }
```

**Comment by ShetiPhian** [comment]
I don't see what that isn't working, from what I can find the config is correct and the block works. (though either not supporting translucent or overlays the texture too many times, maybe there is a config for that)

I think it might be an issue with the DenseOre item model as it would handle the size.

**Comment by Mohron** [comment]
RWTema repos are where issues go to be ignored and die :(

**Comment by ShetiPhian** [comment]
If json models are being used, they can be repaired via a resource pack. 
a parent of block/block will setup position, size and rotation
