### ISSUE TITLE
Crash upon launching pack with 1.11

### ISSUE THREAD

**Issue by RedBullSlurpie** [ShetiPhian/Localizations-and-Issues#8]
So I compiled a small pack for 1.11 to test some mods, and upon launching the pack, I get a crash points towards your mod, heres the crash

http://pastebin.com/HZQpEuEb

**Comment by ShetiPhian** [comment]
This early into a new version of Minecraft Forge is releasing a few builds a day and fixing many bugs.
Backwards compatibility can/will also break without warning.

In Forge build 2142 there was breaking changes made to the OreDictionary.
Anything bellow would work but you don't want to downgrade to it though as several recipes where uncraftable.

I'll compile and upload my current build tonight.

**Comment by ShetiPhian** [comment]
I've uploaded new builds.
