### ISSUE TITLE
Crashing Incomaptability

### ISSUE THREAD

**Issue by purestone9** [ShetiPhian/Localizations-and-Issues#81]
[crash-2017-06-04_13.50.02-server.txt](https://github.com/ShetiPhian/Localizations-and-Issues/files/1050673/crash-2017-06-04_13.50.02-server.txt)
When I use a Turntable from Better With Mods to rotate a block from Terraqueous it crashed my game. Both in single player and on servers as well.

**Comment by primetoxinz** [comment]
To fix this you need to override withRotation(Rotation rotation) in your BlockLog class to uses your axis property rather than the vanilla one.

**Comment by ShetiPhian** [comment]
@purestone9 
This test build should work:
http://www.mediafire.com/file/t9bbwuc1stbw95e/terraqueous-1.11.0-1.3.13-RB1.jar

@primetoxinz 
Thanks for doing most of the leg work, I didn't even need to fire up MCPMappingViewer :)

**Comment by purestone9** [comment]
Thank you very much @ShetiPhian 
The build dose indeed work to fix the problem

**Comment by purestone9** [comment]
@ShetiPhian 
I was wondering if you would be able to release the fix on curse.
In a pack that I play, Colonial Expansion, the pack creator is not going to update it until the fix is released.
If you could release the fix on curse it would be awesome.

**Comment by ShetiPhian** [comment]
Just uploaded, should be available for download shortly.
