### ISSUE TITLE
Cloud Furnace Dupes items

### ISSUE THREAD

**Issue by OrdinatorStouff** [ShetiPhian/Localizations-and-Issues#82]
Cloud furnace appears to "double" items that are not normally smelted. For example if 3 refined storage speed upgrades are put in the left slot, it makes "more" in the output slot and doesn't consume input (aside from the fact those shouldn't be smelt-able in the first place)

Pack: ATM2 0.69
Mod: 1.11.2-1.3.11

This was reported to us (AllTheMods pack team) so this is a secondhand report, but we can certainly do some more testing or gather more information if needed.

**Comment by OrdinatorStouff** [comment]
![2017-06-03_02 55 00 1](https://user-images.githubusercontent.com/6283913/26842872-1f24c46c-4aa3-11e7-8603-d75020971476.png)

**Comment by ShetiPhian** [comment]
http://www.mediafire.com/file/6e652laq2mwtwaw/terraqueous-1.11.0-1.3.14-RB1.jar
This build fixed it for vanilla items, and should work with mod items.
