### ISSUE TITLE
Crash Upon Testing Pack

### ISSUE THREAD

**Issue by ElectricBlue1** [ShetiPhian/Localizations-and-Issues#83]
I have a crash with the mod and there are other crashing mods but i removed them but i still have the issue. Here is the crash --> https://pastebin.com/ZSGZhY2H

**Comment by ShetiPhian** [comment]
@ElectricBlue1 
Not sure if you closed this to report to Thermal Expansion or if you noticed the error.

But just in case
"Caused by: java.lang.RuntimeException: Invalid id 4096 - maximum id range exceeded."
Your out of block Id's and need to remove some mods.

**Comment by ElectricBlue1** [comment]
I have fixed it
