### ISSUE TITLE
Battle of the Mods: BWM vs Terraqueous

### ISSUE THREAD

**Issue by kreezxil** [ShetiPhian/Localizations-and-Issues#84]
I have had the Better With Mods 1.11.2 versions in my Colonial Expansion pack for a while and also your Terraqueous 1.11.2 versions. For the longest time, I'v accepted that breaking dirt, sand, and gravel without a shovel will result in loads and loads of piles as if in punishment for not using a tool. Turns out according to the BWM team, that at most 3 piles were ever to drop from each type of block.

On, a whim, I disabled your doodads droping gravel and sand lumps and the massive multiplication pile drops have stopped and now are in line with what the BWM guys told me it was. 3 piles per block instead from 20 to 64.

**Comment by primetoxinz** [comment]
@ShetiPhian Something about how your `BlockEvent.HarvestDropsEvent` is effecting our drop rates, [here](https://github.com/BeetoGuy/BetterWithMods/blob/1.11/src/main/java/betterwithmods/module/hardcore/HCPiles.java#L77-L96) is our event if it helps you solve it

**Comment by ShetiPhian** [comment]
The setting 'DoodadDropLumps' is only used by BlockDoodad.getDrops, it controls if a stone doodad should drop gravel when broken and if a sandstone doodad should drop sand when broken.


As for my HarvestDropsEvent, I only watch for tall grass, glass, and if the player is holding a scythe

```
    public void harvestDropsEvent(HarvestDropsEvent event)
    {
      if (event.isSilkTouching() || event.getDrops() == null || event.getDrops().isEmpty()) {
        return;
      }

      Block eBlock = event.getState().getBlock();

      if (eBlock == Blocks.DOUBLE_PLANT) {
        if (Values.blockTallGrass != null && event.getState().getBlock().getMetaFromState(event.getState()) == 2) {
          if (event.getWorld().rand.nextInt(8) == 0) {
            ItemStack seed = ForgeHooks.getGrassSeed(event.getWorld().rand, event.getFortuneLevel());
            if (seed != null) {
              event.getDrops().add(seed);
            }
          }
        }
        return;
      }

      if (Settings.INSTANCE.enableGlassShardDrops && Values.itemMain != null) {
        if (eBlock == Blocks.GLASS || eBlock == Blocks.STAINED_GLASS) {
          event.getDrops().add(Values.stacks.get("glass_shard", (event.getWorld().rand.nextInt(2) + 3)));
        } else if (eBlock == Blocks.GLASS_PANE || eBlock == Blocks.STAINED_GLASS_PANE) {
          event.getDrops().add(Values.stacks.get("glass_shard"));
        }
      }

      if (event.getHarvester() == null) {
        return;
      }
      EntityPlayer player = event.getHarvester();

      if (Values.itemMultiTool != null && !player.getHeldItemMainhand().isEmpty() && player.getHeldItemMainhand().getItem() == Values.itemMultiTool) {
        ItemMultiTool.handleDrops(player.getHeldItemMainhand(), player, event.getDrops());
      }
    }
```

**Comment by kreezxil** [comment]
But when I turn the doodad lump dropper on it magnifies greatly the number
of drops I get from dirt, sand, and gravel in BWM.

**Comment by ShetiPhian** [comment]
Settings [line50]
```public boolean  dropLumps;```

ConfigHandler.syncConfig [line 73]
```settings.dropLumps = this.config.getBoolean("DoodadDropLumps", "TWEAKS-DOODADS", true, "Stone doodads will drop lumps of gravel/sandstone");```

ConfigHandler.restructure [line 224]
```this.config.moveProperty("TWEAKS", "DoodadDropLumps","TWEAKS-DOODADS");```

BlockDoodad.getDrops [line 172]
```if (Values.itemMain != null && Settings.INSTANCE.dropLumps) {```


Those are the only places I have used it.
The only way it has any effect on mining anything other then stone, sandstone, or red sandstone doodads, is if another mod is reading it for some reason.
