### ISSUE TITLE
Pergola Walls get destroyed when vines are cut

### ISSUE THREAD

**Issue by YswMusician** [ShetiPhian/Localizations-and-Issues#85]
Whenever I use shears to cut vines, pergola walls get destroyed and only vine is dropped.
(Also, vine with fruit drops no fruit, when collected using shears.)

**Comment by ShetiPhian** [comment]
Just tested in both 1.11 [Forge 13.20.0.2235, and Terraqueous 1.11.0-1.3.13] and 1.10 [Forge 12.18.3.2234, and Terraqueous 1.10.0-1.2.24], both are working correctly.

Some other mod has changed how shears work and are no longer using the default methods. This is not something I can fix. If the other mod has a blacklist adding 'terraqueous:pergola' to it should correct the issue.

**Comment by YswMusician** [comment]
Thanks! Since I'm playing with too many mods, It will take some time.
Modpack I using : All the Mods 2
