### ISSUE TITLE
Missing Textures in 1.12

### ISSUE THREAD

**Issue by Daihok41** [ShetiPhian/Localizations-and-Issues#87]
For some reason my textures for the tools are not showing up in 1.12 version.

**Comment by ShetiPhian** [comment]
https://github.com/ShetiPhian/Localizations-and-Issues/issues/86

Likely related to the event order changes in 1.12, when the game tries to bake the model the list is empty as the event used to fill it now fires after. I've changed my model to handle an empty list at the time of baking.

**Comment by ShetiPhian** [comment]
Update 'terraqueous-1.12.0-1.4.0.2' should solve this issue.
Please post here if it does not.

Note: you'll also need to update ShetiPhianCore to 3.5.0.2
