### ISSUE TITLE
1.12)ender tanks recipes not appearing in jei or working with images from modpage

### ISSUE THREAD

**Issue by SDUBZ** [ShetiPhian/Localizations-and-Issues#90]
Forge:1.12-2405
Jei:1.12-1.1
Ender tanks:1.12-1.6.0.1

**Comment by ShetiPhian** [comment]
It was working, but I suspect the fixes needed for the ore dictionary changed something I need to update to.

This will be fixed in the next release.

**Comment by ShetiPhian** [comment]
I'm a huge idiot -_-
Just opened one of the recipe files and noticed the issue.
When the Forge remap event was made to support placed blocks I renamed the tanks (wanted to do that since 1.8) but I forgot to update the recipe files.

**Comment by ShetiPhian** [comment]
Update 'endertanks-1.12.0-1.6.0.2' should solve this issue.
Please post here if it does not.
