### ISSUE TITLE
EnderTank Uncraftable [1.12]

### ISSUE THREAD

**Issue by nightcipher** [ShetiPhian/Localizations-and-Issues#91]
The EnderTank shows up in JEI, but has no crafting recipe. Using the in game command to bring up the guide also shows no crafting recipe, and assembling the items on the table does not allow for the tank to be crafted. 

ShetiPhianCore - 3.5.0.1
EnderTanks - 1.6.0.1
Forge Mod Loader - 8.0.99.99
Minecraft Forge - 14.21.1.2406

Issue persists when ONLY these mods are installed. Hoping that I'm not missing something silly.

**Comment by ShetiPhian** [comment]
It was working, but I suspect the fixes needed for the ore dictionary changed something I need to update to.

This will be fixed in the next release.

**Comment by ShetiPhian** [comment]
I'm a huge idiot -_-
Just opened one of the recipe files and noticed the issue.
When the Forge remap event was made to support placed blocks I renamed the tanks (wanted to do that since 1.8) but I forgot to update the recipe files.

**Comment by ShetiPhian** [comment]
Update 'endertanks-1.12.0-1.6.0.2' should solve this issue.
Please post here if it does not.
