### ISSUE TITLE
1.12 Terraqueous wood

### ISSUE THREAD

**Issue by Sparksolur** [ShetiPhian/Localizations-and-Issues#94]
The problem is converting the wood to planks. Apple wood turns into mango planks, cherry into lemon planks, orange to plum planks. Pear and peach are okay, but the other five types of wood don't turn into planks at all.

**Comment by ShetiPhian** [comment]
Looking at the banana plank recipe file I see the error.
After copy and pasting I missed changing the block id in the ingredients section.

I should be able to correct those and push an update after work tomorrow.

**Comment by ShetiPhian** [comment]
Just uploaded 1.4.0.3 to Curse.
