### ISSUE TITLE
Privated ender chest 1.12

### ISSUE THREAD

**Issue by p0mess** [ShetiPhian/Localizations-and-Issues#95]
Privated ender chest crashes the client if he will replaced. 
[crash-2017-07-21_18.38.10-client.txt](https://github.com/ShetiPhian/Localizations-and-Issues/files/1165850/crash-2017-07-21_18.38.10-client.txt)

**Comment by ShetiPhian** [comment]
I see where the crash happened but not the why.
Please provide step by step instruction for reproducing this crash.

**Comment by p0mess** [comment]
1. i am place the chest
2. private him
3. private ender bag (shift+rightclick to chest)
4. remove chest
5. again place the chest and client was crashed

**Comment by p0mess** [comment]
New details:
client crashes when chest was placed to block's side. If chest was placed to top side of block, client was not crashes.

**Comment by ShetiPhian** [comment]
At first I was thinking there was something going on with the tile entity, but looking at the steps to reproduce the crash makes me think its an issue in my item stack helper class. When I worked around a strange issue with the bags I made changes in that helper class, might have cause the problem then.

**Comment by p0mess** [comment]
You can close issue. Its forge bug, after the last update chests working normally. I'm sorry to trouble you.

**Comment by ShetiPhian** [comment]
Well I no no longer need to find out what caused the variable to be null, but I'll still add a null check to stop that crash from happening again.
