### ISSUE TITLE
[Resource] es_ES/MX translation

### ISSUE THREAD

**Issue by Dorzar** [ShetiPhian/Localizations-and-Issues#96]
!---------------------------------------- MultiBeds en_US.lang Localization ---------------------------------------!
! Keep file encoded with UTF-8 to support chat formatting http://minecraft.gamepedia.com/Formatting_codes
! msg entries can span multiple lines, use <br> to indicate a line break.
//Translate by: Dorzar / VeryHardChamp
Última actualización: 23/07/2017

!------------------------------------------------------ MISC ------------------------------------------------------!
itemGroup.multibeds=MultiBeds

!-------------------------------------------------- ITEMS/BLOCKS --------------------------------------------------!
item.multibeds.beds.baffle.name=Cojines de pluma
item.multibeds.beds.cloud.name=Cama de nubes
item.multibeds.beds.earth.name=Cama
item.multibeds.beds.spread.name=Cubrecama
item.multibeds.beds.decorative.name=Cubrecama decorado

**Comment by ShetiPhian** [comment]
added, this will appear in future builds
